// packages/govtnz-ds/build_src/react-ts/DateInput.tsx
import * as React from "react";

type Props = {
  error?: boolean | undefined;
  hintId?: string | undefined;
  errorId?: string | undefined;
  label?: React.ReactNode;
  hint?: React.ReactNode;
  id?: string | undefined;
  dayId?: string | undefined;
  name: string;
  disabled?: boolean | undefined;
  readOnly?: boolean | undefined;
  autoFocus?: boolean | undefined;
  value?: string | undefined;
  spellCheck?: boolean | undefined;
  autoComplete: React.InputHTMLAttributes<HTMLInputElement>["autoComplete"];
  onChange: any;
  monthId?: string | undefined;
  yearId?: string | undefined;
};

const DateInput = ({
  error,
  hintId,
  errorId,
  label,
  hint,
  id,
  dayId,
  name,
  disabled,
  readOnly,
  autoFocus,
  value,
  spellCheck,
  autoComplete,
  onChange,
  monthId,
  yearId
}: Props) => (
  <div
    className={`g-dateInput-form-group${
      error ? " g-dateInput-form-group--error" : ""
    }`}
  >
    <fieldset
      aria-describedby={
        hintId !== undefined || errorId !== undefined
          ? `${hintId ? hintId : ""}${errorId ? " " + errorId : ""}`
          : undefined
      }
      className="g-fieldset"
      role="group"
    >
      <legend className="g-fieldset__legend g-fieldset__legend--xl">
        {label !== undefined ? (
          label
        ) : (
          <React.Fragment>Example label</React.Fragment>
        )}
      </legend>
      <span className="g-dateInput-hint" id={hintId}>
        {hint !== undefined ? (
          hint
        ) : (
          <React.Fragment>Example hint</React.Fragment>
        )}
      </span>
      {error !== undefined ? (
        <React.Fragment>
          <span className="g-dateInput-error-message" id={errorId}>
            <span className="g-dateInput-visually-hidden">Error: </span>
            {error !== undefined ? (
              error
            ) : (
              <React.Fragment>Example error</React.Fragment>
            )}
          </span>
        </React.Fragment>
      ) : (
        ""
      )}

      <div className="g-date-input" id={id}>
        <div className="g-date-input__item">
          <div className="g-dateInput-form-group">
            <label
              className="g-dateInput-label g-date-input__label"
              htmlFor={dayId}
            >
              Day
            </label>
            <input
              className={`g-dateInput-input g-date-input__input g-dateInput-input--width-2${
                error ? " g-dateInput-input--error" : ""
              }`}
              id={dayId}
              maxLength={2}
              name={name}
              pattern="[0-9]*"
              type="text"
              disabled={disabled}
              readOnly={readOnly}
              autoFocus={autoFocus}
              value={value}
              spellCheck={spellCheck}
              autoComplete={autoComplete}
              onChange={onChange}
            />
          </div>
        </div>
        <div className="g-date-input__item">
          <div className="g-dateInput-form-group">
            <label
              className="g-dateInput-label g-date-input__label"
              htmlFor={monthId}
            >
              Month
            </label>
            <input
              className={`g-dateInput-input g-date-input__input g-dateInput-input--width-2${
                error ? " g-dateInput-input--error" : ""
              }`}
              id={monthId}
              maxLength={2}
              name={name}
              pattern="[0-9]*"
              type="text"
              disabled={disabled}
              readOnly={readOnly}
              autoFocus={autoFocus}
              value={value}
              spellCheck={spellCheck}
              autoComplete={autoComplete}
              onChange={onChange}
            />
          </div>
        </div>
        <div className="g-date-input__item">
          <div className="g-dateInput-form-group">
            <label
              className="g-dateInput-label govuk-date-input__label"
              htmlFor={yearId}
            >
              Year
            </label>
            <input
              className={`g-dateInput-input g-date-input__input g-dateInput-input--width-4${
                error ? " g-dateInput-input--error" : ""
              }`}
              id={yearId}
              maxLength={4}
              name={name}
              pattern="[0-9]*"
              type="text"
              disabled={disabled}
              readOnly={readOnly}
              autoFocus={autoFocus}
              value={value}
              spellCheck={spellCheck}
              autoComplete={autoComplete}
              onChange={onChange}
            />
          </div>
        </div>
      </div>
    </fieldset>
  </div>
);

export default DateInput;

// packages/govtnz-ds/build_src/angular/DateInput.ts
import { Component, Input } from "@angular/core";
@Component({
  selector: "g-DateInput",
  template: `
<div class="g-dateInput-form-group{{error ? " g-dateInput-form-group--error" : ""}}">

  
<fieldset aria-describedby="{{hintId ?  hintId : ""}}{{errorId ? " " +  errorId : ""}}" class="g-fieldset" role="group">

    
<legend class="g-fieldset__legend g-fieldset__legend--xl">

      <slot name="label"></slot>
    

</legend>


    
<span class="g-dateInput-hint" id="{{hintId}}">

      <slot name="hint"></slot>
    

</span>


    
      
<span class="g-dateInput-error-message" id="{{errorId}}">

        
<span class="g-dateInput-visually-hidden">
Error: 

</span>


        <slot name="error"></slot>
      

</span>


    
    
<div class="g-date-input" id="{{id}}">

      
<div class="g-date-input__item">

        
<div class="g-dateInput-form-group">

          
<label class="g-dateInput-label g-date-input__label" for="{{dayId}}">

            Day
          

</label>


          
<input class="g-dateInput-input g-date-input__input g-dateInput-input--width-2{{error ? " g-dateInput-input--error" : ""}}" id="{{dayId}}" maxlength="2" name="{{name}}" pattern="[0-9]*" type="text" disabled="{{disabled}}" readonly="{{readOnly}}" autofocus="{{autoFocus}}" value="{{value}}" spellcheck="{{spellCheck}}" autocomplete="{{autoComplete}}"/>

        

</div>


      

</div>


      
<div class="g-date-input__item">

        
<div class="g-dateInput-form-group">

          
<label class="g-dateInput-label g-date-input__label" for="{{monthId}}">

            Month
          

</label>


          
<input class="g-dateInput-input g-date-input__input g-dateInput-input--width-2{{error ? " g-dateInput-input--error" : ""}}" id="{{monthId}}" maxlength="2" name="{{name}}" pattern="[0-9]*" type="text" disabled="{{disabled}}" readonly="{{readOnly}}" autofocus="{{autoFocus}}" value="{{value}}" spellcheck="{{spellCheck}}" autocomplete="{{autoComplete}}"/>

        

</div>


      

</div>


      
<div class="g-date-input__item">

        
<div class="g-dateInput-form-group">

          
<label class="g-dateInput-label g-date-input__label" for="{{yearId}}">

            Year
          

</label>


          
<input class="g-dateInput-input g-date-input__input g-dateInput-input--width-4{{error ? " g-dateInput-input--error" : ""}}" id="{{yearId}}" maxlength="4" name="{{name}}" pattern="[0-9]*" type="text" disabled="{{disabled}}" readonly="{{readOnly}}" autofocus="{{autoFocus}}" value="{{value}}" spellcheck="{{spellCheck}}" autocomplete="{{autoComplete}}"/>

        

</div>


      

</div>


    

</div>


  

</fieldset>




</div>


`
})
export class AppComponent {
  @Input() error: boolean | undefined;
  @Input() hintId: string | undefined;
  @Input() errorId: string | undefined;
  @Input() label: React.ReactNode;
  @Input() hint: React.ReactNode;
  @Input() id: string | undefined;
  @Input() dayId: string | undefined;
  @Input() name: string;
  @Input() disabled: boolean | undefined;
  @Input() readOnly: boolean | undefined;
  @Input() autoFocus: boolean | undefined;
  @Input() value: string | undefined;
  @Input() spellCheck: boolean | undefined;
  @Input() autoComplete: any;
  @Input() monthId: string | undefined;
  @Input() yearId: string | undefined;
  title = "DateInput";
}
