// packages/govtnz-ds/build_src/react-js/FieldsetBlock.js
import React from "react";

const FieldsetBlock = ({
  hintId,
  errorId,
  legend,
  hint,
  errorId2,
  error,
  children
}) => (
  <div className="g-fieldsetBlock-form-group">
    <fieldset
      aria-describedby={
        hintId !== undefined || errorId !== undefined
          ? `${hintId ? hintId : ""}${errorId ? " " + errorId : ""}`
          : undefined
      }
      className="g-fieldset"
    >
      <legend className="g-fieldset__legend">
        {legend !== undefined ? (
          legend
        ) : (
          <React.Fragment>Legend text</React.Fragment>
        )}
      </legend>
      {hintId !== undefined ? (
        <React.Fragment>
          <div className="g-fieldsetBlock-hint" id={hintId}>
            {hint !== undefined ? (
              hint
            ) : (
              <React.Fragment>Hint text</React.Fragment>
            )}
          </div>
        </React.Fragment>
      ) : (
        ""
      )}
      {errorId2 !== undefined ? (
        <React.Fragment>
          <div className="g-fieldsetBlock-error-message" id={errorId}>
            <span className="g-fieldsetBlock-visually-hidden">Error:</span>
            {error !== undefined ? (
              error
            ) : (
              <React.Fragment>Error text</React.Fragment>
            )}
          </div>
        </React.Fragment>
      ) : (
        ""
      )}
      <div>
        {children !== undefined ? (
          children
        ) : (
          <React.Fragment>Fieldset contents</React.Fragment>
        )}
      </div>
    </fieldset>
  </div>
);

export default FieldsetBlock;

// packages/govtnz-ds/build_src/angular/FieldsetBlock.ts
import { Component, Input } from "@angular/core";
@Component({
  selector: "g-FieldsetBlock",
  template: `
<div class="g-fieldsetBlock-form-group">

  
<fieldset aria-describedby="{{hintId ?  hintId : ""}}{{errorId ? " " +  errorId : ""}}" class="g-fieldset">

    
<legend class="g-fieldset__legend">

      <slot name="legend"></slot>
    

</legend>


    
      
<div class="g-fieldsetBlock-hint" id="{{hintId}}">

        <slot name="hint"></slot>
      

</div>


    
    
      
<div class="g-fieldsetBlock-error-message" id="{{errorId}}">

        
<span class="g-fieldsetBlock-visually-hidden">

          Error:
        

</span>


        <slot name="error"></slot>
      

</div>


    
    
<div>
<slot></slot>

</div>


  

</fieldset>




</div>


`
})
export class AppComponent {
  @Input() hintId: string | undefined;
  @Input() errorId: string | undefined;
  @Input() legend: React.ReactNode;
  @Input() hint: React.ReactNode;
  @Input() errorId2: React.ReactNode;
  @Input() error: React.ReactNode;
  @Input() children: React.ReactNode;
  title = "FieldsetBlock";
}
