// packages/govtnz-ds/build_src/react-ts/Fieldset.tsx
import * as React from "react";

type Props = {
  hintId?: string | undefined;
  children?: React.ReactNode;
};

const Fieldset = ({ hintId, children }: Props) => (
  <div className="g-fieldset-form-group">
    <fieldset aria-describedby={hintId} className="g-fieldset">
      {children !== undefined ? (
        children
      ) : (
        <React.Fragment>Legend and other fieldset contents...</React.Fragment>
      )}
    </fieldset>
  </div>
);
Fieldset.props = ["hintId", "children"];
export default Fieldset;

// packages/govtnz-ds/build_src/angular/Fieldset.ts
import { Component, Input } from "@angular/core";
@Component({
  selector: "g-Fieldset",
  template: `
    <div class="g-form-group">
      <fieldset aria-describedby="{{ hintId }}" class="g-fieldset">
        <slot></slot>
      </fieldset>
    </div>
  `
})
export class AppComponent {
  @Input() hintId: string | undefined;
  @Input() children: React.ReactNode;
  title = "Fieldset";
}
