// packages/govtnz-ds/build_src/react-ts/FileUpload.tsx
import React from "react";

type Props = {
  id?: string;
  required?: boolean;
  disabled?: boolean;
  readOnly?: boolean;
  autoFocus?: boolean;
  name: string;
  onChange?: React.InputHTMLAttributes<HTMLInputElement>["onChange"];
  ref?: React.RefObject<HTMLInputElement>;
};

const FileUpload = ({
  id,
  required,
  disabled,
  readOnly,
  autoFocus,
  name,
  onChange,
  ref
}: Props) => (
  <div className="g-fileUpload__form-group">
    <label className="g-fileUpload__label" htmlFor={id}>
      Upload a file
    </label>
    <input
      className="g-fileUpload__input"
      id={id}
      name={name}
      type="file"
      required={required}
      disabled={
        disabled !== undefined ? disabled.toString() === "true" : undefined
      }
      readOnly={readOnly}
      autoFocus={autoFocus}
      onChange={onChange}
      ref={ref}
    />
  </div>
);

export default FileUpload;

// packages/govtnz-ds/build_src/angular/FileUpload.ts
import { Component, Input } from "@angular/core";
@Component({
  selector: "g-FileUpload",
  template: `
    <div class="g-fileUpload__form-group">
      <label class="g-fileUpload__label" for="{{ id }}">
        Upload a file
      </label>

      <input
        class="g-fileUpload__input"
        id="{{ id }}"
        name="{{ name }}"
        type="file"
        required="{{ required }}"
        disabled="{{ disabled }}"
        readonly="{{ readOnly }}"
        autofocus="{{ autoFocus }}"
      />
    </div>
  `
})
export class AppComponent {
  @Input() id: string | undefined;
  @Input() required: boolean | undefined;
  @Input() disabled: boolean | undefined;
  @Input() readOnly: boolean | undefined;
  @Input() autoFocus: boolean | undefined;
  @Input() name: string;
  title = "FileUpload";
}
