// packages/govtnz-ds/build_src/react-js/FlexRow.js
import React from "react";

const constants = {
  xsVerticalAlign: {
    top: "g-flex-top-xs",
    middle: "g-flex-middle-xs",
    bottom: "g-flex-bottom-xs"
  },
  smVerticalAlign: {
    top: "g-flex-top-sm",
    middle: "g-flex-middle-sm",
    bottom: "g-flex-bottom-sm"
  },
  mdVerticalAlign: {
    top: "g-flex-top-md",
    middle: "g-flex-middle-md",
    bottom: "g-flex-bottom-md"
  },
  lgVerticalAlign: {
    top: "g-flex-top-lg",
    middle: "g-flex-middle-lg",
    bottom: "g-flex-bottom-lg"
  },
  xsReversed: { true: "g-flex-reversed-xs", false: "g-flex-not-reversed-xs" },
  smReversed: { true: "g-flex-reversed-sm", false: "g-flex-not-reversed-sm" },
  mdReversed: { true: "g-flex-reversed-md", false: "g-flex-not-reversed-md" },
  lgReversed: { true: "g-flex-reversed-lg", false: "g-flex-not-reversed-lg" }
};

const FlexRow = ({
  xsVerticalAlign,
  smVerticalAlign,
  mdVerticalAlign,
  lgVerticalAlign,
  xsReversed,
  smReversed,
  mdReversed,
  lgReversed,
  isReversed,
  className,
  children
}) => (
  <div
    className={`g-flex-row${
      constants.xsVerticalAlign[xsVerticalAlign] !== undefined
        ? " " + constants.xsVerticalAlign[xsVerticalAlign]
        : ""
    }${
      constants.smVerticalAlign[smVerticalAlign] !== undefined
        ? " " + constants.smVerticalAlign[smVerticalAlign]
        : ""
    }${
      constants.mdVerticalAlign[mdVerticalAlign] !== undefined
        ? " " + constants.mdVerticalAlign[mdVerticalAlign]
        : ""
    }${
      constants.lgVerticalAlign[lgVerticalAlign] !== undefined
        ? " " + constants.lgVerticalAlign[lgVerticalAlign]
        : ""
    }${
      constants.xsReversed[xsReversed] !== undefined
        ? " " + constants.xsReversed[xsReversed]
        : ""
    }${
      constants.smReversed[smReversed] !== undefined
        ? " " + constants.smReversed[smReversed]
        : ""
    }${
      constants.mdReversed[mdReversed] !== undefined
        ? " " + constants.mdReversed[mdReversed]
        : ""
    }${
      constants.lgReversed[lgReversed] !== undefined
        ? " " + constants.lgReversed[lgReversed]
        : ""
    }${isReversed ? " g-flex-reverse" : ""}${className ? " " + className : ""}`}
  >
    {children !== undefined ? (
      children
    ) : (
      <React.Fragment>Columns...</React.Fragment>
    )}
  </div>
);

export default FlexRow;

// packages/govtnz-ds/build_src/angular/FlexRow.ts
import { Component, Input } from "@angular/core";
@Component({
  selector: "g-FlexRow",
  template: `
<div class="g-flex-row{{constants.xsVerticalAlign[xsVerticalAlign] !== undefined ? " " +  constants.xsVerticalAlign[xsVerticalAlign] : ""}}{{constants.smVerticalAlign[smVerticalAlign] !== undefined ? " " +  constants.smVerticalAlign[smVerticalAlign] : ""}}{{constants.mdVerticalAlign[mdVerticalAlign] !== undefined ? " " +  constants.mdVerticalAlign[mdVerticalAlign] : ""}}{{constants.lgVerticalAlign[lgVerticalAlign] !== undefined ? " " +  constants.lgVerticalAlign[lgVerticalAlign] : ""}}{{constants.xsReversed[xsReversed] !== undefined ? " " +  constants.xsReversed[xsReversed] : ""}}{{constants.smReversed[smReversed] !== undefined ? " " +  constants.smReversed[smReversed] : ""}}{{constants.mdReversed[mdReversed] !== undefined ? " " +  constants.mdReversed[mdReversed] : ""}}{{constants.lgReversed[lgReversed] !== undefined ? " " +  constants.lgReversed[lgReversed] : ""}}{{isReversed ? " g-flex-reverse" : ""}}">

  <slot></slot>


</div>


`
})
export class AppComponent {
  @Input() xsVerticalAlign: "top" | "middle" | "bottom" | undefined;
  @Input() smVerticalAlign: "top" | "middle" | "bottom" | undefined;
  @Input() mdVerticalAlign: "top" | "middle" | "bottom" | undefined;
  @Input() lgVerticalAlign: "top" | "middle" | "bottom" | undefined;
  @Input() xsReversed: "true" | "false" | undefined;
  @Input() smReversed: "true" | "false" | undefined;
  @Input() mdReversed: "true" | "false" | undefined;
  @Input() lgReversed: "true" | "false" | undefined;
  @Input() isReversed: boolean | undefined;
  @Input() children: React.ReactNode;
  title = "FlexRow";
}
