// packages/govtnz-ds/build_src/react-js/FlexContainer.js
import React from "react";

const constants = {
  width: { fixed: "g-flex-container", fluid: "g-flex-container-fluid" }
};

const FlexContainer = ({ width, children }) => (
  <div
    className={
      constants.width[width] !== undefined ? constants.width[width] : ""
    }
  >
    {children !== undefined ? (
      children
    ) : (
      <React.Fragment>Rows...</React.Fragment>
    )}
  </div>
);

export default FlexContainer;

// packages/govtnz-ds/build_src/angular/FlexContainer.ts
import { Component, Input } from "@angular/core";
@Component({
  selector: "g-FlexContainer",
  template: `
<div class="{{constants.width[width] !== undefined ?  constants.width[width] : ""}}">
   <slot></slot> 

</div>

 `
})
export class AppComponent {
  @Input() width: "fixed" | "fluid";
  @Input() children: React.ReactNode;
  title = "FlexContainer";
}
