// packages/govtnz-ds/build_src/react-js/FooterLink.js
import React from "react";

const FooterLink = ({ href, rel, target, onClick, children }) => (
  <li className="g-footer-link">
    <a
      className="g-footer-link__a"
      href={href}
      rel={rel}
      target={target}
      onClick={onClick}
    >
      {children !== undefined ? (
        children
      ) : (
        <React.Fragment> Example header content </React.Fragment>
      )}
    </a>
  </li>
);

export default FooterLink;

// packages/govtnz-ds/build_src/angular/FooterLink.ts
import { Component, Input } from "@angular/core";
@Component({
  selector: "g-FooterLink",
  template: `
    <li class="g-footer-link">
      <a
        class="g-footer-link__a"
        href="{{ href }}"
        rel="{{ rel }}"
        target="{{ target }}"
      >
        <slot></slot>
      </a>
    </li>
  `
})
export class AppComponent {
  @Input() href: string;
  @Input() rel: string | undefined;
  @Input() target: any | undefined;
  @Input() children: React.ReactNode;
  title = "FooterLink";
}
