// packages/govtnz-ds/build_src/vue-js/InsetText.vue
<template>
  <div class="g-inset-text">
    It can take up to 8 weeks to register a lasting power of attorney if there
    are no mistakes in the application.
  </div>
</template>
<script>
import Vue from "vue";

export default Vue.extend({
  props: {},
  computed: {}
});
</script>
<style scoped>
.g-insetText-hint > * {
  margin-top: 0px;
}
</style>

// packages/govtnz-ds/build_src/angular/InsetText.ts
import { Component, Input } from "@angular/core";
@Component({
  selector: "g-InsetText",
  template: `
    <div class="g-inset-text">
      It can take up to 8 weeks to register a lasting power of attorney if there
      are no mistakes in the application.
    </div>
  `
})
export class AppComponent {
  title = "InsetText";
}
