// packages/govtnz-ds/build_src/react-ts/MainNavLink.tsx
import React from "react";

type Props = {
  ariaCurrent?: React.InputHTMLAttributes<HTMLInputElement>["aria-current"];
  href: string;
  rel?: string;
  target?: React.AnchorHTMLAttributes<HTMLAnchorElement>["target"];
  onClick?: React.AnchorHTMLAttributes<HTMLAnchorElement>["onClick"];
  children?: React.ReactNode;
};

const MainNavLink = ({
  ariaCurrent,
  href,
  rel,
  target,
  onClick,
  children
}: Props) => (
  <li className="g-main-nav__link">
    {" "}
    <a
      aria-current={ariaCurrent}
      className={`g-main-nav__link__a${
        ariaCurrent ? " g-main-nav__link__a--active" : ""
      }`}
      href={href}
      rel={rel}
      target={target}
      onClick={onClick}
    >
      {" "}
      {children !== undefined ? (
        children
      ) : (
        <React.Fragment> Example item text </React.Fragment>
      )}{" "}
    </a>{" "}
  </li>
);

export default MainNavLink;

// packages/govtnz-ds/build_src/angular/MainNavLink.ts
import { Component, Input } from "@angular/core";
@Component({
  selector: "g-MainNavLink",
  template: `
<li class="g-main-nav__link">

  
<a aria-current="{{ariaCurrent}}" class="g-main-nav__link__a{{ariaCurrent ? " g-main-nav__link__a--active" : ""}}" href="{{href}}" rel="{{rel}}" target="{{target}}">

    <slot></slot>
  

</a>




</li>


`
})
export class AppComponent {
  @Input() ariaCurrent: any | undefined;
  @Input() href: string;
  @Input() rel: string | undefined;
  @Input() target: any | undefined;
  @Input() children: React.ReactNode;
  title = "MainNavLink";
}
