// packages/govtnz-ds/build_src/react-ts/Ol.tsx
import React from "react";

type Props = {
  numbered?: boolean;
  children?: React.ReactNode;
};

const Ol = ({ numbered, children }: Props) => (
  <ol className={`g-list${numbered ? " g-list--number" : ""}`}>
    {children !== undefined ? (
      children
    ) : (
      <React.Fragment>Example text</React.Fragment>
    )}
  </ol>
);

export default Ol;

// packages/govtnz-ds/build_src/angular/Ol.ts
import { Component, Input } from "@angular/core";
@Component({
  selector: "g-Ol",
  template: `
<ol class="g-ol-list{{numbered ? " g-ol-list--number" : ""}}">
<slot></slot>

</ol>

`
})
export class AppComponent {
  @Input() numbered: boolean | undefined;
  @Input() children: React.ReactNode;
  title = "Ol";
}
