// packages/govtnz-ds/build_src/react-js/RadioBlock.js
import React from "react";

const RadioBlock = ({
  radioId,
  hintId,
  name,
  disabled,
  readOnly,
  autoFocus,
  value,
  checked,
  onChange,
  label,
  hint
}) => (
  <div className="g-radios__item">
    <input
      aria-describedby={hintId}
      className="g-radios__input"
      id={radioId}
      name={name}
      type="radio"
      disabled={disabled}
      readOnly={readOnly}
      autoFocus={autoFocus}
      value={value}
      checked={checked}
      onChange={onChange}
    />
    <label className="g-radioBlock-label g-radios__label" htmlFor={radioId}>
      {label !== undefined ? (
        label
      ) : (
        <React.Fragment>Label text</React.Fragment>
      )}
    </label>
    {hintId !== undefined ? (
      <React.Fragment>
        <div className="g-radioBlock-hint g-checkboxes__hint" id={hintId}>
          {hint !== undefined ? (
            hint
          ) : (
            <React.Fragment>Hint text</React.Fragment>
          )}
        </div>
      </React.Fragment>
    ) : (
      ""
    )}
  </div>
);

export default RadioBlock;

// packages/govtnz-ds/build_src/angular/RadioBlock.ts
import { Component, Input } from "@angular/core";
@Component({
  selector: "g-RadioBlock",
  template: `
    <div class="g-radios__item">
      <input
        aria-describedby="{{ hintId }}"
        class="g-radios__input"
        id="{{ radioId }}"
        name="{{ name }}"
        type="radio"
        disabled="{{ disabled }}"
        readonly="{{ readOnly }}"
        autofocus="{{ autoFocus }}"
        value="{{ value }}"
        checked="{{ checked }}"
      />

      <label class="g-radioBlock-label g-radios__label" for="{{ radioId }}">
        <slot name="label"></slot>
      </label>

      <div class="g-radioBlock-hint g-checkboxes__hint" id="{{ hintId }}">
        <slot name="hint"></slot>
      </div>
    </div>
  `
})
export class AppComponent {
  @Input() radioId: string | undefined;
  @Input() hintId: string | undefined;
  @Input() name: string;
  @Input() disabled: boolean | undefined;
  @Input() readOnly: boolean | undefined;
  @Input() autoFocus: boolean | undefined;
  @Input() value: string | undefined;
  @Input() checked: boolean | undefined;
  @Input() label: React.ReactNode;
  @Input() hint: React.ReactNode;
  title = "RadioBlock";
}
