// packages/govtnz-ds/build_src/react-ts/Radios.tsx
import React from "react";

type Props = {
  inline?: boolean;
  big?: boolean;
  children?: React.ReactNode;
};

const Radios = ({ inline, big, children }: Props) => (
  <div
    className={`g-radios${inline ? " g-radios--inline" : ""}${
      big ? " g-radios--big" : ""
    }`}
  >
    {" "}
    {children !== undefined ? (
      children
    ) : (
      <React.Fragment>Radio components</React.Fragment>
    )}{" "}
  </div>
);

export default Radios;

// packages/govtnz-ds/build_src/angular/Radios.ts
import { Component, Input } from "@angular/core";
@Component({
  selector: "g-Radios",
  template: `
<div class="g-radios{{inline ? " g-radios--inline" : ""}}{{big ? " g-radios--big" : ""}}">
   <slot></slot> 

</div>

 `
})
export class AppComponent {
  @Input() inline: boolean | undefined;
  @Input() big: boolean | undefined;
  @Input() children: React.ReactNode;
  title = "Radios";
}
