// packages/govtnz-ds/build_src/react-ts/SelectBlock.tsx
import React from "react";

type Props = {
  errorId?: boolean;
  selectId?: string;
  label?: React.ReactNode;
  error: boolean;
  name: string;
  required?: boolean;
  multiple?: boolean;
  onChange?: React.SelectHTMLAttributes<HTMLSelectElement>["onChange"];
  ref?: React.RefObject<HTMLSelectElement>;
};

const SelectBlock = ({
  errorId,
  selectId,
  label,
  error,
  name,
  required,
  multiple,
  onChange,
  ref
}: Props) => (
  <div className={errorId ? "g-form-group--error" : ""}>
    <label className="g-selectBlock-label" htmlFor={selectId}>
      {label !== undefined ? (
        label
      ) : (
        <React.Fragment>Example label text</React.Fragment>
      )}
    </label>
    <select
      className={`g-selectBlock-select${
        error ? " g-selectBlock-select--error" : ""
      }`}
      id={selectId}
      name={name}
      required={required}
      multiple={multiple}
      onChange={onChange}
      ref={ref}
    >
      Options
    </select>
  </div>
);

export default SelectBlock;

// packages/govtnz-ds/build_src/angular/SelectBlock.ts
import { Component, Input } from "@angular/core";
@Component({
  selector: "g-SelectBlock",
  template: `
<div class="{{errorId ? "g-form-group--error" : ""}}">

  
<label class="g-selectBlock-label" for="{{selectId}}">

    <slot name="label"></slot>
  

</label>


  
<select class="g-selectBlock-select{{error ? " g-selectBlock-select--error" : ""}}" id="{{selectId}}" name="{{name}}" required="{{required}}" multiple="{{multiple}}">
Options

</select>




</div>


`
})
export class AppComponent {
  @Input() errorId: boolean | undefined;
  @Input() selectId: string | undefined;
  @Input() label: React.ReactNode;
  @Input() error: boolean;
  @Input() name: string;
  @Input() required: boolean | undefined;
  @Input() multiple: boolean | undefined;
  title = "SelectBlock";
}
