// packages/govtnz-ds/build_src/react-js/SkipLink.js
import React from "react";

const constants = {
  target: { Blank: "_blank", Top: "_top", Self: "_self", Parent: "_parent" }
};

const SkipLink = ({ href, rel, target }) => (
  <a
    className="g-skip-link"
    href={href}
    rel={rel}
    target={constants.target[target]}
  >
    Skip to main content
  </a>
);

export default SkipLink;

// packages/govtnz-ds/build_src/angular/SkipLink.ts
import { Component, Input } from "@angular/core";
@Component({
  selector: "g-SkipLink",
  template: `
    <a
      class="g-skip-link"
      href="{{ href }}"
      rel="{{ rel }}"
      target="{{ target }}"
    >
      Skip to main content
    </a>
  `
})
export class AppComponent {
  @Input() href: string;
  @Input() rel: string | undefined;
  @Input() target: any | undefined;
  title = "SkipLink";
}
