// packages/metatemplate/examples/input/angular/input.ts
import { Component, Input } from "@angular/core";
@Component({
  selector: "g-input",
  template: `
    <input class="{{ hasError ? "error" : "" }}" disabled="{{ disabled }}"
    readonly="{{ readOnly }}" autofocus="{{ autoFocus }}" name="{{ name }}"
    value="{{ value }}" min="{{ min }}" max="{{ max }}" type="{{ type }}"
    spellcheck="{{ spellCheck }}" maxlength="{{ maxLength }}" autocomplete="{{
      autoComplete
    }}"/>
  `
})
export class AppComponent {
  @Input() hasError: boolean;
  @Input() disabled: boolean | undefined;
  @Input() readOnly: boolean | undefined;
  @Input() autoFocus: boolean | undefined;
  @Input() name: string;
  @Input() value: string | undefined;
  @Input() min: number | undefined;
  @Input() max: number | undefined;
  @Input() type: any;
  @Input() spellCheck: boolean | undefined;
  @Input() maxLength: number | undefined;
  @Input() autoComplete: any;
  title = "input";
}

// packages/metatemplate/examples/input/react-js/input.js
import React from "react";

const Input = ({
  hasError,
  disabled,
  readOnly,
  autoFocus,
  name,
  value,
  min,
  max,
  type,
  spellCheck,
  maxLength,
  autoComplete,
  onChange,
  ref
}) => (
  <input
    className={hasError ? "error" : ""}
    disabled={disabled}
    readOnly={readOnly}
    autoFocus={autoFocus}
    name={name}
    value={value}
    min={min}
    max={max}
    type={type}
    spellCheck={spellCheck}
    maxLength={maxLength}
    autoComplete={autoComplete}
    onChange={onChange}
    ref={ref}
  />
);

export default Input;
