// packages/metatemplate/examples/container/react-ts/container.tsx
import React from "react";

type Props = {
  width: "fixed" | "fluid";
  children?: React.ReactNode;
};

const constants = {
  width: { fixed: "g-flex-container", fluid: "g-flex-container-fluid" }
};

const Container = ({ width, children }: Props) => (
  <div
    className={
      constants.width[width] !== undefined ? constants.width[width] : ""
    }
  >
    {children !== undefined ? (
      children
    ) : (
      <React.Fragment>Rows...</React.Fragment>
    )}
  </div>
);

export default Container;

// packages/metatemplate/examples/container/angular/container.ts
import { Component, Input } from "@angular/core";
@Component({
  selector: "g-container",
  template: `
<div class="{{constants.width[width] !== undefined ?  constants.width[width] : ""}}">

  <slot></slot>


</div>


`
})
export class AppComponent {
  @Input() width: "fixed" | "fluid";
  @Input() children: React.ReactNode;
  title = "container";
}
