// packages/govtnz-ds/build_src/react-js-styled-components/Fieldset.js
import React from "react";
import styled from "styled-components";

const StyledDiv = styled.div`
  margin-bottom: 20px;
  @media (min-width: 40.0625em) {
    margin-bottom: 30px;
  }
  :last-of-type {
    margin-bottom: 0;
  }
  padding: 0;
  border: 0;
  margin-bottom: 5px;
  margin-top: 0px;
`;

const StyledFieldset = styled.fieldset`
  margin: 0;
  padding: 0;
  border: 0;
  :after {
    content: "";
    display: block;
    clear: both;
  }
  margin-top: 0px;
`;

const Fieldset = ({ hintId, children }) => (
  <StyledDiv>
    <StyledFieldset aria-describedby={hintId}>
      {children !== undefined ? (
        children
      ) : (
        <React.Fragment>Legend and other fieldset contents...</React.Fragment>
      )}
    </StyledFieldset>
  </StyledDiv>
);

export default Fieldset;

// packages/govtnz-ds/build_src/vue-js/Fieldset.vue
<template>
  <div class="g-fieldset-form-group">
    <fieldset v-bind:aria-describedby="hintId" class="g-fieldset">
      <slot></slot>
    </fieldset>
  </div> </template
><script>
import Vue from "vue";

export default Vue.extend({
  props: {
    hintId: { type: String, required: false },
    children: {
      required: false,
      default: "Legend and other fieldset contents..."
    }
  },
  computed: {}
});</script
><style scoped>
.g-fieldset-form-group {
  margin-bottom: 20px;
}
@media (min-width: 40.0625em) {
  .g-fieldset-form-group {
    margin-bottom: 30px;
  }
}
.g-fieldset-form-group .g-fieldset-form-group:last-of-type {
  margin-bottom: 0;
}
.g-fieldset-form-group--error .g-fieldset-form-group {
  padding: 0;
  border: 0;
}
.g-fieldset {
  margin: 0;
  padding: 0;
  border: 0;
}
.g-fieldset:after {
  content: "";
  display: block;
  clear: both;
}
.g-fieldset-character-count .g-fieldset-form-group {
  margin-bottom: 5px;
}
.g-fieldset-hint > * {
  margin-top: 0px;
}
</style>
