// packages/govtnz-ds/build_src/react-ts-styled-components/H5.js
"use strict";
var __importStar = (this && this.__importStar) || function (mod) {
    if (mod && mod.__esModule) return mod;
    var result = {};
    if (mod != null) for (var k in mod) if (Object.hasOwnProperty.call(mod, k)) result[k] = mod[k];
    result["default"] = mod;
    return result;
};
Object.defineProperty(exports, "__esModule", { value: true });
const React = __importStar(require("react"));
const styled = __importStar(require("styled-components"));
const StyledH5 = styled.h5 `
  ${props => props.styleSize === "xlarge" &&
    styled.css `
      color: #2a2a2a;
      font-family: Arial, sans-serif;
      -webkit-font-smoothing: antialiased;
      -moz-osx-font-smoothing: grayscale;
      font-weight: 500;
      font-size: 3rem;
      line-height: 1.125;
      display: block;
      margin-top: 0;
      margin-bottom: 1rem;
    `}
  @media print {
    ${props => props.styleSize === "xlarge" &&
    styled.css `
        color: #000000;
      `};
  }
  @media print {
    ${props => props.styleSize === "xlarge" &&
    styled.css `
        font-family: sans-serif;
      `};
  }
  @media (min-width: 40.0625em) {
    ${props => props.styleSize === "xlarge" &&
    styled.css `
        font-size: 3.5rem;
        line-height: 1.15;
      `};
  }
  @media print {
    ${props => props.styleSize === "xlarge" &&
    styled.css `
        font-size: 32pt;
        line-height: 1.15;
      `};
  }
  @media (min-width: 40.0625em) {
    ${props => props.styleSize === "xlarge" &&
    styled.css `
        margin-bottom: 1rem;
      `};
  }
  ${props => props.styleSize === "large" &&
    styled.css `
      color: #2a2a2a;
      font-family: Arial, sans-serif;
      -webkit-font-smoothing: antialiased;
      -moz-osx-font-smoothing: grayscale;
      font-weight: 500;
      font-size: 2rem;
      line-height: 1.2;
      display: block;
      margin-top: 3.5rem;
      margin-bottom: 0.5rem;
    `}
  @media print {
    ${props => props.styleSize === "large" &&
    styled.css `
        color: #000000;
      `};
  }
  @media print {
    ${props => props.styleSize === "large" &&
    styled.css `
        font-family: sans-serif;
      `};
  }
  @media (min-width: 40.0625em) {
    ${props => props.styleSize === "large" &&
    styled.css `
        font-size: 2.5rem;
        line-height: 1.25;
      `};
  }
  @media print {
    ${props => props.styleSize === "large" &&
    styled.css `
        font-size: 24pt;
        line-height: 1.05;
      `};
  }
  @media (min-width: 40.0625em) {
    ${props => props.styleSize === "large" &&
    styled.css `
        margin-bottom: 30px;
      `};
  }
  ${props => props.styleSize === "medium" &&
    styled.css `
      color: #0b0c0c;
      font-family: Arial, sans-serif;
      -webkit-font-smoothing: antialiased;
      -moz-osx-font-smoothing: grayscale;
      font-weight: 500;
      font-size: 1.5rem;
      line-height: 1.25;
      display: block;
      margin-top: 2.5rem;
      margin-bottom: 0.5rem;
    `}
  @media print {
    ${props => props.styleSize === "medium" &&
    styled.css `
        color: #000000;
      `};
  }
  @media print {
    ${props => props.styleSize === "medium" &&
    styled.css `
        font-family: sans-serif;
      `};
  }
  @media (min-width: 40.0625em) {
    ${props => props.styleSize === "medium" &&
    styled.css `
        font-size: 1.5rem;
        line-height: 1.25;
      `};
  }
  @media print {
    ${props => props.styleSize === "medium" &&
    styled.css `
        font-size: 18pt;
        line-height: 1.15;
      `};
  }
  @media (min-width: 40.0625em) {
    ${props => props.styleSize === "medium" &&
    styled.css `
        margin-bottom: 0.5rem;
      `};
  }
  ${props => props.styleSize === "small" &&
    styled.css `
      color: #2a2a2a;
      font-family: Arial, sans-serif;
      -webkit-font-smoothing: antialiased;
      -moz-osx-font-smoothing: grayscale;
      font-weight: 500;
      font-size: 1.25rem;
      line-height: 1.25;
      display: block;
      margin-top: 2.5rem;
      margin-bottom: 0.5rem;
    `}
  @media print {
    ${props => props.styleSize === "small" &&
    styled.css `
        color: #000000;
      `};
  }
  @media print {
    ${props => props.styleSize === "small" &&
    styled.css `
        font-family: sans-serif;
      `};
  }
  @media (min-width: 40.0625em) {
    ${props => props.styleSize === "small" &&
    styled.css `
        font-size: 1.1875rem;
        line-height: 1.31579;
      `};
  }
  @media print {
    ${props => props.styleSize === "small" &&
    styled.css `
        font-size: 14pt;
        line-height: 1.15;
      `};
  }
  @media (min-width: 40.0625em) {
    ${props => props.styleSize === "small" &&
    styled.css `
        margin-bottom: 0.5rem;
      `};
  }
  padding-top: 5px;
  @media (min-width: 40.0625em) {
    padding-top: 10px;
  }
  padding-top: 15px;
  @media (min-width: 40.0625em) {
    padding-top: 20px;
  }
  padding-top: 5px;
  @media (min-width: 40.0625em) {
    padding-top: 10px;
  }
  ${props => props.styleSize === "xsmall" &&
    styled.css `
      color: #2a2a2a;
      font-family: Arial, sans-serif;
      -webkit-font-smoothing: antialiased;
      -moz-osx-font-smoothing: grayscale;
      font-weight: 500;
      font-size: 1.125rem;
      line-height: 1.25;
      display: block;
      margin-top: 2.5rem;
      margin-bottom: 0.5rem;
    `}
  @media print {
    ${props => props.styleSize === "xsmall" &&
    styled.css `
        color: #000000;
      `};
  }
  @media print {
    ${props => props.styleSize === "xsmall" &&
    styled.css `
        font-family: sans-serif;
      `};
  }
  @media (min-width: 40.0625em) {
    ${props => props.styleSize === "xsmall" &&
    styled.css `
        font-size: 0.9375rem;
        line-height: 1.31579;
      `};
  }
  @media print {
    ${props => props.styleSize === "xsmall" &&
    styled.css `
        font-size: 13pt;
        line-height: 1.15;
      `};
  }
  @media (min-width: 40.0625em) {
    ${props => props.styleSize === "xsmall" &&
    styled.css `
        margin-bottom: 0.5rem;
      `};
  }
  padding-top: 5px;
  @media (min-width: 40.0625em) {
    padding-top: 10px;
  }
  ${props => props.styleSize === "xxsmall" &&
    styled.css `
      color: #2a2a2a;
      font-family: Arial, sans-serif;
      -webkit-font-smoothing: antialiased;
      -moz-osx-font-smoothing: grayscale;
      font-weight: 500;
      font-size: 1rem;
      line-height: 1.25;
      display: block;
      margin-top: 2.5rem;
      margin-bottom: 15px;
    `}
  @media print {
    ${props => props.styleSize === "xxsmall" &&
    styled.css `
        color: #000000;
      `};
  }
  @media print {
    ${props => props.styleSize === "xxsmall" &&
    styled.css `
        font-family: sans-serif;
      `};
  }
  @media (min-width: 40.0625em) {
    ${props => props.styleSize === "xxsmall" &&
    styled.css `
        font-size: 0.875rem;
        line-height: 1.31579;
      `};
  }
  @media print {
    ${props => props.styleSize === "xxsmall" &&
    styled.css `
        font-size: 12pt;
        line-height: 1.15;
      `};
  }
  @media (min-width: 40.0625em) {
    ${props => props.styleSize === "xxsmall" &&
    styled.css `
        margin-bottom: 20px;
      `};
  }
  padding-top: 5px;
  @media (min-width: 40.0625em) {
    padding-top: 10px;
  }
  ${props => props.marginBottom8 &&
    styled.css `
      margin-bottom: 8px;
    `}
`;
const H5 = ({ styleSize, marginBottom8, id, children }) => (React.createElement(StyledH5, { styleSize: styleSize, marginBottom8: marginBottom8, id: id }, children !== undefined ? (children) : (React.createElement(React.Fragment, null, "Example text"))));
H5.props = ["styleSize", "marginBottom8", "id", "children"];
exports.default = H5;
//# sourceMappingURL=H5.js.map

// packages/govtnz-ds/build_src/vue-js/H5.vue
<template>
  <h5 v-bind:class="computed__class" v-bind:id="id">
    <slot></slot>
  </h5>
</template>
<script>
import Vue from "vue";

const constants = {
  styleSize: {
    xlarge: "g-h5-heading-xl",
    large: "g-h5-heading-l",
    medium: "g-h5-heading-m",
    small: "g-h5-heading-s",
    xsmall: "g-h5-heading-xs",
    xxsmall: "g-h5-heading-xxs"
  }
};

export default Vue.extend({
  props: {
    styleSize: {
      type: String,
      validator: value => {
        return (
          ["xlarge", "large", "medium", "small", "xsmall", "xxsmall"].indexOf(
            value
          ) !== -1
        );
      },
      required: true
    },
    marginBottom8: { type: Boolean, default: false, required: false },
    marginBottom0: { type: Boolean, default: false, required: false },
    id: { type: String, required: false },
    children: { required: false, default: "Example text" }
  },
  computed: {
    computed__class() {
      return (
        (constants.styleSize[this.styleSize] !== undefined
          ? ` ${constants.styleSize[this.styleSize]}`
          : "") +
        (this.marginBottom8 ? " g-h5-heading-mb-8" : "") +
        (this.marginBottom0 ? " g-h5-heading-mb-0" : "")
      );
    }
  }
});
</script>
<style scoped>
.g-h5-heading-xl {
  color: #2a2a2a;
  font-family: Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  font-weight: g-heading-font-weight;
  font-size: 3rem;
  line-height: 1.125;
  display: block;
  margin-top: 0;
  margin-bottom: 1rem;
}
@media print {
  .g-h5-heading-xl {
    color: #000000;
  }
}
@media print {
  .g-h5-heading-xl {
    font-family: sans-serif;
  }
}
@media (min-width: 40.0625em) {
  .g-h5-heading-xl {
    font-size: 3.5rem;
    line-height: 1.15;
  }
}
@media print {
  .g-h5-heading-xl {
    font-size: 32pt;
    line-height: 1.15;
  }
}
@media (min-width: 40.0625em) {
  .g-h5-heading-xl {
    margin-bottom: 1rem;
  }
}
.g-h5-heading-l {
  color: #2a2a2a;
  font-family: Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  font-weight: g-heading-font-weight;
  font-size: 2rem;
  line-height: 1.2;
  display: block;
  margin-top: 3.5rem;
  margin-bottom: 0.5rem;
}
@media print {
  .g-h5-heading-l {
    color: #000000;
  }
}
@media print {
  .g-h5-heading-l {
    font-family: sans-serif;
  }
}
@media (min-width: 40.0625em) {
  .g-h5-heading-l {
    font-size: 2.5rem;
    line-height: 1.25;
  }
}
@media print {
  .g-h5-heading-l {
    font-size: 24pt;
    line-height: 1.05;
  }
}
@media (min-width: 40.0625em) {
  .g-h5-heading-l {
    margin-bottom: 30px;
  }
}
.g-h5-heading-m {
  color: #0b0c0c;
  font-family: Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  font-weight: g-heading-font-weight;
  font-size: 1.5rem;
  line-height: 1.25;
  display: block;
  margin-top: 2.5rem;
  margin-bottom: 0.5rem;
}
@media print {
  .g-h5-heading-m {
    color: #000000;
  }
}
@media print {
  .g-h5-heading-m {
    font-family: sans-serif;
  }
}
@media (min-width: 40.0625em) {
  .g-h5-heading-m {
    font-size: 1.5rem;
    line-height: 1.25;
  }
}
@media print {
  .g-h5-heading-m {
    font-size: 18pt;
    line-height: 1.15;
  }
}
@media (min-width: 40.0625em) {
  .g-h5-heading-m {
    margin-bottom: 0.5rem;
  }
}
.g-h5-heading-s {
  color: #2a2a2a;
  font-family: Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  font-weight: g-heading-font-weight;
  font-size: 1.25rem;
  line-height: 1.25;
  display: block;
  margin-top: 2.5rem;
  margin-bottom: 0.5rem;
}
@media print {
  .g-h5-heading-s {
    color: #000000;
  }
}
@media print {
  .g-h5-heading-s {
    font-family: sans-serif;
  }
}
@media (min-width: 40.0625em) {
  .g-h5-heading-s {
    font-size: 1.1875rem;
    line-height: 1.31579;
  }
}
@media print {
  .g-h5-heading-s {
    font-size: 14pt;
    line-height: 1.15;
  }
}
@media (min-width: 40.0625em) {
  .g-h5-heading-s {
    margin-bottom: 0.5rem;
  }
}
.g-h5-body-l + .g-h5-heading-l,
.g-h5-body-lead + .g-h5-heading-l {
  padding-top: 5px;
}
@media (min-width: 40.0625em) {
  .g-h5-body-l + .g-h5-heading-l,
  .g-h5-body-lead + .g-h5-heading-l {
    padding-top: 10px;
  }
}
.g-h5-body-m + .g-h5-heading-l,
.g-h5-body + .g-h5-heading-l,
.g-h5-body-s + .g-h5-heading-l,
.g-h5-list + .g-h5-heading-l {
  padding-top: 15px;
}
@media (min-width: 40.0625em) {
  .g-h5-body-m + .g-h5-heading-l,
  .g-h5-body + .g-h5-heading-l,
  .g-h5-body-s + .g-h5-heading-l,
  .g-h5-list + .g-h5-heading-l {
    padding-top: 20px;
  }
}
.g-h5-body-m + .g-h5-heading-m,
.g-h5-body + .g-h5-heading-m,
.g-h5-body-s + .g-h5-heading-m,
.g-h5-list + .g-h5-heading-m,
.g-h5-body-m + .g-h5-heading-s,
.g-h5-body + .g-h5-heading-s,
.g-h5-body-s + .g-h5-heading-s,
.g-h5-list + .g-h5-heading-s {
  padding-top: 5px;
}
@media (min-width: 40.0625em) {
  .g-h5-body-m + .g-h5-heading-m,
  .g-h5-body + .g-h5-heading-m,
  .g-h5-body-s + .g-h5-heading-m,
  .g-h5-list + .g-h5-heading-m,
  .g-h5-body-m + .g-h5-heading-s,
  .g-h5-body + .g-h5-heading-s,
  .g-h5-body-s + .g-h5-heading-s,
  .g-h5-list + .g-h5-heading-s {
    padding-top: 10px;
  }
}
.g-h5-heading-xs {
  color: #2a2a2a;
  font-family: Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  font-weight: g-heading-font-weight;
  font-size: 1.125rem;
  line-height: 1.25;
  display: block;
  margin-top: 2.5rem;
  margin-bottom: 0.5rem;
}
@media print {
  .g-h5-heading-xs {
    color: #000000;
  }
}
@media print {
  .g-h5-heading-xs {
    font-family: sans-serif;
  }
}
@media (min-width: 40.0625em) {
  .g-h5-heading-xs {
    font-size: 0.9375rem;
    line-height: 1.31579;
  }
}
@media print {
  .g-h5-heading-xs {
    font-size: 13pt;
    line-height: 1.15;
  }
}
@media (min-width: 40.0625em) {
  .g-h5-heading-xs {
    margin-bottom: 0.5rem;
  }
}
.g-h5-body-m + .g-h5-heading-xs,
.g-h5-body + .g-h5-heading-xs,
.g-h5-body-s + .g-h5-heading-xs,
.g-h5-list + .g-h5-heading-xs {
  padding-top: 5px;
}
@media (min-width: 40.0625em) {
  .g-h5-body-m + .g-h5-heading-xs,
  .g-h5-body + .g-h5-heading-xs,
  .g-h5-body-s + .g-h5-heading-xs,
  .g-h5-list + .g-h5-heading-xs {
    padding-top: 10px;
  }
}
.g-h5-heading-xxs {
  color: #2a2a2a;
  font-family: Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  font-weight: g-heading-font-weight;
  font-size: 1rem;
  line-height: 1.25;
  display: block;
  margin-top: 2.5rem;
  margin-bottom: 15px;
}
@media print {
  .g-h5-heading-xxs {
    color: #000000;
  }
}
@media print {
  .g-h5-heading-xxs {
    font-family: sans-serif;
  }
}
@media (min-width: 40.0625em) {
  .g-h5-heading-xxs {
    font-size: 0.875rem;
    line-height: 1.31579;
  }
}
@media print {
  .g-h5-heading-xxs {
    font-size: 12pt;
    line-height: 1.15;
  }
}
@media (min-width: 40.0625em) {
  .g-h5-heading-xxs {
    margin-bottom: 20px;
  }
}
.g-h5-body-m + .g-h5-heading-xxs,
.g-h5-body + .g-h5-heading-xxs,
.g-h5-body-s + .g-h5-heading-xxs,
.g-h5-list + .g-h5-heading-xxs {
  padding-top: 5px;
}
@media (min-width: 40.0625em) {
  .g-h5-body-m + .g-h5-heading-xxs,
  .g-h5-body + .g-h5-heading-xxs,
  .g-h5-body-s + .g-h5-heading-xxs,
  .g-h5-list + .g-h5-heading-xxs {
    padding-top: 10px;
  }
}
.g-h5-heading-mb-8 {
  margin-bottom: 8px;
}
.g-h5-heading-mb-0 {
  margin-bottom: 0px;
}
.g-h5-hint > * {
  margin-top: 0px;
}
</style>
