// packages/govtnz-ds/build_src/react-ts-styled-components/Header.tsx
import React from "react";
import styled from "styled-components";

type Props = {
  children?: React.ReactNode;
};

const StyledHeader = styled.header`
  position: relative;
  background-color: g-theme-inverted-background-color;
  color: g-theme-inverted-color;
  fill: g-theme-inverted-color;
`;

const Header = ({ children }: Props) => (
  <StyledHeader role="banner">
    {children !== undefined ? (
      children
    ) : (
      <React.Fragment> Example header content </React.Fragment>
    )}
  </StyledHeader>
);

export default Header;

// packages/govtnz-ds/build_src/vue-js/Header.vue
<template>
  <header class="g-header" role="banner">
    <slot></slot>
  </header>
</template>
<script>
import Vue from "vue";

export default Vue.extend({
  props: { children: { required: false, default: " Example header content " } },
  computed: {}
});
</script>
<style scoped>
.g-header {
  position: relative;
  background-color: g-theme-inverted-background-color;
  color: g-theme-inverted-color;
  fill: g-theme-inverted-color;
}
</style>
