// packages/govtnz-ds/build_src/react-ts-styled-components/Li.tsx
import React from "react";
import styled from "styled-components";

type Props = {
  children?: React.ReactNode;
};

const StyledLi = styled.li`
  margin-bottom: 0.25rem;
  margin-bottom: 0;
  @media (min-width: 40.0625em) {
    margin-bottom: 5px;
  }
  margin-top: 0px;
`;

const Li = ({ children }: Props) => (
  <StyledLi>
    {children !== undefined ? (
      children
    ) : (
      <React.Fragment>Example text</React.Fragment>
    )}
  </StyledLi>
);

export default Li;

// packages/govtnz-ds/build_src/vue-js/Li.vue
<template>
  <li>
    <slot></slot>
  </li>
</template>
<script>
import Vue from "vue";

export default Vue.extend({
  props: { children: { required: false, default: "Example text" } },
  computed: {}
});
</script>
<style scoped>
.g-li-list > li {
  margin-bottom: 0.25rem;
}
.g-li-list--bullet > li,
.g-li-list--number > li {
  margin-bottom: 0;
}
@media (min-width: 40.0625em) {
  .g-li-list--bullet > li,
  .g-li-list--number > li {
    margin-bottom: 5px;
  }
}
.g-li-hint > * {
  margin-top: 0px;
}
</style>
