// packages/govtnz-ds/build_src/react-ts-styled-components/Radio.js
"use strict";
var __importStar = (this && this.__importStar) || function (mod) {
    if (mod && mod.__esModule) return mod;
    var result = {};
    if (mod != null) for (var k in mod) if (Object.hasOwnProperty.call(mod, k)) result[k] = mod[k];
    result["default"] = mod;
    return result;
};
Object.defineProperty(exports, "__esModule", { value: true });
const React = __importStar(require("react"));
const styled = __importStar(require("styled-components"));
const StyledInput = styled.input `
  position: absolute;
  z-index: 1;
  top: 0;
  left: 0;
  width: 40px;
  height: 40px;
  cursor: pointer;
  margin: 0;
  opacity: 0;
  :disabled {
    cursor: default;
  }
`;
const Radio = ({ fakeFocus, gov1, hintId, name, disabled, readOnly, autoFocus, value, checked, onChange }) => (React.createElement(StyledInput, { fakeFocus: fakeFocus, "aria-describedby": hintId, id: gov1, name: name, type: "radio", disabled: disabled, readOnly: readOnly, autoFocus: autoFocus, value: value, checked: checked, onChange: onChange }));
Radio.props = [
    "fakeFocus",
    "gov1",
    "hintId",
    "name",
    "disabled",
    "readOnly",
    "autoFocus",
    "value",
    "checked",
    "onChange"
];
exports.default = Radio;
//# sourceMappingURL=Radio.js.map

// packages/govtnz-ds/build_src/vue-js/Radio.vue
<template>
  <input
    v-bind:aria-describedby="hintId"
    v-bind:class="computed__class"
    v-bind:id="gov1"
    v-bind:name="name"
    type="radio"
    v-bind:disabled="disabled"
    v-bind:readonly="readOnly"
    v-bind:autofocus="autoFocus"
    v-bind:value="value"
    v-bind:checked="checked"
  />
</template>
<script>
import Vue from "vue";

export default Vue.extend({
  props: {
    fakeFocus: { type: Boolean, default: false, required: false },
    gov1: { type: String, required: false },
    hintId: { type: String, required: false },
    name: { type: String, required: true },
    disabled: { type: Boolean, default: false, required: false },
    readOnly: { type: Boolean, default: false, required: false },
    autoFocus: { type: Boolean, default: false, required: false },
    value: { type: String, required: false },
    checked: { type: Boolean, default: false, required: false }
  },
  computed: {
    computed__class() {
      return "g-radios__input" + (this.fakeFocus ? " :focus" : "");
    }
  }
});
</script>
<style scoped>
.g-radios__input {
  position: absolute;
  z-index: 1;
  top: 0;
  left: 0;
  width: 40px;
  height: 40px;
  cursor: pointer;
  margin: 0;
  opacity: 0;
}
.g-radios__input:disabled {
  cursor: default;
}
.g-radio-hint > * {
  margin-top: 0px;
}
</style>
