// packages/govtnz-ds/build_src/react-js/Ul.js
import React from 'react';

const Ul = ({ bulleted, spacing, children }) => (
  <ul
    className={`g-list${bulleted ? " g-list--bullet" : ""}${
      spacing ? " g-list--spacing" : ""
    }`}
  >
    {children !== undefined ? (
      children
    ) : (
      <React.Fragment>Example text</React.Fragment>
    )}
  </ul>
);

export default Ul;

// packages/govtnz-ds/build_src/vue-js/Ul.vue
<template>
  <ul v-bind:class="computed__class">
    <slot></slot>
  </ul>
</template>
<script>
import Vue from "vue";

export default Vue.extend({
  props: {
    bulleted: { type: Boolean, default: false, required: false },
    children: { required: false, default: "Example text" }
  },
  computed: {
    computed__class() {
      return "g-list" + (this.bulleted ? " g-list--bullet" : "");
    }
  }
});
</script>
<style scoped>
.g-ul-hint > * {
  margin-top: 0px;
}
</style>
