// packages/govtnz-ds/build_src/angular/H1.ts
import { Component, Input } from "@angular/core";
@Component({
  selector: "g-H1",
  template: `
<h1 class="g-heading{{constants.styleSize[styleSize] !== undefined ? " " +  constants.styleSize[styleSize] : ""}}{{marginBottom8 ? " g-heading-mb-8" : ""}}{{marginBottom0 ? " g-heading-mb-0" : ""}}" id="{{id}}">
   <slot></slot> 

</h1>

 `
})
export class AppComponent {
  @Input() styleSize:
    | "xlarge"
    | "large"
    | "medium"
    | "small"
    | "xsmall"
    | "xxsmall";
  @Input() marginBottom8: boolean | undefined;
  @Input() marginBottom0: boolean | undefined;
  @Input() id: string | undefined;
  @Input() children: React.ReactNode;
  title = "H1";
}

// packages/govtnz-ds/build_src/react-ts/H1.js
"use strict";
var __importStar = (this && this.__importStar) || function (mod) {
    if (mod && mod.__esModule) return mod;
    var result = {};
    if (mod != null) for (var k in mod) if (Object.hasOwnProperty.call(mod, k)) result[k] = mod[k];
    result["default"] = mod;
    return result;
};
Object.defineProperty(exports, "__esModule", { value: true });
const React = __importStar(require("react"));
const constants = {
    styleSize: {
        xlarge: "g-heading-xl",
        large: "g-heading-l",
        medium: "g-heading-m",
        small: "g-heading-s",
        xsmall: "g-heading-xs",
        xxsmall: "g-heading-xxs"
    }
};
const H1 = ({ styleSize, marginBottom8, id, children }) => (React.createElement("h1", { className: `${constants.styleSize[styleSize] !== undefined
        ? constants.styleSize[styleSize]
        : ""}${marginBottom8 ? " g-heading-mb-8" : ""}`, id: id }, children !== undefined ? (children) : (React.createElement(React.Fragment, null, "Example text"))));
H1.props = ["styleSize", "marginBottom8", "id", "children"];
exports.default = H1;
//# sourceMappingURL=H1.js.map
