// packages/govtnz-ds/build_src/angular/Select.ts
import { Component, Input } from "@angular/core";
@Component({
  selector: "g-Select",
  template: `
    <select
      class="g-select"
      id="{{ selectId }}"
      name="{{ name }}"
      multiple="{{ multiple }}"
    >
      <slot></slot>
    </select>
  `
})
export class AppComponent {
  @Input() selectId: string | undefined;
  @Input() name: string;
  @Input() multiple: boolean | undefined;
  @Input() children: React.ReactNode;
  title = "Select";
}

// packages/govtnz-ds/build_src/react-ts/Select.tsx
import * as React from "react";

type Props = {
  selectId?: string | undefined;
  name: string;
  multiple?: boolean | undefined;
  onChange: any;
  children?: React.ReactNode;
};

const Select = ({ selectId, name, multiple, onChange, children }: Props) => (
  <select
    className="g-select"
    id={selectId}
    name={name}
    multiple={multiple}
    onChange={onChange}
  >
    {children !== undefined ? (
      children
    ) : (
      <React.Fragment>
        <option>Options</option>
      </React.Fragment>
    )}
  </select>
);

export default Select;
