// packages/govtnz-ds/build_src/angular/SkipLink.ts
import { Component, Input } from "@angular/core";
@Component({
  selector: "g-SkipLink",
  template: `
    <a
      class="g-skip-link"
      href="{{ href }}"
      rel="{{ rel }}"
      target="{{ target }}"
    >
      Skip to main content
    </a>
  `
})
export class AppComponent {
  @Input() href: string;
  @Input() rel: string | undefined;
  @Input() target: any | undefined;
  title = "SkipLink";
}

// packages/govtnz-ds/build_src/react-ts/SkipLink.tsx
import React from "react";

type Props = {
  href: string;
  rel?: string;
  target?: React.AnchorHTMLAttributes<HTMLAnchorElement>["target"];
  onClick?: React.AnchorHTMLAttributes<HTMLAnchorElement>["onClick"];
};

const SkipLink = ({ href, rel, target, onClick }: Props) => (
  <a
    className="g-skip-link"
    href={href}
    rel={rel}
    target={target}
    onClick={onClick}
  >
    Skip to main content
  </a>
);

export default SkipLink;
