// packages/govtnz-ds/build_src/angular/TextareaBlock.ts
import { Component, Input } from "@angular/core";
@Component({
  selector: "g-TextareaBlock",
  template: `
<div class="g-textareaBlock-form-group{{errorId ? " g-textareaBlock-form-group--error" : ""}}">

  
<label class="g-textareaBlock-label" for="{{id}}">

    <slot name="label"></slot>
  

</label>


  
    
<div class="g-textareaBlock-hint" id="{{hintId}}">

      <slot name="hint"></slot>
    

</div>


  
  
    
<div class="g-textareaBlock-error-message" id="{{errorId}}">

      
<span class="g-textareaBlock-visually-hidden">

        Error:
      

</span>


      <slot name="error"></slot>
    

</div>


  
  
<textarea aria-describedby="{{hintId ?  hintId : ""}}{{errorId ? " " +  errorId : ""}}" class="g-textareaBlock-textarea" id="{{id}}" name="{{name}}" rows="{{rows}}" required="{{required}}" disabled="{{disabled}}" readonly="{{readOnly}}" cols="{{cols}}" autofocus="{{autoFocus}}" spellcheck="{{spellCheck}}" autocomplete="{{autoComplete}}" maxlength="{{maxLength}}" value="{{value}}"/>



</div>


`
})
export class AppComponent {
  @Input() errorId: string | undefined;
  @Input() id: string | undefined;
  @Input() label: React.ReactNode;
  @Input() hintId: string | undefined;
  @Input() hint: React.ReactNode;
  @Input() error: React.ReactNode;
  @Input() name: string;
  @Input() required: boolean | undefined;
  @Input() disabled: boolean | undefined;
  @Input() readOnly: boolean | undefined;
  @Input() rows: number | undefined;
  @Input() cols: number | undefined;
  @Input() autoFocus: boolean | undefined;
  @Input() spellCheck: boolean | undefined;
  @Input() autoComplete: any;
  @Input() maxLength: number | undefined;
  @Input() value: string | undefined;
  title = "TextareaBlock";
}

// packages/govtnz-ds/build_src/react-ts/TextareaBlock.tsx
import React from "react";

type Props = {
  errorId?: string;
  id?: string;
  label?: React.ReactNode;
  hintId?: string;
  hint?: React.ReactNode;
  error?: React.ReactNode;
  name: string;
  required?: boolean;
  disabled?: boolean;
  readOnly?: boolean;
  rows?: number;
  cols?: number;
  autoFocus?: boolean;
  spellCheck?: boolean;
  autoComplete: React.InputHTMLAttributes<HTMLInputElement>["autoComplete"];
  maxLength?: number;
  value?: string;
  onChange?: React.TextareaHTMLAttributes<HTMLTextAreaElement>["onChange"];
  ref?: React.RefObject<HTMLTextAreaElement>;
};

const TextareaBlock = ({
  errorId,
  id,
  label,
  hintId,
  hint,
  error,
  name,
  required,
  disabled,
  readOnly,
  rows,
  cols,
  autoFocus,
  spellCheck,
  autoComplete,
  maxLength,
  value,
  onChange,
  ref
}: Props) => (
  <div
    className={`g-textareaBlock-form-group${
      errorId ? " g-textareaBlock-form-group--error" : ""
    }`}
  >
    <label className="g-textareaBlock-label" htmlFor={id}>
      {label !== undefined ? (
        label
      ) : (
        <React.Fragment>Label text</React.Fragment>
      )}
    </label>
    {hintId !== undefined ? (
      <React.Fragment>
        <div className="g-textareaBlock-hint" id={hintId}>
          {hint !== undefined ? (
            hint
          ) : (
            <React.Fragment>Hint text</React.Fragment>
          )}
        </div>
      </React.Fragment>
    ) : (
      ""
    )}
    {errorId !== undefined ? (
      <React.Fragment>
        <div className="g-textareaBlock-error-message" id={errorId}>
          <span className="g-textareaBlock-visually-hidden">Error:</span>
          {error !== undefined ? (
            error
          ) : (
            <React.Fragment>Error text</React.Fragment>
          )}
        </div>
      </React.Fragment>
    ) : (
      ""
    )}
    <textarea
      aria-describedby={
        hintId !== undefined || errorId !== undefined
          ? `${hintId ? hintId : ""}${errorId ? " " + errorId : ""}`
          : undefined
      }
      className="g-textareaBlock-textarea"
      id={id}
      name={name}
      rows={rows}
      required={required}
      disabled={
        disabled !== undefined ? disabled.toString() === "true" : undefined
      }
      readOnly={readOnly}
      cols={cols}
      autoFocus={autoFocus}
      spellCheck={spellCheck}
      autoComplete={autoComplete}
      maxLength={maxLength}
      value={value}
      onChange={onChange}
      ref={ref}
    />
  </div>
);

export default TextareaBlock;
