// packages/govtnz-ds/build_src/angular/Ul.ts
import { Component, Input } from "@angular/core";
@Component({
  selector: "g-Ul",
  template: `
<ul class="g-list{{bulleted ? " g-list--bullet" : ""}}{{spacing ? " g-list--spacing" : ""}}">

  <slot></slot>


</ul>


`
})
export class AppComponent {
  @Input() bulleted: boolean | undefined;
  @Input() spacing: boolean | undefined;
  @Input() children: React.ReactNode;
  title = "Ul";
}

// packages/govtnz-ds/build_src/react-ts/Ul.tsx
import React from "react";

type Props = {
  bulleted?: boolean;
  spacing?: boolean;
  children?: React.ReactNode;
};

const Ul = ({ bulleted, spacing, children }: Props) => (
  <ul
    className={`g-list${bulleted ? " g-list--bullet" : ""}${
      spacing ? " g-list--spacing" : ""
    }`}
  >
    {children !== undefined ? (
      children
    ) : (
      <React.Fragment>Example text</React.Fragment>
    )}
  </ul>
);

export default Ul;
