// packages/govtnz-ds/build_src/vue-ts/Header.vue
<template>
  <header class="g-header" role="banner">
    <slot></slot>
  </header>
</template>
<script lang="ts">
import Vue from "vue";

export default Vue.extend({
  props: { children: { required: false, default: " Example header content " } },
  computed: {}
});
</script>
<style scoped>
.g-header {
  position: relative;
  background-color: g-theme-inverted-background-color;
  color: g-theme-inverted-color;
  fill: g-theme-inverted-color;
}
</style>

// packages/govtnz-ds/build_src/react-js-styled-components/Header.js
import React from "react";
import styled from "styled-components";

const StyledHeader = styled.header`
  position: relative;
  background-color: g-theme-inverted-background-color;
  color: g-theme-inverted-color;
  fill: g-theme-inverted-color;
`;

const Header = ({ children }) => (
  <StyledHeader role="banner">
    {children !== undefined ? (
      children
    ) : (
      <React.Fragment> Example header content </React.Fragment>
    )}
  </StyledHeader>
);

export default Header;
