// packages/govtnz-ds/build_src/vue-ts/MainNavLink.vue
<template>
  <li class="g-main-nav__link">
    <a
      v-bind:aria-current="ariaCurrent"
      v-bind:class="computed__class"
      v-bind:href="href"
      v-bind:rel="rel"
      v-bind:target="target"
    >
      <slot></slot>
    </a>
  </li>
</template>
<script lang="ts">
import Vue from "vue";

export default Vue.extend({
  props: {
    ariaCurrent: { type: Boolean, default: false, required: false },
    href: { type: String, required: true },
    rel: { type: String, required: false },
    target: { type: String, required: false },
    children: { required: false, default: " Example item text " }
  },
  computed: {
    computed__class() {
      return (
        "g-main-nav__link__a " +
        (this.ariaCurrent ? " g-main-nav__link__a--active" : "")
      );
    }
  }
});
</script>
<style scoped>
.g-main-nav__link {
  display: block;
  margin-right: 0em;
  margin-left: -0.9em;
  font-family: sans-serif;
  font-size: 18px;
  color: g-theme-inverted-color;
  letter-spacing: 0;
  line-height: 20px;
}
.g-main-nav__link__a {
  display: block;
  padding: 1em;
  color: g-theme-inverted-color;
  text-decoration: none;
}
.g-main-nav__link__a:hover {
  text-decoration: underline;
}
.g-main-nav__link__a--active {
  border-left: solid 0.2em g-theme-inverted-nav-active-border-color;
  padding-left: 0.8em;
}
.g-main-nav__link__a:focus {
  outline: 3px solid g-theme-focus-ring-color;
}
@media only screen and (min-width: 48em) {
  .g-main-nav__link {
    display: inline-block;
    margin-right: 1em;
    margin-left: 0px;
    margin-top: 4px;
  }
  .g-main-nav__link:first-child {
    margin-left: 0em;
  }
  .g-main-nav__link:last-child {
    margin-right: 0px;
  }
  .g-main-nav__link__a {
    position: relative;
    display: inline-block;
    padding: 0.6em 1em;
  }
  .g-main-nav__link__a--active {
    border-left: none;
  }
  .g-main-nav__link__a--active::after {
    content: "";
    position: absolute;
    clear: both;
    display: block;
    bottom: 0px;
    left: 1em;
    right: 1em;
    height: 4px;
    background: g-theme-inverted-nav-active-border-color;
  }
}
</style>

// packages/govtnz-ds/build_src/react-js-styled-components/MainNavLink.js
import React from "react";
import styled from "styled-components";

const StyledLi = styled.li`
  display: block;
  margin-right: 0em;
  margin-left: -0.9em;
  font-family: sans-serif;
  font-size: 18px;
  color: g-theme-inverted-color;
  letter-spacing: 0;
  line-height: 20px;
  @media only screen and (min-width: 48em) {
    display: inline-block;
    margin-right: 1em;
    margin-left: 0px;
    margin-top: 4px;
    :first-child {
      margin-left: 0em;
    }
    :last-child {
      margin-right: 0px;
    }
  }
`;

const StyledA = styled.a`
  display: block;
  padding: 1em;
  color: g-theme-inverted-color;
  text-decoration: none;
  :hover {
    text-decoration: underline;
  }
  ${props =>
    props.ariaCurrent &&
    styled.css`
      border-left: solid 0.2em g-theme-inverted-nav-active-border-color;
      padding-left: 0.8em;
    `}
  :focus {
    outline: 3px solid g-theme-focus-ring-color;
  }
  @media only screen and (min-width: 48em) {
    position: relative;
    display: inline-block;
    padding: 0.6em 1em;
    ${props =>
      props.ariaCurrent &&
      styled.css`
        border-left: none;
      `};
    ::after {
      content: "";
      position: absolute;
      clear: both;
      display: block;
      bottom: 0px;
      left: 1em;
      right: 1em;
      height: 4px;
      background: g-theme-inverted-nav-active-border-color;
    }
  }
`;

const MainNavLink = ({ ariaCurrent, href, rel, target, onClick, children }) => (
  <StyledLi>
    <StyledA
      ariaCurrent={ariaCurrent}
      aria-current={ariaCurrent}
      href={href}
      rel={rel}
      target={target}
      onClick={onClick}
    >
      {children !== undefined ? (
        children
      ) : (
        <React.Fragment> Example item text </React.Fragment>
      )}
    </StyledA>
  </StyledLi>
);

export default MainNavLink;
