// packages/govtnz-ds/build_src/vue-js/SkipLink.vue
<template>
  <a
    class="g-skip-link"
    v-bind:href="href"
    v-bind:rel="rel"
    v-bind:target="target"
  >
    Skip to main content
  </a>
</template>
<script>
import Vue from "vue";

export default Vue.extend({
  props: {
    href: { type: String, required: true },
    rel: { type: String, required: false },
    target: { type: String, required: false }
  },
  computed: {}
});
</script>
<style scoped>
.g-skipLink-error-summary__list a {
  font-weight: 700;
}
.g-skipLink-error-summary__list a:focus {
  outline: 3px solid #b53cde;
  outline-offset: 0;
}
.g-skipLink-error-summary__list a:link,
.g-skipLink-error-summary__list a:visited,
.g-skipLink-error-summary__list a:hover,
.g-skipLink-error-summary__list a:active {
  color: #b10e1e;
}
.g-skipLink-error-summary__list a:focus {
  color: #0b0c0c;
}
.g-skipLink-header__navigation-item a {
  font-family: Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  font-weight: 700;
  font-size: 0.875rem;
  line-height: 1.14286;
  white-space: nowrap;
}
@media print {
  .g-skipLink-header__navigation-item a {
    font-family: sans-serif;
  }
}
@media (min-width: 40.0625em) {
  .g-skipLink-header__navigation-item a {
    font-size: 1rem;
    line-height: 1.25;
  }
}
@media print {
  .g-skipLink-header__navigation-item a {
    font-size: 14pt;
    line-height: 1.2;
  }
}
.g-skipLink-header__navigation-item--active a:link,
.g-skipLink-header__navigation-item--active a:hover,
.g-skipLink-header__navigation-item--active a:visited {
  color: #1d8feb;
}
.g-skipLink-header__navigation-item--active a:focus {
  color: #0b0c0c;
}
.g-skip-link {
  position: absolute !important;
  width: 1px !important;
  height: 1px !important;
  margin: 0 !important;
  overflow: hidden !important;
  clip: rect(0 0 0 0) !important;
  -webkit-clip-path: inset(50%) !important;
  clip-path: inset(50%) !important;
  white-space: nowrap !important;
  font-family: Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  font-size: 0.875rem;
  line-height: 1.14286;
  display: block;
  padding: 10px 15px;
}
.g-skip-link:active,
.g-skip-link:focus {
  position: static !important;
  width: auto !important;
  height: auto !important;
  margin: inherit !important;
  overflow: visible !important;
  clip: auto !important;
  -webkit-clip-path: none !important;
  clip-path: none !important;
  white-space: inherit !important;
}
@media print {
  .g-skip-link {
    font-family: sans-serif;
  }
}
.g-skip-link:focus {
  outline: 3px solid #b53cde;
  outline-offset: 0;
  background-color: #b53cde;
}
.g-skip-link:link,
.g-skip-link:visited,
.g-skip-link:hover,
.g-skip-link:active,
.g-skip-link:focus {
  color: #0b0c0c;
}
@media print {
  .g-skip-link:link,
  .g-skip-link:visited,
  .g-skip-link:hover,
  .g-skip-link:active,
  .g-skip-link:focus {
    color: #000000;
  }
}
@media (min-width: 40.0625em) {
  .g-skip-link {
    font-size: 1rem;
    line-height: 1.25;
  }
}
@media print {
  .g-skip-link {
    font-size: 14pt;
    line-height: 1.2;
  }
}
.g-skipLink-hint > * {
  margin-top: 0px;
}
</style>

// packages/govtnz-ds/build_src/react-js-styled-components/SkipLink.js
import React from "react";
import styled from "styled-components";

const StyledA = styled.a`
  font-weight: 700;
  :focus {
    outline: 3px solid #b53cde;
    outline-offset: 0;
  }
  :link,
  :visited,
  :hover,
  :active {
    color: #b10e1e;
  }
  :focus {
    color: #0b0c0c;
  }
  font-family: Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  font-weight: 700;
  font-size: 0.875rem;
  line-height: 1.14286;
  white-space: nowrap;
  @media print {
    font-family: sans-serif;
  }
  @media (min-width: 40.0625em) {
    font-size: 1rem;
    line-height: 1.25;
  }
  @media print {
    font-size: 14pt;
    line-height: 1.2;
  }
  :link,
  :hover,
  :visited {
    color: #1d8feb;
  }
  :focus {
    color: #0b0c0c;
  }
  position: absolute !important;
  width: 1px !important;
  height: 1px !important;
  margin: 0 !important;
  overflow: hidden !important;
  clip: rect(0 0 0 0) !important;
  -webkit-clip-path: inset(50%) !important;
  clip-path: inset(50%) !important;
  white-space: nowrap !important;
  font-family: Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  font-size: 0.875rem;
  line-height: 1.14286;
  display: block;
  padding: 10px 15px;
  :active,
  :focus {
    position: static !important;
    width: auto !important;
    height: auto !important;
    margin: inherit !important;
    overflow: visible !important;
    clip: auto !important;
    -webkit-clip-path: none !important;
    clip-path: none !important;
    white-space: inherit !important;
  }
  @media print {
    font-family: sans-serif;
  }
  :focus {
    outline: 3px solid #b53cde;
    outline-offset: 0;
    background-color: #b53cde;
  }
  :link,
  :visited,
  :hover,
  :active,
  :focus {
    color: #0b0c0c;
  }
  @media print {
    :link,
    :visited,
    :hover,
    :active,
    :focus {
      color: #000000;
    }
  }
  @media (min-width: 40.0625em) {
    font-size: 1rem;
    line-height: 1.25;
  }
  @media print {
    font-size: 14pt;
    line-height: 1.2;
  }
  margin-top: 0px;
`;

const SkipLink = ({ href, rel, target, onClick }) => (
  <StyledA href={href} rel={rel} target={target} onClick={onClick}>
    Skip to main content
  </StyledA>
);

export default SkipLink;
