// packages/govtnz-ds/build_src/vue-js/Subfooter.vue
<template>
  <div class="g-subfooter">
    <slot></slot>
  </div>
</template>
<script>
import Vue from "vue";

export default Vue.extend({
  props: {
    children: { required: false, default: " Example subfooter content " }
  },
  computed: {}
});
</script>
<style scoped>
.g-subfooter {
  background-color: #2a2a2a;
  color: #ffffff;
  fill: #ffffff;
  min-height: 146px;
}
@media only screen and (min-width: 48em) {
  .g-subfooter {
    min-height: 104px;
  }
}
</style>

// packages/govtnz-ds/build_src/react-js-styled-components/Subfooter.js
import React from "react";
import styled from "styled-components";

const StyledDiv = styled.div`
  background-color: #2a2a2a;
  color: #ffffff;
  fill: #ffffff;
  min-height: 146px;
  @media only screen and (min-width: 48em) {
    min-height: 104px;
  }
`;

const Subfooter = ({ children }) => (
  <StyledDiv>
    {children !== undefined ? (
      children
    ) : (
      <React.Fragment> Example subfooter content </React.Fragment>
    )}
  </StyledDiv>
);

export default Subfooter;
