// packages/govtnz-ds/build_src/vue-js/Tabs.vue
<template>
  <div class="g-tabs" data-module="tabs">
    <h2 class="g-tabs__title">
      Contents
    </h2>

    <ul class="g-tabs__list" role="tablist">
      <li class="g-tabs__list-item" role="presentation">
        <a
          v-bind:aria-controls="pastDay"
          aria-selected="true"
          class="g-tabs__tab g-tabs__tab--selected"
          v-bind:href="href"
          v-bind:id="tabPastDay"
          role="tab"
          tabindex="0"
          v-bind:rel="rel"
          v-bind:target="computed__target"
        >
          Past day
        </a>
      </li>

      <li class="g-tabs__list-item" role="presentation">
        <a
          v-bind:aria-controls="pastWeek"
          aria-selected="false"
          class="g-tabs__tab"
          v-bind:href="href2"
          v-bind:id="tabPastWeek"
          role="tab"
          tabindex="-1"
          v-bind:rel="rel2"
          v-bind:target="computed__target2"
        >
          Past week
        </a>
      </li>

      <li class="g-tabs__list-item" role="presentation">
        <a
          v-bind:aria-controls="pastMonth"
          aria-selected="false"
          class="g-tabs__tab"
          v-bind:href="href3"
          v-bind:id="tabPastMonth"
          role="tab"
          tabindex="-1"
          v-bind:rel="rel3"
          v-bind:target="computed__target3"
        >
          Past month
        </a>
      </li>

      <li class="g-tabs__list-item" role="presentation">
        <a
          v-bind:aria-controls="pastYear"
          aria-selected="false"
          class="g-tabs__tab"
          v-bind:href="href4"
          v-bind:id="tabPastYear"
          role="tab"
          tabindex="-1"
          v-bind:rel="rel4"
          v-bind:target="computed__target4"
        >
          Past year
        </a>
      </li>
    </ul>

    <section
      v-bind:aria-labelledby="tabPastDay"
      class="g-tabs__panel"
      v-bind:id="pastDay"
      role="tabpanel"
    >
      <h2 class="g-tabs-heading-l">
        Past day
      </h2>

      <table class="g-tabs-table">
        <thead class="g-tabs-table__head">
          <tr class="g-tabs-table__row">
            Case manager Cases opened Cases closed
          </tr>
        </thead>

        <tbody class="g-tabs-table__body">
          <tr class="g-tabs-table__row">
            David Francis 3 0
          </tr>

          <tr class="g-tabs-table__row">
            Paul Farmer 1 0
          </tr>

          <tr class="g-tabs-table__row">
            Rita Patel 2 0
          </tr>
        </tbody>
      </table>
    </section>

    <section
      v-bind:aria-labelledby="tabPastWeek"
      class="g-tabs__panel g-tabs__panel--hidden"
      v-bind:id="pastWeek"
      role="tabpanel"
    >
      <h2 class="g-tabs-heading-l">
        Past week
      </h2>

      <table class="g-tabs-table">
        <thead class="g-tabs-table__head">
          <tr class="g-tabs-table__row">
            Case manager Cases opened Cases closed
          </tr>
        </thead>

        <tbody class="g-tabs-table__body">
          <tr class="g-tabs-table__row">
            David Francis 24 18
          </tr>

          <tr class="g-tabs-table__row">
            Paul Farmer 16 20
          </tr>

          <tr class="g-tabs-table__row">
            Rita Patel 24 27
          </tr>
        </tbody>
      </table>
    </section>

    <section
      v-bind:aria-labelledby="tabPastMonth"
      class="g-tabs__panel g-tabs__panel--hidden"
      v-bind:id="pastMonth"
      role="tabpanel"
    >
      <h2 class="g-tabs-heading-l">
        Past month
      </h2>

      <table class="g-tabs-table">
        <thead class="g-tabs-table__head">
          <tr class="g-tabs-table__row">
            Case manager Cases opened Cases closed
          </tr>
        </thead>

        <tbody class="g-tabs-table__body">
          <tr class="g-tabs-table__row">
            David Francis 98 95
          </tr>

          <tr class="g-tabs-table__row">
            Paul Farmer 122 131
          </tr>

          <tr class="g-tabs-table__row">
            Rita Patel 126 142
          </tr>
        </tbody>
      </table>
    </section>

    <section
      v-bind:aria-labelledby="tabPastYear"
      class="g-tabs__panel g-tabs__panel--hidden"
      v-bind:id="pastYear"
      role="tabpanel"
    >
      <h2 class="g-tabs-heading-l">
        Past year
      </h2>

      <table class="g-tabs-table">
        <thead class="g-tabs-table__head">
          <tr class="g-tabs-table__row">
            Case manager Cases opened Cases closed
          </tr>
        </thead>

        <tbody class="g-tabs-table__body">
          <tr class="g-tabs-table__row">
            David Francis 1380 1472
          </tr>

          <tr class="g-tabs-table__row">
            Paul Farmer 1129 1083
          </tr>

          <tr class="g-tabs-table__row">
            Rita Patel 1539 1265
          </tr>
        </tbody>
      </table>
    </section>
  </div>
</template>
<script>
import Vue from "vue";

const constants = {
  target: { Blank: "_blank", Top: "_top", Self: "_self", Parent: "_parent" },
  target2: { Blank: "_blank", Top: "_top", Self: "_self", Parent: "_parent" },
  target3: { Blank: "_blank", Top: "_top", Self: "_self", Parent: "_parent" },
  target4: { Blank: "_blank", Top: "_top", Self: "_self", Parent: "_parent" }
};

export default Vue.extend({
  props: {
    tabPastDay: { type: String, required: false },
    pastDay: { type: String, required: false },
    href: { type: String, required: true },
    rel: { type: String, required: false },
    target: {
      type: String,
      validator: value => {
        return ["Blank", "Top", "Self", "Parent"].indexOf(value) !== -1;
      },
      required: false
    },
    tabPastWeek: { type: String, required: false },
    pastWeek: { type: String, required: false },
    href2: { type: String, required: true },
    rel2: { type: String, required: false },
    target2: {
      type: String,
      validator: value => {
        return ["Blank", "Top", "Self", "Parent"].indexOf(value) !== -1;
      },
      required: false
    },
    tabPastMonth: { type: String, required: false },
    pastMonth: { type: String, required: false },
    href3: { type: String, required: true },
    rel3: { type: String, required: false },
    target3: {
      type: String,
      validator: value => {
        return ["Blank", "Top", "Self", "Parent"].indexOf(value) !== -1;
      },
      required: false
    },
    tabPastYear: { type: String, required: false },
    pastYear: { type: String, required: false },
    href4: { type: String, required: true },
    rel4: { type: String, required: false },
    target4: {
      type: String,
      validator: value => {
        return ["Blank", "Top", "Self", "Parent"].indexOf(value) !== -1;
      },
      required: false
    }
  },
  computed: {
    computed__target() {
      return constants.target[this.target] !== undefined
        ? constants.target[this.target]
        : "";
    },
    computed__target2() {
      return constants.target2[this.target2] !== undefined
        ? constants.target2[this.target2]
        : "";
    },
    computed__target3() {
      return constants.target3[this.target3] !== undefined
        ? constants.target3[this.target3]
        : "";
    },
    computed__target4() {
      return constants.target4[this.target4] !== undefined
        ? constants.target4[this.target4]
        : "";
    }
  }
});
</script>
<style scoped>
.g-tabs-list > li {
  margin-bottom: 0.25rem;
}
.g-tabs-list--bullet > li,
.g-tabs-list--number > li {
  margin-bottom: 0;
}
@media (min-width: 40.0625em) {
  .g-tabs-list--bullet > li,
  .g-tabs-list--number > li {
    margin-bottom: 5px;
  }
}
.g-tabs-heading-l {
  color: #2a2a2a;
  font-family: Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  font-weight: g-heading-font-weight;
  font-size: 2rem;
  line-height: 1.2;
  display: block;
  margin-top: 3.5rem;
  margin-bottom: 0.5rem;
}
@media print {
  .g-tabs-heading-l {
    color: #000000;
  }
}
@media print {
  .g-tabs-heading-l {
    font-family: sans-serif;
  }
}
@media (min-width: 40.0625em) {
  .g-tabs-heading-l {
    font-size: 2.5rem;
    line-height: 1.25;
  }
}
@media print {
  .g-tabs-heading-l {
    font-size: 24pt;
    line-height: 1.05;
  }
}
@media (min-width: 40.0625em) {
  .g-tabs-heading-l {
    margin-bottom: 30px;
  }
}
.g-tabs-body-l + .g-tabs-heading-l,
.g-tabs-body-lead + .g-tabs-heading-l {
  padding-top: 5px;
}
@media (min-width: 40.0625em) {
  .g-tabs-body-l + .g-tabs-heading-l,
  .g-tabs-body-lead + .g-tabs-heading-l {
    padding-top: 10px;
  }
}
.g-tabs-body-m + .g-tabs-heading-l,
.g-tabs-body + .g-tabs-heading-l,
.g-tabs-body-s + .g-tabs-heading-l,
.g-tabs-list + .g-tabs-heading-l {
  padding-top: 15px;
}
@media (min-width: 40.0625em) {
  .g-tabs-body-m + .g-tabs-heading-l,
  .g-tabs-body + .g-tabs-heading-l,
  .g-tabs-body-s + .g-tabs-heading-l,
  .g-tabs-list + .g-tabs-heading-l {
    padding-top: 20px;
  }
}
.g-tabs-error-summary__list a {
  font-weight: 700;
}
.g-tabs-error-summary__list a:focus {
  outline: 3px solid #ffbf47;
  outline-offset: 0;
}
.g-tabs-error-summary__list a:link,
.g-tabs-error-summary__list a:visited,
.g-tabs-error-summary__list a:hover,
.g-tabs-error-summary__list a:active {
  color: #b10e1e;
}
.g-tabs-error-summary__list a:focus {
  color: #0b0c0c;
}
.g-tabs-header__navigation-item a {
  font-family: Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  font-weight: 700;
  font-size: 0.875rem;
  line-height: 1.14286;
  white-space: nowrap;
}
@media print {
  .g-tabs-header__navigation-item a {
    font-family: sans-serif;
  }
}
@media (min-width: 40.0625em) {
  .g-tabs-header__navigation-item a {
    font-size: 1rem;
    line-height: 1.25;
  }
}
@media print {
  .g-tabs-header__navigation-item a {
    font-size: 14pt;
    line-height: 1.2;
  }
}
.g-tabs-header__navigation-item--active a:link,
.g-tabs-header__navigation-item--active a:hover,
.g-tabs-header__navigation-item--active a:visited {
  color: #1d8feb;
}
.g-tabs-header__navigation-item--active a:focus {
  color: #0b0c0c;
}
.g-tabs {
  font-family: Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  font-weight: 400;
  font-size: 1rem;
  line-height: 1.25;
  color: #0b0c0c;
  margin-top: 5px;
  margin-bottom: 20px;
}
@media print {
  .g-tabs {
    font-family: sans-serif;
  }
}
@media (min-width: 40.0625em) {
  .g-tabs {
    font-size: 1.1875rem;
    line-height: 1.31579;
  }
}
@media print {
  .g-tabs {
    font-size: 14pt;
    line-height: 1.15;
  }
}
@media print {
  .g-tabs {
    color: #000000;
  }
}
@media (min-width: 40.0625em) {
  .g-tabs {
    margin-top: 5px;
  }
}
@media (min-width: 40.0625em) {
  .g-tabs {
    margin-bottom: 30px;
  }
}
.g-tabs__title {
  font-family: Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  font-weight: 400;
  font-size: 1rem;
  line-height: 1.25;
  margin-bottom: 5px;
}
@media print {
  .g-tabs__title {
    font-family: sans-serif;
  }
}
@media (min-width: 40.0625em) {
  .g-tabs__title {
    font-size: 1.1875rem;
    line-height: 1.31579;
  }
}
@media print {
  .g-tabs__title {
    font-size: 14pt;
    line-height: 1.15;
  }
}
.g-tabs__list {
  margin: 0;
  padding: 0;
  list-style: none;
}
@media (max-width: 40.0525em) {
  .g-tabs__list {
    margin-bottom: 20px;
  }
}
@media (max-width: 40.0525em) and (min-width: 40.0625em) {
  .g-tabs__list {
    margin-bottom: 30px;
  }
}
.g-tabs__list-item {
  margin-left: 25px;
}
.g-tabs__list-item::before {
  content: "— ";
  margin-left: -25px;
  padding-right: 5px;
}
.g-tabs__tab {
  font-family: Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  font-weight: 400;
  font-size: 1rem;
  line-height: 1.25;
  display: inline-block;
  padding-top: 10px;
  padding-bottom: 10px;
}
@media print {
  .g-tabs__tab {
    font-family: sans-serif;
  }
}
.g-tabs__tab:focus {
  outline: 3px solid #ffbf47;
  outline-offset: 0;
  background-color: #ffbf47;
}
.g-tabs__tab:link {
  color: #005ea5;
}
.g-tabs__tab:visited {
  color: #4c2c92;
}
.g-tabs__tab:hover {
  color: #2b8cc4;
}
.g-tabs__tab:active {
  color: #2b8cc4;
}
.g-tabs__tab:focus {
  color: #0b0c0c;
}
@media print {
  .g-tabs__tab {
    font-family: sans-serif;
  }
}
@media (min-width: 40.0625em) {
  .g-tabs__tab {
    font-size: 1.1875rem;
    line-height: 1.31579;
  }
}
@media print {
  .g-tabs__tab {
    font-size: 14pt;
    line-height: 1.15;
  }
}
.g-tabs__panel {
  margin-bottom: 30px;
}
@media (min-width: 40.0625em) {
  .g-tabs__panel {
    margin-bottom: 50px;
  }
}
@media (min-width: 40.0625em) {
  .js-enabled .g-tabs__list {
    border-bottom: 1px solid #bfc1c3;
  }
  .js-enabled .g-tabs__list:after {
    content: "";
    display: block;
    clear: both;
  }
  .js-enabled .g-tabs__list-item {
    margin-left: 0;
  }
  .js-enabled .g-tabs__list-item::before {
    content: none;
  }
  .js-enabled .g-tabs__title {
    display: none;
  }
  .js-enabled .g-tabs__tab {
    margin-right: 5px;
    padding-right: 20px;
    padding-left: 20px;
    float: left;
    color: #0b0c0c;
    background-color: #f8f8f8;
    text-align: center;
    text-decoration: none;
  }
  .js-enabled .g-tabs__tab--selected {
    margin-top: -5px;
    margin-bottom: -1px;
    padding-top: 14px;
    padding-right: 19px;
    padding-bottom: 16px;
    padding-left: 19px;
    border: 1px solid #bfc1c3;
    border-bottom: 0;
    color: #0b0c0c;
    background-color: #ffffff;
  }
  .js-enabled .g-tabs__tab--selected:focus {
    background-color: transparent;
  }
  .js-enabled .g-tabs__panel {
    margin-bottom: 0;
    padding-top: 30px;
    padding-right: 20px;
    padding-bottom: 30px;
    padding-left: 20px;
    border: 1px solid #bfc1c3;
    border-top: 0;
  }
}
@media (min-width: 40.0625em) and (min-width: 40.0625em) {
  .js-enabled .g-tabs__panel {
    margin-bottom: 0;
  }
}
@media (min-width: 40.0625em) {
  .js-enabled .g-tabs__panel--hidden {
    display: none;
  }
}
.g-tabs-table {
  font-family: Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  font-weight: 400;
  font-size: 1rem;
  line-height: 1.25;
  color: #0b0c0c;
  width: 100%;
  margin-bottom: 20px;
  border-spacing: 0;
  border-collapse: collapse;
}
@media print {
  .g-tabs-table {
    font-family: sans-serif;
  }
}
@media (min-width: 40.0625em) {
  .g-tabs-table {
    font-size: 1.1875rem;
    line-height: 1.31579;
  }
}
@media print {
  .g-tabs-table {
    font-size: 14pt;
    line-height: 1.15;
  }
}
@media print {
  .g-tabs-table {
    color: #000000;
  }
}
@media (min-width: 40.0625em) {
  .g-tabs-table {
    margin-bottom: 30px;
  }
}
.g-tabs-hint > * {
  margin-top: 0px;
}
</style>

// packages/govtnz-ds/build_src/react-js-styled-components/Tabs.js
import React from "react";
import styled from "styled-components";

const StyledDiv = styled.div`
  font-family: Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  font-weight: 400;
  font-size: 1rem;
  line-height: 1.25;
  color: #0b0c0c;
  margin-top: 5px;
  margin-bottom: 20px;
  @media print {
    font-family: sans-serif;
  }
  @media (min-width: 40.0625em) {
    font-size: 1.1875rem;
    line-height: 1.31579;
  }
  @media print {
    font-size: 14pt;
    line-height: 1.15;
  }
  @media print {
    color: #000000;
  }
  @media (min-width: 40.0625em) {
    margin-top: 5px;
  }
  @media (min-width: 40.0625em) {
    margin-bottom: 30px;
  }
`;

const StyledH2 = styled.h2`
  font-family: Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  font-weight: 400;
  font-size: 1rem;
  line-height: 1.25;
  margin-bottom: 5px;
  @media print {
    font-family: sans-serif;
  }
  @media (min-width: 40.0625em) {
    font-size: 1.1875rem;
    line-height: 1.31579;
  }
  @media print {
    font-size: 14pt;
    line-height: 1.15;
  }
  @media (min-width: 40.0625em) {
    display: none;
  }
`;

const StyledUl = styled.ul`
  margin: 0;
  padding: 0;
  list-style: none;
  @media (max-width: 40.0525em) {
    margin-bottom: 20px;
  }
  @media (max-width: 40.0525em) and (min-width: 40.0625em) {
    margin-bottom: 30px;
  }
  @media (min-width: 40.0625em) {
    border-bottom: 1px solid #bfc1c3;
    :after {
      content: "";
      display: block;
      clear: both;
    }
  }
`;

const StyledLi = styled.li`
  margin-bottom: 5px;
  margin-bottom: 0;
  @media (min-width: 40.0625em) {
    margin-bottom: 5px;
  }
  margin-left: 25px;
  ::before {
    content: "— ";
    margin-left: -25px;
    padding-right: 5px;
  }
  @media (min-width: 40.0625em) {
    margin-left: 0;
    ::before {
      content: none;
    }
  }
`;

const StyledA = styled.a`
  font-weight: 700;
  :focus {
    outline: 3px solid #ffbf47;
    outline-offset: 0;
  }
  :link,
  :visited,
  :hover,
  :active {
    color: #b10e1e;
  }
  :focus {
    color: #0b0c0c;
  }
  font-family: Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  font-weight: 700;
  font-size: 0.875rem;
  line-height: 1.14286;
  white-space: nowrap;
  @media print {
    font-family: sans-serif;
  }
  @media (min-width: 40.0625em) {
    font-size: 1rem;
    line-height: 1.25;
  }
  @media print {
    font-size: 14pt;
    line-height: 1.2;
  }
  :link,
  :hover,
  :visited {
    color: #1d8feb;
  }
  :focus {
    color: #0b0c0c;
  }
  font-family: Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  font-weight: 400;
  font-size: 1rem;
  line-height: 1.25;
  display: inline-block;
  padding-top: 10px;
  padding-bottom: 10px;
  @media print {
    font-family: sans-serif;
  }
  :focus {
    outline: 3px solid #ffbf47;
    outline-offset: 0;
    background-color: #ffbf47;
  }
  :link {
    color: #005ea5;
  }
  :visited {
    color: #4c2c92;
  }
  :hover {
    color: #2b8cc4;
  }
  :active {
    color: #2b8cc4;
  }
  :focus {
    color: #0b0c0c;
  }
  @media print {
    font-family: sans-serif;
  }
  @media (min-width: 40.0625em) {
    font-size: 1.1875rem;
    line-height: 1.31579;
  }
  @media print {
    font-size: 14pt;
    line-height: 1.15;
  }
  @media (min-width: 40.0625em) {
    margin-right: 5px;
    padding-right: 20px;
    padding-left: 20px;
    float: left;
    color: #0b0c0c;
    background-color: #f8f8f8;
    text-align: center;
    text-decoration: none;
    margin-top: -5px;
    margin-bottom: -1px;
    padding-top: 14px;
    padding-right: 19px;
    padding-bottom: 16px;
    padding-left: 19px;
    border: 1px solid #bfc1c3;
    border-bottom: 0;
    color: #0b0c0c;
    background-color: #ffffff;
    :focus {
      background-color: transparent;
    }
  }
`;

const StyledLi2 = styled.li`
  margin-bottom: 5px;
  margin-bottom: 0;
  @media (min-width: 40.0625em) {
    margin-bottom: 5px;
  }
  margin-left: 25px;
  ::before {
    content: "— ";
    margin-left: -25px;
    padding-right: 5px;
  }
  @media (min-width: 40.0625em) {
    margin-left: 0;
    ::before {
      content: none;
    }
  }
`;

const StyledA2 = styled.a`
  font-weight: 700;
  :focus {
    outline: 3px solid #ffbf47;
    outline-offset: 0;
  }
  :link,
  :visited,
  :hover,
  :active {
    color: #b10e1e;
  }
  :focus {
    color: #0b0c0c;
  }
  font-family: Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  font-weight: 700;
  font-size: 0.875rem;
  line-height: 1.14286;
  white-space: nowrap;
  @media print {
    font-family: sans-serif;
  }
  @media (min-width: 40.0625em) {
    font-size: 1rem;
    line-height: 1.25;
  }
  @media print {
    font-size: 14pt;
    line-height: 1.2;
  }
  :link,
  :hover,
  :visited {
    color: #1d8feb;
  }
  :focus {
    color: #0b0c0c;
  }
  font-family: Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  font-weight: 400;
  font-size: 1rem;
  line-height: 1.25;
  display: inline-block;
  padding-top: 10px;
  padding-bottom: 10px;
  @media print {
    font-family: sans-serif;
  }
  :focus {
    outline: 3px solid #ffbf47;
    outline-offset: 0;
    background-color: #ffbf47;
  }
  :link {
    color: #005ea5;
  }
  :visited {
    color: #4c2c92;
  }
  :hover {
    color: #2b8cc4;
  }
  :active {
    color: #2b8cc4;
  }
  :focus {
    color: #0b0c0c;
  }
  @media print {
    font-family: sans-serif;
  }
  @media (min-width: 40.0625em) {
    font-size: 1.1875rem;
    line-height: 1.31579;
  }
  @media print {
    font-size: 14pt;
    line-height: 1.15;
  }
  @media (min-width: 40.0625em) {
    margin-right: 5px;
    padding-right: 20px;
    padding-left: 20px;
    float: left;
    color: #0b0c0c;
    background-color: #f8f8f8;
    text-align: center;
    text-decoration: none;
  }
`;

const StyledLi3 = styled.li`
  margin-bottom: 5px;
  margin-bottom: 0;
  @media (min-width: 40.0625em) {
    margin-bottom: 5px;
  }
  margin-left: 25px;
  ::before {
    content: "— ";
    margin-left: -25px;
    padding-right: 5px;
  }
  @media (min-width: 40.0625em) {
    margin-left: 0;
    ::before {
      content: none;
    }
  }
`;

const StyledA3 = styled.a`
  font-weight: 700;
  :focus {
    outline: 3px solid #ffbf47;
    outline-offset: 0;
  }
  :link,
  :visited,
  :hover,
  :active {
    color: #b10e1e;
  }
  :focus {
    color: #0b0c0c;
  }
  font-family: Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  font-weight: 700;
  font-size: 0.875rem;
  line-height: 1.14286;
  white-space: nowrap;
  @media print {
    font-family: sans-serif;
  }
  @media (min-width: 40.0625em) {
    font-size: 1rem;
    line-height: 1.25;
  }
  @media print {
    font-size: 14pt;
    line-height: 1.2;
  }
  :link,
  :hover,
  :visited {
    color: #1d8feb;
  }
  :focus {
    color: #0b0c0c;
  }
  font-family: Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  font-weight: 400;
  font-size: 1rem;
  line-height: 1.25;
  display: inline-block;
  padding-top: 10px;
  padding-bottom: 10px;
  @media print {
    font-family: sans-serif;
  }
  :focus {
    outline: 3px solid #ffbf47;
    outline-offset: 0;
    background-color: #ffbf47;
  }
  :link {
    color: #005ea5;
  }
  :visited {
    color: #4c2c92;
  }
  :hover {
    color: #2b8cc4;
  }
  :active {
    color: #2b8cc4;
  }
  :focus {
    color: #0b0c0c;
  }
  @media print {
    font-family: sans-serif;
  }
  @media (min-width: 40.0625em) {
    font-size: 1.1875rem;
    line-height: 1.31579;
  }
  @media print {
    font-size: 14pt;
    line-height: 1.15;
  }
  @media (min-width: 40.0625em) {
    margin-right: 5px;
    padding-right: 20px;
    padding-left: 20px;
    float: left;
    color: #0b0c0c;
    background-color: #f8f8f8;
    text-align: center;
    text-decoration: none;
  }
`;

const StyledLi4 = styled.li`
  margin-bottom: 5px;
  margin-bottom: 0;
  @media (min-width: 40.0625em) {
    margin-bottom: 5px;
  }
  margin-left: 25px;
  ::before {
    content: "— ";
    margin-left: -25px;
    padding-right: 5px;
  }
  @media (min-width: 40.0625em) {
    margin-left: 0;
    ::before {
      content: none;
    }
  }
`;

const StyledA4 = styled.a`
  font-weight: 700;
  :focus {
    outline: 3px solid #ffbf47;
    outline-offset: 0;
  }
  :link,
  :visited,
  :hover,
  :active {
    color: #b10e1e;
  }
  :focus {
    color: #0b0c0c;
  }
  font-family: Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  font-weight: 700;
  font-size: 0.875rem;
  line-height: 1.14286;
  white-space: nowrap;
  @media print {
    font-family: sans-serif;
  }
  @media (min-width: 40.0625em) {
    font-size: 1rem;
    line-height: 1.25;
  }
  @media print {
    font-size: 14pt;
    line-height: 1.2;
  }
  :link,
  :hover,
  :visited {
    color: #1d8feb;
  }
  :focus {
    color: #0b0c0c;
  }
  font-family: Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  font-weight: 400;
  font-size: 1rem;
  line-height: 1.25;
  display: inline-block;
  padding-top: 10px;
  padding-bottom: 10px;
  @media print {
    font-family: sans-serif;
  }
  :focus {
    outline: 3px solid #ffbf47;
    outline-offset: 0;
    background-color: #ffbf47;
  }
  :link {
    color: #005ea5;
  }
  :visited {
    color: #4c2c92;
  }
  :hover {
    color: #2b8cc4;
  }
  :active {
    color: #2b8cc4;
  }
  :focus {
    color: #0b0c0c;
  }
  @media print {
    font-family: sans-serif;
  }
  @media (min-width: 40.0625em) {
    font-size: 1.1875rem;
    line-height: 1.31579;
  }
  @media print {
    font-size: 14pt;
    line-height: 1.15;
  }
  @media (min-width: 40.0625em) {
    margin-right: 5px;
    padding-right: 20px;
    padding-left: 20px;
    float: left;
    color: #0b0c0c;
    background-color: #f8f8f8;
    text-align: center;
    text-decoration: none;
  }
`;

const StyledSection = styled.section`
  margin-bottom: 30px;
  @media (min-width: 40.0625em) {
    margin-bottom: 50px;
  }
  @media (min-width: 40.0625em) {
    margin-bottom: 0;
    padding-top: 30px;
    padding-right: 20px;
    padding-bottom: 30px;
    padding-left: 20px;
    border: 1px solid #bfc1c3;
    border-top: 0;
  }
  @media (min-width: 40.0625em) and (min-width: 40.0625em) {
    margin-bottom: 0;
  }
`;

const StyledH22 = styled.h2`
  color: #2a2a2a;
  font-family: Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  font-weight: g-heading-font-weight;
  font-size: 2rem;
  line-height: 1.2;
  display: block;
  margin-top: 3.5rem;
  margin-bottom: 0.5rem;
  @media print {
    color: #000000;
  }
  @media print {
    font-family: sans-serif;
  }
  @media (min-width: 40.0625em) {
    font-size: 2.5rem;
    line-height: 1.25;
  }
  @media print {
    font-size: 24pt;
    line-height: 1.05;
  }
  @media (min-width: 40.0625em) {
    margin-bottom: 30px;
  }
  padding-top: 5px;
  @media (min-width: 40.0625em) {
    padding-top: 10px;
  }
  padding-top: 15px;
  @media (min-width: 40.0625em) {
    padding-top: 20px;
  }
`;

const StyledTable = styled.table`
  font-family: Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  font-weight: 400;
  font-size: 1rem;
  line-height: 1.25;
  color: #0b0c0c;
  width: 100%;
  margin-bottom: 20px;
  border-spacing: 0;
  border-collapse: collapse;
  @media print {
    font-family: sans-serif;
  }
  @media (min-width: 40.0625em) {
    font-size: 1.1875rem;
    line-height: 1.31579;
  }
  @media print {
    font-size: 14pt;
    line-height: 1.15;
  }
  @media print {
    color: #000000;
  }
  @media (min-width: 40.0625em) {
    margin-bottom: 30px;
  }
`;

const StyledSection2 = styled.section`
  margin-bottom: 30px;
  @media (min-width: 40.0625em) {
    margin-bottom: 50px;
  }
  @media (min-width: 40.0625em) {
    margin-bottom: 0;
    padding-top: 30px;
    padding-right: 20px;
    padding-bottom: 30px;
    padding-left: 20px;
    border: 1px solid #bfc1c3;
    border-top: 0;
  }
  @media (min-width: 40.0625em) and (min-width: 40.0625em) {
    margin-bottom: 0;
  }
  @media (min-width: 40.0625em) {
    display: none;
  }
`;

const StyledH23 = styled.h2`
  color: #2a2a2a;
  font-family: Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  font-weight: g-heading-font-weight;
  font-size: 2rem;
  line-height: 1.2;
  display: block;
  margin-top: 3.5rem;
  margin-bottom: 0.5rem;
  @media print {
    color: #000000;
  }
  @media print {
    font-family: sans-serif;
  }
  @media (min-width: 40.0625em) {
    font-size: 2.5rem;
    line-height: 1.25;
  }
  @media print {
    font-size: 24pt;
    line-height: 1.05;
  }
  @media (min-width: 40.0625em) {
    margin-bottom: 30px;
  }
  padding-top: 5px;
  @media (min-width: 40.0625em) {
    padding-top: 10px;
  }
  padding-top: 15px;
  @media (min-width: 40.0625em) {
    padding-top: 20px;
  }
`;

const StyledTable2 = styled.table`
  font-family: Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  font-weight: 400;
  font-size: 1rem;
  line-height: 1.25;
  color: #0b0c0c;
  width: 100%;
  margin-bottom: 20px;
  border-spacing: 0;
  border-collapse: collapse;
  @media print {
    font-family: sans-serif;
  }
  @media (min-width: 40.0625em) {
    font-size: 1.1875rem;
    line-height: 1.31579;
  }
  @media print {
    font-size: 14pt;
    line-height: 1.15;
  }
  @media print {
    color: #000000;
  }
  @media (min-width: 40.0625em) {
    margin-bottom: 30px;
  }
`;

const StyledSection3 = styled.section`
  margin-bottom: 30px;
  @media (min-width: 40.0625em) {
    margin-bottom: 50px;
  }
  @media (min-width: 40.0625em) {
    margin-bottom: 0;
    padding-top: 30px;
    padding-right: 20px;
    padding-bottom: 30px;
    padding-left: 20px;
    border: 1px solid #bfc1c3;
    border-top: 0;
  }
  @media (min-width: 40.0625em) and (min-width: 40.0625em) {
    margin-bottom: 0;
  }
  @media (min-width: 40.0625em) {
    display: none;
  }
`;

const StyledH24 = styled.h2`
  color: #2a2a2a;
  font-family: Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  font-weight: g-heading-font-weight;
  font-size: 2rem;
  line-height: 1.2;
  display: block;
  margin-top: 3.5rem;
  margin-bottom: 0.5rem;
  @media print {
    color: #000000;
  }
  @media print {
    font-family: sans-serif;
  }
  @media (min-width: 40.0625em) {
    font-size: 2.5rem;
    line-height: 1.25;
  }
  @media print {
    font-size: 24pt;
    line-height: 1.05;
  }
  @media (min-width: 40.0625em) {
    margin-bottom: 30px;
  }
  padding-top: 5px;
  @media (min-width: 40.0625em) {
    padding-top: 10px;
  }
  padding-top: 15px;
  @media (min-width: 40.0625em) {
    padding-top: 20px;
  }
`;

const StyledTable3 = styled.table`
  font-family: Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  font-weight: 400;
  font-size: 1rem;
  line-height: 1.25;
  color: #0b0c0c;
  width: 100%;
  margin-bottom: 20px;
  border-spacing: 0;
  border-collapse: collapse;
  @media print {
    font-family: sans-serif;
  }
  @media (min-width: 40.0625em) {
    font-size: 1.1875rem;
    line-height: 1.31579;
  }
  @media print {
    font-size: 14pt;
    line-height: 1.15;
  }
  @media print {
    color: #000000;
  }
  @media (min-width: 40.0625em) {
    margin-bottom: 30px;
  }
`;

const StyledSection4 = styled.section`
  margin-bottom: 30px;
  @media (min-width: 40.0625em) {
    margin-bottom: 50px;
  }
  @media (min-width: 40.0625em) {
    margin-bottom: 0;
    padding-top: 30px;
    padding-right: 20px;
    padding-bottom: 30px;
    padding-left: 20px;
    border: 1px solid #bfc1c3;
    border-top: 0;
  }
  @media (min-width: 40.0625em) and (min-width: 40.0625em) {
    margin-bottom: 0;
  }
  @media (min-width: 40.0625em) {
    display: none;
  }
`;

const StyledH25 = styled.h2`
  color: #2a2a2a;
  font-family: Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  font-weight: g-heading-font-weight;
  font-size: 2rem;
  line-height: 1.2;
  display: block;
  margin-top: 3.5rem;
  margin-bottom: 0.5rem;
  @media print {
    color: #000000;
  }
  @media print {
    font-family: sans-serif;
  }
  @media (min-width: 40.0625em) {
    font-size: 2.5rem;
    line-height: 1.25;
  }
  @media print {
    font-size: 24pt;
    line-height: 1.05;
  }
  @media (min-width: 40.0625em) {
    margin-bottom: 30px;
  }
  padding-top: 5px;
  @media (min-width: 40.0625em) {
    padding-top: 10px;
  }
  padding-top: 15px;
  @media (min-width: 40.0625em) {
    padding-top: 20px;
  }
`;

const StyledTable4 = styled.table`
  font-family: Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  font-weight: 400;
  font-size: 1rem;
  line-height: 1.25;
  color: #0b0c0c;
  width: 100%;
  margin-bottom: 20px;
  border-spacing: 0;
  border-collapse: collapse;
  @media print {
    font-family: sans-serif;
  }
  @media (min-width: 40.0625em) {
    font-size: 1.1875rem;
    line-height: 1.31579;
  }
  @media print {
    font-size: 14pt;
    line-height: 1.15;
  }
  @media print {
    color: #000000;
  }
  @media (min-width: 40.0625em) {
    margin-bottom: 30px;
  }
`;

const constants = {
  target: { Blank: "_blank", Top: "_top", Self: "_self", Parent: "_parent" },
  target2: { Blank: "_blank", Top: "_top", Self: "_self", Parent: "_parent" },
  target3: { Blank: "_blank", Top: "_top", Self: "_self", Parent: "_parent" },
  target4: { Blank: "_blank", Top: "_top", Self: "_self", Parent: "_parent" }
};

const Tabs = ({
  tabPastDay,
  pastDay,
  href,
  rel,
  target,
  tabPastWeek,
  pastWeek,
  href2,
  rel2,
  target2,
  tabPastMonth,
  pastMonth,
  href3,
  rel3,
  target3,
  tabPastYear,
  pastYear,
  href4,
  rel4,
  target4
}) => (
  <StyledDiv data-module="tabs">
    <StyledH2>Contents</StyledH2>

    <StyledUl role="tablist">
      <StyledLi role="presentation">
        <StyledA
          aria-controls={pastDay}
          aria-selected="true"
          href={href}
          id={tabPastDay}
          role="tab"
          tabIndex={0}
          rel={rel}
          target={constants.target[target]}
        >
          Past day
        </StyledA>
      </StyledLi>
      <StyledLi2 role="presentation">
        <StyledA2
          aria-controls={pastWeek}
          aria-selected="false"
          href={href2}
          id={tabPastWeek}
          role="tab"
          tabIndex={-1}
          rel={rel2}
          target={constants.target2[target2]}
        >
          Past week
        </StyledA2>
      </StyledLi2>
      <StyledLi3 role="presentation">
        <StyledA3
          aria-controls={pastMonth}
          aria-selected="false"
          href={href3}
          id={tabPastMonth}
          role="tab"
          tabIndex={-1}
          rel={rel3}
          target={constants.target3[target3]}
        >
          Past month
        </StyledA3>
      </StyledLi3>
      <StyledLi4 role="presentation">
        <StyledA4
          aria-controls={pastYear}
          aria-selected="false"
          href={href4}
          id={tabPastYear}
          role="tab"
          tabIndex={-1}
          rel={rel4}
          target={constants.target4[target4]}
        >
          Past year
        </StyledA4>
      </StyledLi4>
    </StyledUl>

    <StyledSection aria-labelledby={tabPastDay} id={pastDay} role="tabpanel">
      <StyledH22>Past day</StyledH22>
      <StyledTable>
        <thead>
          <tr>Case manager Cases opened Cases closed</tr>
        </thead>
        <tbody>
          <tr>David Francis 3 0</tr>
          <tr>Paul Farmer 1 0</tr>
          <tr>Rita Patel 2 0</tr>
        </tbody>
      </StyledTable>
    </StyledSection>
    <StyledSection2 aria-labelledby={tabPastWeek} id={pastWeek} role="tabpanel">
      <StyledH23>Past week</StyledH23>
      <StyledTable2>
        <thead>
          <tr>Case manager Cases opened Cases closed</tr>
        </thead>
        <tbody>
          <tr>David Francis 24 18</tr>
          <tr>Paul Farmer 16 20</tr>
          <tr>Rita Patel 24 27</tr>
        </tbody>
      </StyledTable2>
    </StyledSection2>
    <StyledSection3
      aria-labelledby={tabPastMonth}
      id={pastMonth}
      role="tabpanel"
    >
      <StyledH24>Past month</StyledH24>
      <StyledTable3>
        <thead>
          <tr>Case manager Cases opened Cases closed</tr>
        </thead>
        <tbody>
          <tr>David Francis 98 95</tr>
          <tr>Paul Farmer 122 131</tr>
          <tr>Rita Patel 126 142</tr>
        </tbody>
      </StyledTable3>
    </StyledSection3>
    <StyledSection4 aria-labelledby={tabPastYear} id={pastYear} role="tabpanel">
      <StyledH25>Past year</StyledH25>
      <StyledTable4>
        <thead>
          <tr>Case manager Cases opened Cases closed</tr>
        </thead>
        <tbody>
          <tr>David Francis 1380 1472</tr>
          <tr>Paul Farmer 1129 1083</tr>
          <tr>Rita Patel 1539 1265</tr>
        </tbody>
      </StyledTable4>
    </StyledSection4>
  </StyledDiv>
);

export default Tabs;
