// packages/govtnz-ds/build_src/vue-js/TagInactive.vue
<template>
  <strong class="g-tagInactive-tag g-tagInactive-tag--inactive">
    alpha
  </strong>
</template>
<script>
import Vue from "vue";

export default Vue.extend({
  props: {},
  computed: {}
});
</script>
<style scoped>
.g-tagInactive-tag {
  font-family: Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  font-weight: 700;
  font-size: 0.875rem;
  line-height: 1.25;
  display: inline-block;
  padding: 4px 8px;
  padding-bottom: 1px;
  outline: 2px solid transparent;
  outline-offset: -2px;
  color: #ffffff;
  background-color: #005ea5;
  letter-spacing: 1px;
  text-decoration: none;
  text-transform: uppercase;
}
@media print {
  .g-tagInactive-tag {
    font-family: sans-serif;
  }
}
@media (min-width: 40.0625em) {
  .g-tagInactive-tag {
    font-size: 1rem;
    line-height: 1.25;
  }
}
@media print {
  .g-tagInactive-tag {
    font-size: 14pt;
    line-height: 1.25;
  }
}
.g-tagInactive-tag--inactive {
  background-color: #6f777b;
}
.g-tagInactive-hint > * {
  margin-top: 0px;
}
</style>

// packages/govtnz-ds/build_src/react-js-styled-components/TagInactive.js
import React from "react";
import styled from "styled-components";

const StyledStrong = styled.strong`
  font-family: Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  font-weight: 700;
  font-size: 0.875rem;
  line-height: 1.25;
  display: inline-block;
  padding: 4px 8px;
  padding-bottom: 1px;
  outline: 2px solid transparent;
  outline-offset: -2px;
  color: #ffffff;
  background-color: #005ea5;
  letter-spacing: 1px;
  text-decoration: none;
  text-transform: uppercase;
  @media print {
    font-family: sans-serif;
  }
  @media (min-width: 40.0625em) {
    font-size: 1rem;
    line-height: 1.25;
  }
  @media print {
    font-size: 14pt;
    line-height: 1.25;
  }
  background-color: #6f777b;
  margin-top: 0px;
`;

const TagInactive = ({}) => <StyledStrong>alpha</StyledStrong>;

export default TagInactive;
