// packages/govtnz-ds/build_src/vue-ts/FieldsetLabel.vue
<template>
  <div class="g-fieldsetLabel-hint" v-bind:id="hintId">
    <slot name="hint"></slot>
  </div>
</template>
<script lang="ts">
import Vue from "vue";

export default Vue.extend({
  props: {
    hintId: { type: String, required: false },
    hint: { required: false, default: "Hint text" }
  },
  computed: {}
});
</script>
<style scoped>
.g-fieldsetLabel-hint {
  font-family: Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  font-weight: 400;
  font-size: 1rem;
  line-height: 1.25;
  display: block;
  margin-bottom: 15px;
  color: #595959;
}
@media print {
  .g-fieldsetLabel-hint {
    font-family: sans-serif;
  }
}
@media (min-width: 40.0625em) {
  .g-fieldsetLabel-hint {
    font-size: 1.1875rem;
    line-height: 1.31579;
  }
}
@media print {
  .g-fieldsetLabel-hint {
    font-size: 14pt;
    line-height: 1.15;
  }
}
.g-fieldset__legend + .g-fieldsetLabel-hint {
  margin-top: -5px;
}
.g-fieldsetLabel-hint > * {
  margin-top: 0px;
}
</style>

// packages/govtnz-ds/build_src/react-ts-styled-components/FieldsetLabel.tsx
import * as React from "react";
import * as styled from "styled-components";

type Props = {
  hintId?: string | undefined;
  hint?: React.ReactNode;
};

const StyledDiv = styled.div`
  font-family: Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  font-weight: 400;
  font-size: 1rem;
  line-height: 1.25;
  display: block;
  margin-bottom: 15px;
  color: #595959;
  @media print {
    font-family: sans-serif;
  }
  @media (min-width: 40.0625em) {
    font-size: 1.1875rem;
    line-height: 1.31579;
  }
  @media print {
    font-size: 14pt;
    line-height: 1.15;
  }
  margin-top: -5px;
`;

const FieldsetLabel = ({ hintId, hint }: Props) => (
  <StyledDiv id={hintId}>
    {hint !== undefined ? hint : <React.Fragment>Hint text</React.Fragment>}
  </StyledDiv>
);
FieldsetLabel.props = ["hintId", "hint"];
export default FieldsetLabel;
