// packages/govtnz-ds/build_src/vue-ts/FlexColumn.vue
<template>
  <div v-bind:class="computed__class">
    <slot></slot>
  </div>
</template>
<script lang="ts">
import Vue from "vue";

const constants = {
  xs: {
    "1": "g-flex-col-xs-1",
    "2": "g-flex-col-xs-2",
    "3": "g-flex-col-xs-3",
    "4": "g-flex-col-xs-4",
    "5": "g-flex-col-xs-5",
    "6": "g-flex-col-xs-6",
    "7": "g-flex-col-xs-7",
    "8": "g-flex-col-xs-8",
    "9": "g-flex-col-xs-9",
    "10": "g-flex-col-xs-10",
    "11": "g-flex-col-xs-11",
    "12": "g-flex-col-xs-12",
    hidden: "g-flex-col-xs-hidden",
    auto: "g-flex-col-xs"
  },
  sm: {
    "1": "g-flex-col-sm-1",
    "2": "g-flex-col-sm-2",
    "3": "g-flex-col-sm-3",
    "4": "g-flex-col-sm-4",
    "5": "g-flex-col-sm-5",
    "6": "g-flex-col-sm-6",
    "7": "g-flex-col-sm-7",
    "8": "g-flex-col-sm-8",
    "9": "g-flex-col-sm-9",
    "10": "g-flex-col-sm-10",
    "11": "g-flex-col-sm-11",
    "12": "g-flex-col-sm-12",
    hidden: "g-flex-col-sm-hidden",
    auto: "g-flex-col-sm"
  },
  md: {
    "1": "g-flex-col-md-1",
    "2": "g-flex-col-md-2",
    "3": "g-flex-col-md-3",
    "4": "g-flex-col-md-4",
    "5": "g-flex-col-md-5",
    "6": "g-flex-col-md-6",
    "7": "g-flex-col-md-7",
    "8": "g-flex-col-md-8",
    "9": "g-flex-col-md-9",
    "10": "g-flex-col-md-10",
    "11": "g-flex-col-md-11",
    "12": "g-flex-col-md-12",
    hidden: "g-flex-col-md-hidden",
    auto: "g-flex-col-md"
  },
  lg: {
    "1": "g-flex-col-lg-1",
    "2": "g-flex-col-lg-2",
    "3": "g-flex-col-lg-3",
    "4": "g-flex-col-lg-4",
    "5": "g-flex-col-lg-5",
    "6": "g-flex-col-lg-6",
    "7": "g-flex-col-lg-7",
    "8": "g-flex-col-lg-8",
    "9": "g-flex-col-lg-9",
    "10": "g-flex-col-lg-10",
    "11": "g-flex-col-lg-11",
    "12": "g-flex-col-lg-12",
    hidden: "g-flex-col-lg-hidden",
    auto: "g-flex-col-md"
  },
  xsOffset: {
    "0": "g-flex-col-xs-offset-0",
    "1": "g-flex-col-xs-offset-1",
    "2": "g-flex-col-xs-offset-2",
    "3": "g-flex-col-xs-offset-3",
    "4": "g-flex-col-xs-offset-4",
    "5": "g-flex-col-xs-offset-5",
    "6": "g-flex-col-xs-offset-6",
    "7": "g-flex-col-xs-offset-7",
    "8": "g-flex-col-xs-offset-8",
    "9": "g-flex-col-xs-offset-9",
    "10": "g-flex-col-xs-offset-10",
    "11": "g-flex-col-xs-offset-11",
    "12": "g-flex-col-xs-offset-12"
  },
  smOffset: {
    "0": "g-flex-col-sm-offset-0",
    "1": "g-flex-col-sm-offset-1",
    "2": "g-flex-col-sm-offset-2",
    "3": "g-flex-col-sm-offset-3",
    "4": "g-flex-col-sm-offset-4",
    "5": "g-flex-col-sm-offset-5",
    "6": "g-flex-col-sm-offset-6",
    "7": "g-flex-col-sm-offset-7",
    "8": "g-flex-col-sm-offset-8",
    "9": "g-flex-col-sm-offset-9",
    "10": "g-flex-col-sm-offset-10",
    "11": "g-flex-col-sm-offset-11",
    "12": "g-flex-col-sm-offset-12"
  },
  mdOffset: {
    "0": "g-flex-col-md-offset-0",
    "1": "g-flex-col-md-offset-1",
    "2": "g-flex-col-md-offset-2",
    "3": "g-flex-col-md-offset-3",
    "4": "g-flex-col-md-offset-4",
    "5": "g-flex-col-md-offset-5",
    "6": "g-flex-col-md-offset-6",
    "7": "g-flex-col-md-offset-7",
    "8": "g-flex-col-md-offset-8",
    "9": "g-flex-col-md-offset-9",
    "10": "g-flex-col-md-offset-10",
    "11": "g-flex-col-md-offset-11",
    "12": "g-flex-col-md-offset-12"
  },
  lgOffset: {
    "0": "g-flex-col-lg-offset-0",
    "1": "g-flex-col-lg-offset-1",
    "2": "g-flex-col-lg-offset-2",
    "3": "g-flex-col-lg-offset-3",
    "4": "g-flex-col-lg-offset-4",
    "5": "g-flex-col-lg-offset-5",
    "6": "g-flex-col-lg-offset-6",
    "7": "g-flex-col-lg-offset-7",
    "8": "g-flex-col-lg-offset-8",
    "9": "g-flex-col-lg-offset-9",
    "10": "g-flex-col-lg-offset-10",
    "11": "g-flex-col-lg-offset-11",
    "12": "g-flex-col-lg-offset-12"
  },
  xsHorizontalAlign: {
    start: "g-flex-start-xs",
    center: "g-flex-center-xs",
    right: "g-flex-right-xs"
  },
  smHorizontalAlign: {
    start: "g-flex-start-sm",
    center: "g-flex-center-sm",
    end: "g-flex-end-sm"
  },
  mdHorizontalAlign: {
    start: "g-flex-start-md",
    center: "g-flex-center-md",
    end: "g-flex-end-md"
  },
  lgHorizontalAlign: {
    start: "g-flex-start-lg",
    center: "g-flex-center-lg",
    end: "g-flex-end-lg"
  }
};

export default Vue.extend({
  props: {
    xs: {
      type: String,
      validator: value => {
        return (
          [
            "hidden",
            "1",
            "2",
            "3",
            "4",
            "5",
            "6",
            "7",
            "8",
            "9",
            "10",
            "11",
            "12",
            "auto"
          ].indexOf(value) !== -1
        );
      },
      required: true
    },
    sm: {
      type: String,
      validator: value => {
        return (
          [
            "hidden",
            "1",
            "2",
            "3",
            "4",
            "5",
            "6",
            "7",
            "8",
            "9",
            "10",
            "11",
            "12",
            "auto"
          ].indexOf(value) !== -1
        );
      },
      required: true
    },
    md: {
      type: String,
      validator: value => {
        return (
          [
            "hidden",
            "1",
            "2",
            "3",
            "4",
            "5",
            "6",
            "7",
            "8",
            "9",
            "10",
            "11",
            "12",
            "auto"
          ].indexOf(value) !== -1
        );
      },
      required: true
    },
    lg: {
      type: String,
      validator: value => {
        return (
          [
            "hidden",
            "1",
            "2",
            "3",
            "4",
            "5",
            "6",
            "7",
            "8",
            "9",
            "10",
            "11",
            "12",
            "auto"
          ].indexOf(value) !== -1
        );
      },
      required: true
    },
    xsOffset: {
      type: String,
      validator: value => {
        return (
          [
            "0",
            "1",
            "2",
            "3",
            "4",
            "5",
            "6",
            "7",
            "8",
            "9",
            "10",
            "11",
            "12"
          ].indexOf(value) !== -1
        );
      },
      required: false
    },
    smOffset: {
      type: String,
      validator: value => {
        return (
          [
            "0",
            "1",
            "2",
            "3",
            "4",
            "5",
            "6",
            "7",
            "8",
            "9",
            "10",
            "11",
            "12"
          ].indexOf(value) !== -1
        );
      },
      required: false
    },
    mdOffset: {
      type: String,
      validator: value => {
        return (
          [
            "0",
            "1",
            "2",
            "3",
            "4",
            "5",
            "6",
            "7",
            "8",
            "9",
            "10",
            "11",
            "12"
          ].indexOf(value) !== -1
        );
      },
      required: false
    },
    lgOffset: {
      type: String,
      validator: value => {
        return (
          [
            "0",
            "1",
            "2",
            "3",
            "4",
            "5",
            "6",
            "7",
            "8",
            "9",
            "10",
            "11",
            "12"
          ].indexOf(value) !== -1
        );
      },
      required: false
    },
    xsHorizontalAlign: {
      type: String,
      validator: value => {
        return ["start", "center", "right"].indexOf(value) !== -1;
      },
      required: false
    },
    smHorizontalAlign: {
      type: String,
      validator: value => {
        return ["start", "center", "end"].indexOf(value) !== -1;
      },
      required: false
    },
    mdHorizontalAlign: {
      type: String,
      validator: value => {
        return ["start", "center", "end"].indexOf(value) !== -1;
      },
      required: false
    },
    lgHorizontalAlign: {
      type: String,
      validator: value => {
        return ["start", "center", "end"].indexOf(value) !== -1;
      },
      required: false
    },
    isReversed: { type: Boolean, default: false, required: false },
    class: { type: String, required: false },
    children: { required: false }
  },
  computed: {
    computed__class() {
      return (
        "g-flex-col " +
        (constants.xs[this.xs] !== undefined
          ? ` ${constants.xs[this.xs]}`
          : "") +
        (constants.sm[this.sm] !== undefined
          ? ` ${constants.sm[this.sm]}`
          : "") +
        (constants.md[this.md] !== undefined
          ? ` ${constants.md[this.md]}`
          : "") +
        (constants.lg[this.lg] !== undefined
          ? ` ${constants.lg[this.lg]}`
          : "") +
        (constants.xsOffset[this.xsOffset] !== undefined
          ? ` ${constants.xsOffset[this.xsOffset]}`
          : "") +
        (constants.smOffset[this.smOffset] !== undefined
          ? ` ${constants.smOffset[this.smOffset]}`
          : "") +
        (constants.mdOffset[this.mdOffset] !== undefined
          ? ` ${constants.mdOffset[this.mdOffset]}`
          : "") +
        (constants.lgOffset[this.lgOffset] !== undefined
          ? ` ${constants.lgOffset[this.lgOffset]}`
          : "") +
        (constants.xsHorizontalAlign[this.xsHorizontalAlign] !== undefined
          ? ` ${constants.xsHorizontalAlign[this.xsHorizontalAlign]}`
          : "") +
        (constants.smHorizontalAlign[this.smHorizontalAlign] !== undefined
          ? ` ${constants.smHorizontalAlign[this.smHorizontalAlign]}`
          : "") +
        (constants.mdHorizontalAlign[this.mdHorizontalAlign] !== undefined
          ? ` ${constants.mdHorizontalAlign[this.mdHorizontalAlign]}`
          : "") +
        (constants.lgHorizontalAlign[this.lgHorizontalAlign] !== undefined
          ? ` ${constants.lgHorizontalAlign[this.lgHorizontalAlign]}`
          : "") +
        (this.isReversed ? " g-flex-reverse" : "") +
        this.class
      );
    }
  }
});
</script>
<style scoped>
.g-flex-col.g-flex-reverse {
  -webkit-box-orient: vertical;
  -webkit-box-direction: reverse;
  -ms-flex-direction: column-reverse;
  flex-direction: column-reverse;
}
.g-flex-col-xs,
.g-flex-col-xs-1,
.g-flex-col-xs-10,
.g-flex-col-xs-11,
.g-flex-col-xs-12,
.g-flex-col-xs-2,
.g-flex-col-xs-3,
.g-flex-col-xs-4,
.g-flex-col-xs-5,
.g-flex-col-xs-6,
.g-flex-col-xs-7,
.g-flex-col-xs-8,
.g-flex-col-xs-9,
.g-flex-col-xs-offset-0,
.g-flex-col-xs-offset-1,
.g-flex-col-xs-offset-10,
.g-flex-col-xs-offset-11,
.g-flex-col-xs-offset-12,
.g-flex-col-xs-offset-2,
.g-flex-col-xs-offset-3,
.g-flex-col-xs-offset-4,
.g-flex-col-xs-offset-5,
.g-flex-col-xs-offset-6,
.g-flex-col-xs-offset-7,
.g-flex-col-xs-offset-8,
.g-flex-col-xs-offset-9 {
  box-sizing: border-box;
  -webkit-box-flex: 0;
  -ms-flex: 0 0 auto;
  flex: 0 0 auto;
  padding-right: 0.5rem;
  padding-left: 0.5rem;
}
.g-flex-col-xs {
  -webkit-box-flex: 1;
  -ms-flex-positive: 1;
  flex-grow: 1;
  -ms-flex-preferred-size: 0;
  flex-basis: 0;
  max-width: 100%;
}
.g-flex-col-xs-hidden {
  display: none;
}
.g-flex-col-xs-1 {
  -ms-flex-preferred-size: 8.33333333%;
  flex-basis: 8.33333333%;
  max-width: 8.33333333%;
}
.g-flex-col-xs-2 {
  -ms-flex-preferred-size: 16.66666667%;
  flex-basis: 16.66666667%;
  max-width: 16.66666667%;
}
.g-flex-col-xs-3 {
  -ms-flex-preferred-size: 25%;
  flex-basis: 25%;
  max-width: 25%;
}
.g-flex-col-xs-4 {
  -ms-flex-preferred-size: 33.33333333%;
  flex-basis: 33.33333333%;
  max-width: 33.33333333%;
}
.g-flex-col-xs-5 {
  -ms-flex-preferred-size: 41.66666667%;
  flex-basis: 41.66666667%;
  max-width: 41.66666667%;
}
.g-flex-col-xs-6 {
  -ms-flex-preferred-size: 50%;
  flex-basis: 50%;
  max-width: 50%;
}
.g-flex-col-xs-7 {
  -ms-flex-preferred-size: 58.33333333%;
  flex-basis: 58.33333333%;
  max-width: 58.33333333%;
}
.g-flex-col-xs-8 {
  -ms-flex-preferred-size: 66.66666667%;
  flex-basis: 66.66666667%;
  max-width: 66.66666667%;
}
.g-flex-col-xs-9 {
  -ms-flex-preferred-size: 75%;
  flex-basis: 75%;
  max-width: 75%;
}
.g-flex-col-xs-10 {
  -ms-flex-preferred-size: 83.33333333%;
  flex-basis: 83.33333333%;
  max-width: 83.33333333%;
}
.g-flex-col-xs-11 {
  -ms-flex-preferred-size: 91.66666667%;
  flex-basis: 91.66666667%;
  max-width: 91.66666667%;
}
.g-flex-col-xs-12 {
  -ms-flex-preferred-size: 100%;
  flex-basis: 100%;
  max-width: 100%;
}
.g-flex-col-xs-offset-0 {
  margin-left: 0;
}
.g-flex-col-xs-offset-1 {
  margin-left: 8.33333333%;
}
.g-flex-col-xs-offset-2 {
  margin-left: 16.66666667%;
}
.g-flex-col-xs-offset-3 {
  margin-left: 25%;
}
.g-flex-col-xs-offset-4 {
  margin-left: 33.33333333%;
}
.g-flex-col-xs-offset-5 {
  margin-left: 41.66666667%;
}
.g-flex-col-xs-offset-6 {
  margin-left: 50%;
}
.g-flex-col-xs-offset-8 {
  margin-left: 66.66666667%;
}
.g-flex-col-xs-offset-9 {
  margin-left: 75%;
}
.g-flex-col-xs-offset-10 {
  margin-left: 83.33333333%;
}
.g-flex-col-xs-offset-11 {
  margin-left: 91.66666667%;
}
.g-flex-start-xs {
  -webkit-box-pack: start;
  -ms-flex-pack: start;
  justify-content: flex-start;
  text-align: start;
}
.g-flex-center-xs {
  -webkit-box-pack: center;
  -ms-flex-pack: center;
  justify-content: center;
  text-align: center;
}
@media only screen and (min-width: 48em) {
  .g-flex-col-sm,
  .g-flex-col-sm-1,
  .g-flex-col-sm-2,
  .g-flex-col-sm-3,
  .g-flex-col-sm-4,
  .g-flex-col-sm-5,
  .g-flex-col-sm-6,
  .g-flex-col-sm-7,
  .g-flex-col-sm-8,
  .g-flex-col-sm-9,
  .g-flex-col-sm-10,
  .g-flex-col-sm-11,
  .g-flex-col-sm-12,
  .g-flex-col-sm-offset-0,
  .g-flex-col-sm-offset-1,
  .g-flex-col-sm-offset-10,
  .g-flex-col-sm-offset-11,
  .g-flex-col-sm-offset-12,
  .g-flex-col-sm-offset-2,
  .g-flex-col-sm-offset-3,
  .g-flex-col-sm-offset-4,
  .g-flex-col-sm-offset-5,
  .g-flex-col-sm-offset-6,
  .g-flex-col-sm-offset-7,
  .g-flex-col-sm-offset-8,
  .g-flex-col-sm-offset-9 {
    box-sizing: border-box;
    -webkit-box-flex: 0;
    -ms-flex: 0 0 auto;
    flex: 0 0 auto;
    padding-right: 0.5rem;
    padding-left: 0.5rem;
  }
  .g-flex-col-sm-hidden {
    display: none;
  }
  .g-flex-col-sm {
    -webkit-box-flex: 1;
    -ms-flex-positive: 1;
    flex-grow: 1;
    -ms-flex-preferred-size: 0;
    flex-basis: 0;
    max-width: 100%;
  }
  .g-flex-col-sm-1 {
    -ms-flex-preferred-size: 8.33333333%;
    flex-basis: 8.33333333%;
    max-width: 8.33333333%;
  }
  .g-flex-col-sm-2 {
    -ms-flex-preferred-size: 16.66666667%;
    flex-basis: 16.66666667%;
    max-width: 16.66666667%;
  }
  .g-flex-col-sm-3 {
    -ms-flex-preferred-size: 25%;
    flex-basis: 25%;
    max-width: 25%;
  }
  .g-flex-col-sm-4 {
    -ms-flex-preferred-size: 33.33333333%;
    flex-basis: 33.33333333%;
    max-width: 33.33333333%;
  }
  .g-flex-col-sm-5 {
    -ms-flex-preferred-size: 41.66666667%;
    flex-basis: 41.66666667%;
    max-width: 41.66666667%;
  }
  .g-flex-col-sm-6 {
    -ms-flex-preferred-size: 50%;
    flex-basis: 50%;
    max-width: 50%;
  }
  .g-flex-col-sm-7 {
    -ms-flex-preferred-size: 58.33333333%;
    flex-basis: 58.33333333%;
    max-width: 58.33333333%;
  }
  .g-flex-col-sm-8 {
    -ms-flex-preferred-size: 66.66666667%;
    flex-basis: 66.66666667%;
    max-width: 66.66666667%;
  }
  .g-flex-col-sm-9 {
    -ms-flex-preferred-size: 75%;
    flex-basis: 75%;
    max-width: 75%;
  }
  .g-flex-col-sm-10 {
    -ms-flex-preferred-size: 83.33333333%;
    flex-basis: 83.33333333%;
    max-width: 83.33333333%;
  }
  .g-flex-col-sm-11 {
    -ms-flex-preferred-size: 91.66666667%;
    flex-basis: 91.66666667%;
    max-width: 91.66666667%;
  }
  .g-flex-col-sm-12 {
    -ms-flex-preferred-size: 100%;
    flex-basis: 100%;
    max-width: 100%;
  }
  .g-flex-col-sm-offset-0 {
    margin-left: 0;
  }
  .g-flex-col-sm-offset-1 {
    margin-left: 8.33333333%;
  }
  .g-flex-col-sm-offset-2 {
    margin-left: 16.66666667%;
  }
  .g-flex-col-sm-offset-3 {
    margin-left: 25%;
  }
  .g-flex-col-sm-offset-4 {
    margin-left: 33.33333333%;
  }
  .g-flex-col-sm-offset-5 {
    margin-left: 41.66666667%;
  }
  .g-flex-col-sm-offset-6 {
    margin-left: 50%;
  }
  .g-flex-col-sm-offset-7 {
    margin-left: 58.33333333%;
  }
  .g-flex-col-sm-offset-8 {
    margin-left: 66.66666667%;
  }
  .g-flex-col-sm-offset-9 {
    margin-left: 75%;
  }
  .g-flex-col-sm-offset-10 {
    margin-left: 83.33333333%;
  }
  .g-flex-col-sm-offset-11 {
    margin-left: 91.66666667%;
  }
  .g-flex-start-sm {
    -webkit-box-pack: start;
    -ms-flex-pack: start;
    justify-content: flex-start;
    text-align: start;
  }
  .g-flex-center-sm {
    -webkit-box-pack: center;
    -ms-flex-pack: center;
    justify-content: center;
    text-align: center;
  }
  .g-flex-end-sm {
    -webkit-box-pack: end;
    -ms-flex-pack: end;
    justify-content: flex-end;
    text-align: end;
  }
}
@media only screen and (min-width: 64em) {
  .g-flex-col-md,
  .g-flex-col-md-1,
  .g-flex-col-md-10,
  .g-flex-col-md-11,
  .g-flex-col-md-12,
  .g-flex-col-md-2,
  .g-flex-col-md-3,
  .g-flex-col-md-4,
  .g-flex-col-md-5,
  .g-flex-col-md-6,
  .g-flex-col-md-7,
  .g-flex-col-md-8,
  .g-flex-col-md-9,
  .g-flex-col-md-offset-0,
  .g-flex-col-md-offset-1,
  .g-flex-col-md-offset-10,
  .g-flex-col-md-offset-11,
  .g-flex-col-md-offset-12,
  .g-flex-col-md-offset-2,
  .g-flex-col-md-offset-3,
  .g-flex-col-md-offset-4,
  .g-flex-col-md-offset-5,
  .g-flex-col-md-offset-6,
  .g-flex-col-md-offset-7,
  .g-flex-col-md-offset-8,
  .g-flex-col-md-offset-9 {
    box-sizing: border-box;
    -webkit-box-flex: 0;
    -ms-flex: 0 0 auto;
    flex: 0 0 auto;
    padding-right: 0.5rem;
    padding-left: 0.5rem;
  }
  .g-flex-col-md-hidden {
    display: none;
  }
  .g-flex-col-md {
    -webkit-box-flex: 1;
    -ms-flex-positive: 1;
    flex-grow: 1;
    -ms-flex-preferred-size: 0;
    flex-basis: 0;
    max-width: 100%;
  }
  .g-flex-col-md-1 {
    -ms-flex-preferred-size: 8.33333333%;
    flex-basis: 8.33333333%;
    max-width: 8.33333333%;
  }
  .g-flex-col-md-2 {
    -ms-flex-preferred-size: 16.66666667%;
    flex-basis: 16.66666667%;
    max-width: 16.66666667%;
  }
  .g-flex-col-md-3 {
    -ms-flex-preferred-size: 25%;
    flex-basis: 25%;
    max-width: 25%;
  }
  .g-flex-col-md-4 {
    -ms-flex-preferred-size: 33.33333333%;
    flex-basis: 33.33333333%;
    max-width: 33.33333333%;
  }
  .g-flex-col-md-5 {
    -ms-flex-preferred-size: 41.66666667%;
    flex-basis: 41.66666667%;
    max-width: 41.66666667%;
  }
  .g-flex-col-md-6 {
    -ms-flex-preferred-size: 50%;
    flex-basis: 50%;
    max-width: 50%;
  }
  .g-flex-col-md-7 {
    -ms-flex-preferred-size: 58.33333333%;
    flex-basis: 58.33333333%;
    max-width: 58.33333333%;
  }
  .g-flex-col-md-8 {
    -ms-flex-preferred-size: 66.66666667%;
    flex-basis: 66.66666667%;
    max-width: 66.66666667%;
  }
  .g-flex-col-md-9 {
    -ms-flex-preferred-size: 75%;
    flex-basis: 75%;
    max-width: 75%;
  }
  .g-flex-col-md-10 {
    -ms-flex-preferred-size: 83.33333333%;
    flex-basis: 83.33333333%;
    max-width: 83.33333333%;
  }
  .g-flex-col-md-11 {
    -ms-flex-preferred-size: 91.66666667%;
    flex-basis: 91.66666667%;
    max-width: 91.66666667%;
  }
  .g-flex-col-md-12 {
    -ms-flex-preferred-size: 100%;
    flex-basis: 100%;
    max-width: 100%;
  }
  .g-flex-col-md-offset-0 {
    margin-left: 0;
  }
  .g-flex-col-md-offset-1 {
    margin-left: 8.33333333%;
  }
  .g-flex-col-md-offset-2 {
    margin-left: 16.66666667%;
  }
  .g-flex-col-md-offset-3 {
    margin-left: 25%;
  }
  .g-flex-col-md-offset-4 {
    margin-left: 33.33333333%;
  }
  .g-flex-col-md-offset-5 {
    margin-left: 41.66666667%;
  }
  .g-flex-col-md-offset-6 {
    margin-left: 50%;
  }
  .g-flex-col-md-offset-7 {
    margin-left: 58.33333333%;
  }
  .g-flex-col-md-offset-8 {
    margin-left: 66.66666667%;
  }
  .g-flex-col-md-offset-9 {
    margin-left: 75%;
  }
  .g-flex-col-md-offset-10 {
    margin-left: 83.33333333%;
  }
  .g-flex-col-md-offset-11 {
    margin-left: 91.66666667%;
  }
  .g-flex-start-md {
    -webkit-box-pack: start;
    -ms-flex-pack: start;
    justify-content: flex-start;
    text-align: start;
  }
  .g-flex-center-md {
    -webkit-box-pack: center;
    -ms-flex-pack: center;
    justify-content: center;
    text-align: center;
  }
  .g-flex-end-md {
    -webkit-box-pack: end;
    -ms-flex-pack: end;
    justify-content: flex-end;
    text-align: end;
  }
}
@media only screen and (min-width: 75em) {
  .g-flex-col-lg-1,
  .g-flex-col-lg-10,
  .g-flex-col-lg-11,
  .g-flex-col-lg-12,
  .g-flex-col-lg-2,
  .g-flex-col-lg-3,
  .g-flex-col-lg-4,
  .g-flex-col-lg-5,
  .g-flex-col-lg-6,
  .g-flex-col-lg-7,
  .g-flex-col-lg-8,
  .g-flex-col-lg-9,
  .g-flex-col-lg-offset-0,
  .g-flex-col-lg-offset-1,
  .g-flex-col-lg-offset-10,
  .g-flex-col-lg-offset-11,
  .g-flex-col-lg-offset-12,
  .g-flex-col-lg-offset-2,
  .g-flex-col-lg-offset-3,
  .g-flex-col-lg-offset-4,
  .g-flex-col-lg-offset-5,
  .g-flex-col-lg-offset-6,
  .g-flex-col-lg-offset-7,
  .g-flex-col-lg-offset-8,
  .g-flex-col-lg-offset-9 {
    box-sizing: border-box;
    -webkit-box-flex: 0;
    -ms-flex: 0 0 auto;
    flex: 0 0 auto;
    padding-right: 0.5rem;
    padding-left: 0.5rem;
  }
  .g-flex-col-lg-hidden {
    display: none;
  }
  .g-flex-col-lg-1 {
    -ms-flex-preferred-size: 8.33333333%;
    flex-basis: 8.33333333%;
    max-width: 8.33333333%;
  }
  .g-flex-col-lg-2 {
    -ms-flex-preferred-size: 16.66666667%;
    flex-basis: 16.66666667%;
    max-width: 16.66666667%;
  }
  .g-flex-col-lg-3 {
    -ms-flex-preferred-size: 25%;
    flex-basis: 25%;
    max-width: 25%;
  }
  .g-flex-col-lg-4 {
    -ms-flex-preferred-size: 33.33333333%;
    flex-basis: 33.33333333%;
    max-width: 33.33333333%;
  }
  .g-flex-col-lg-5 {
    -ms-flex-preferred-size: 41.66666667%;
    flex-basis: 41.66666667%;
    max-width: 41.66666667%;
  }
  .g-flex-col-lg-6 {
    -ms-flex-preferred-size: 50%;
    flex-basis: 50%;
    max-width: 50%;
  }
  .g-flex-col-lg-7 {
    -ms-flex-preferred-size: 58.33333333%;
    flex-basis: 58.33333333%;
    max-width: 58.33333333%;
  }
  .g-flex-col-lg-8 {
    -ms-flex-preferred-size: 66.66666667%;
    flex-basis: 66.66666667%;
    max-width: 66.66666667%;
  }
  .g-flex-col-lg-9 {
    -ms-flex-preferred-size: 75%;
    flex-basis: 75%;
    max-width: 75%;
  }
  .g-flex-col-lg-10 {
    -ms-flex-preferred-size: 83.33333333%;
    flex-basis: 83.33333333%;
    max-width: 83.33333333%;
  }
  .g-flex-col-lg-11 {
    -ms-flex-preferred-size: 91.66666667%;
    flex-basis: 91.66666667%;
    max-width: 91.66666667%;
  }
  .g-flex-col-lg-12 {
    -ms-flex-preferred-size: 100%;
    flex-basis: 100%;
    max-width: 100%;
  }
  .g-flex-col-lg-offset-0 {
    margin-left: 0;
  }
  .g-flex-col-lg-offset-1 {
    margin-left: 8.33333333%;
  }
  .g-flex-col-lg-offset-2 {
    margin-left: 16.66666667%;
  }
  .g-flex-col-lg-offset-3 {
    margin-left: 25%;
  }
  .g-flex-col-lg-offset-4 {
    margin-left: 33.33333333%;
  }
  .g-flex-col-lg-offset-5 {
    margin-left: 41.66666667%;
  }
  .g-flex-col-lg-offset-6 {
    margin-left: 50%;
  }
  .g-flex-col-lg-offset-7 {
    margin-left: 58.33333333%;
  }
  .g-flex-col-lg-offset-8 {
    margin-left: 66.66666667%;
  }
  .g-flex-col-lg-offset-9 {
    margin-left: 75%;
  }
  .g-flex-col-lg-offset-10 {
    margin-left: 83.33333333%;
  }
  .g-flex-start-lg {
    -webkit-box-pack: start;
    -ms-flex-pack: start;
    justify-content: flex-start;
    text-align: start;
  }
  .g-flex-center-lg {
    -webkit-box-pack: center;
    -ms-flex-pack: center;
    justify-content: center;
    text-align: center;
  }
  .g-flex-end-lg {
    -webkit-box-pack: end;
    -ms-flex-pack: end;
    justify-content: flex-end;
    text-align: end;
  }
}
</style>

// packages/govtnz-ds/build_src/react-ts-styled-components/FlexColumn.tsx
import React from "react";
import styled from "styled-components";

type Props = {
  xs:
    | "hidden"
    | "1"
    | "2"
    | "3"
    | "4"
    | "5"
    | "6"
    | "7"
    | "8"
    | "9"
    | "10"
    | "11"
    | "12"
    | "auto";
  sm:
    | "hidden"
    | "1"
    | "2"
    | "3"
    | "4"
    | "5"
    | "6"
    | "7"
    | "8"
    | "9"
    | "10"
    | "11"
    | "12"
    | "auto";
  md:
    | "hidden"
    | "1"
    | "2"
    | "3"
    | "4"
    | "5"
    | "6"
    | "7"
    | "8"
    | "9"
    | "10"
    | "11"
    | "12"
    | "auto";
  lg:
    | "hidden"
    | "1"
    | "2"
    | "3"
    | "4"
    | "5"
    | "6"
    | "7"
    | "8"
    | "9"
    | "10"
    | "11"
    | "12"
    | "auto";
  xsOffset?:
    | "0"
    | "1"
    | "2"
    | "3"
    | "4"
    | "5"
    | "6"
    | "7"
    | "8"
    | "9"
    | "10"
    | "11"
    | "12";
  smOffset?:
    | "0"
    | "1"
    | "2"
    | "3"
    | "4"
    | "5"
    | "6"
    | "7"
    | "8"
    | "9"
    | "10"
    | "11"
    | "12";
  mdOffset?:
    | "0"
    | "1"
    | "2"
    | "3"
    | "4"
    | "5"
    | "6"
    | "7"
    | "8"
    | "9"
    | "10"
    | "11"
    | "12";
  lgOffset?:
    | "0"
    | "1"
    | "2"
    | "3"
    | "4"
    | "5"
    | "6"
    | "7"
    | "8"
    | "9"
    | "10"
    | "11"
    | "12";
  xsHorizontalAlign?: "start" | "center" | "right";
  smHorizontalAlign?: "start" | "center" | "end";
  mdHorizontalAlign?: "start" | "center" | "end";
  lgHorizontalAlign?: "start" | "center" | "end";
  isReversed?: boolean;
  className?: any;
  children?: React.ReactNode;
};

const StyledDiv = styled.div<
  Pick<
    Props,
    | "xs"
    | "xsOffset"
    | "xsHorizontalAlign"
    | "sm"
    | "smOffset"
    | "smHorizontalAlign"
    | "md"
    | "lg"
    | "mdOffset"
    | "mdHorizontalAlign"
    | "lgOffset"
    | "lgHorizontalAlign"
  >
>`-ms-flex-direction: column-reverse;
flex-direction: column-reverse;
${props =>
  ([
    "auto",
    "1",
    "10",
    "11",
    "12",
    "2",
    "3",
    "4",
    "5",
    "6",
    "7",
    "8",
    "9"
  ].indexOf(props.xs) !== -1 ||
    [
      "0",
      "1",
      "10",
      "11",
      "12",
      "2",
      "3",
      "4",
      "5",
      "6",
      "7",
      "8",
      "9"
    ].indexOf(props.xsOffset) !== -1) &&
  styled.css`
    box-sizing: border-box;
    -ms-flex: 0 0 auto;
    flex: 0 0 auto;
    padding-right: 0.5rem;
    padding-left: 0.5rem;
  `}
${props =>
  props.xs === "auto" &&
  styled.css`
    -ms-flex-positive: 1;
    flex-grow: 1;
    -ms-flex-preferred-size: 0;
    flex-basis: 0;
    max-width: 100%;
  `}
${props =>
  props.xs === "hidden" &&
  styled.css`
    display: none;
  `}
${props =>
  props.xs === "1" &&
  styled.css`
    -ms-flex-preferred-size: 8.33333333%;
    flex-basis: 8.33333333%;
    max-width: 8.33333333%;
  `}
${props =>
  props.xs === "2" &&
  styled.css`
    -ms-flex-preferred-size: 16.66666667%;
    flex-basis: 16.66666667%;
    max-width: 16.66666667%;
  `}
${props =>
  props.xs === "3" &&
  styled.css`
    -ms-flex-preferred-size: 25%;
    flex-basis: 25%;
    max-width: 25%;
  `}
${props =>
  props.xs === "4" &&
  styled.css`
    -ms-flex-preferred-size: 33.33333333%;
    flex-basis: 33.33333333%;
    max-width: 33.33333333%;
  `}
${props =>
  props.xs === "5" &&
  styled.css`
    -ms-flex-preferred-size: 41.66666667%;
    flex-basis: 41.66666667%;
    max-width: 41.66666667%;
  `}
${props =>
  props.xs === "6" &&
  styled.css`
    -ms-flex-preferred-size: 50%;
    flex-basis: 50%;
    max-width: 50%;
  `}
${props =>
  props.xs === "7" &&
  styled.css`
    -ms-flex-preferred-size: 58.33333333%;
    flex-basis: 58.33333333%;
    max-width: 58.33333333%;
  `}
${props =>
  props.xs === "8" &&
  styled.css`
    -ms-flex-preferred-size: 66.66666667%;
    flex-basis: 66.66666667%;
    max-width: 66.66666667%;
  `}
${props =>
  props.xs === "9" &&
  styled.css`
    -ms-flex-preferred-size: 75%;
    flex-basis: 75%;
    max-width: 75%;
  `}
${props =>
  props.xs === "10" &&
  styled.css`
    -ms-flex-preferred-size: 83.33333333%;
    flex-basis: 83.33333333%;
    max-width: 83.33333333%;
  `}
${props =>
  props.xs === "11" &&
  styled.css`
    -ms-flex-preferred-size: 91.66666667%;
    flex-basis: 91.66666667%;
    max-width: 91.66666667%;
  `}
${props =>
  props.xs === "12" &&
  styled.css`
    -ms-flex-preferred-size: 100%;
    flex-basis: 100%;
    max-width: 100%;
  `}
${props =>
  props.xsOffset === "0" &&
  styled.css`
    margin-left: 0;
  `}
${props =>
  props.xsOffset === "1" &&
  styled.css`
    margin-left: 8.33333333%;
  `}
${props =>
  props.xsOffset === "2" &&
  styled.css`
    margin-left: 16.66666667%;
  `}
${props =>
  props.xsOffset === "3" &&
  styled.css`
    margin-left: 25%;
  `}
${props =>
  props.xsOffset === "4" &&
  styled.css`
    margin-left: 33.33333333%;
  `}
${props =>
  props.xsOffset === "5" &&
  styled.css`
    margin-left: 41.66666667%;
  `}
${props =>
  props.xsOffset === "6" &&
  styled.css`
    margin-left: 50%;
  `}
${props =>
  props.xsOffset === "8" &&
  styled.css`
    margin-left: 66.66666667%;
  `}
${props =>
  props.xsOffset === "9" &&
  styled.css`
    margin-left: 75%;
  `}
${props =>
  props.xsOffset === "10" &&
  styled.css`
    margin-left: 83.33333333%;
  `}
${props =>
  props.xsOffset === "11" &&
  styled.css`
    margin-left: 91.66666667%;
  `}
${props =>
  props.xsHorizontalAlign === "start" &&
  styled.css`
    -webkit-box-pack: start;
    -ms-flex-pack: start;
    justify-content: flex-start;
    text-align: start;
  `}
${props =>
  props.xsHorizontalAlign === "center" &&
  styled.css`
    -webkit-box-pack: center;
    -ms-flex-pack: center;
    justify-content: center;
    text-align: center;
  `}
@media only screen and (min-width: 48em){
${props =>
  ([
    "auto",
    "1",
    "2",
    "3",
    "4",
    "5",
    "6",
    "7",
    "8",
    "9",
    "10",
    "11",
    "12"
  ].indexOf(props.sm) !== -1 ||
    [
      "0",
      "1",
      "10",
      "11",
      "12",
      "2",
      "3",
      "4",
      "5",
      "6",
      "7",
      "8",
      "9"
    ].indexOf(props.smOffset) !== -1) &&
  styled.css`
    box-sizing: border-box;
    -ms-flex: 0 0 auto;
    flex: 0 0 auto;
    padding-right: 0.5rem;
    padding-left: 0.5rem;
  `};
${props =>
  props.sm === "hidden" &&
  styled.css`
    display: none;
  `};
${props =>
  props.sm === "auto" &&
  styled.css`
    -ms-flex-positive: 1;
    flex-grow: 1;
    -ms-flex-preferred-size: 0;
    flex-basis: 0;
    max-width: 100%;
  `};
${props =>
  props.sm === "1" &&
  styled.css`
    -ms-flex-preferred-size: 8.33333333%;
    flex-basis: 8.33333333%;
    max-width: 8.33333333%;
  `};
${props =>
  props.sm === "2" &&
  styled.css`
    -ms-flex-preferred-size: 16.66666667%;
    flex-basis: 16.66666667%;
    max-width: 16.66666667%;
  `};
${props =>
  props.sm === "3" &&
  styled.css`
    -ms-flex-preferred-size: 25%;
    flex-basis: 25%;
    max-width: 25%;
  `};
${props =>
  props.sm === "4" &&
  styled.css`
    -ms-flex-preferred-size: 33.33333333%;
    flex-basis: 33.33333333%;
    max-width: 33.33333333%;
  `};
${props =>
  props.sm === "5" &&
  styled.css`
    -ms-flex-preferred-size: 41.66666667%;
    flex-basis: 41.66666667%;
    max-width: 41.66666667%;
  `};
${props =>
  props.sm === "6" &&
  styled.css`
    -ms-flex-preferred-size: 50%;
    flex-basis: 50%;
    max-width: 50%;
  `};
${props =>
  props.sm === "7" &&
  styled.css`
    -ms-flex-preferred-size: 58.33333333%;
    flex-basis: 58.33333333%;
    max-width: 58.33333333%;
  `};
${props =>
  props.sm === "8" &&
  styled.css`
    -ms-flex-preferred-size: 66.66666667%;
    flex-basis: 66.66666667%;
    max-width: 66.66666667%;
  `};
${props =>
  props.sm === "9" &&
  styled.css`
    -ms-flex-preferred-size: 75%;
    flex-basis: 75%;
    max-width: 75%;
  `};
${props =>
  props.sm === "10" &&
  styled.css`
    -ms-flex-preferred-size: 83.33333333%;
    flex-basis: 83.33333333%;
    max-width: 83.33333333%;
  `};
${props =>
  props.sm === "11" &&
  styled.css`
    -ms-flex-preferred-size: 91.66666667%;
    flex-basis: 91.66666667%;
    max-width: 91.66666667%;
  `};
${props =>
  props.sm === "12" &&
  styled.css`
    -ms-flex-preferred-size: 100%;
    flex-basis: 100%;
    max-width: 100%;
  `};
${props =>
  props.smOffset === "0" &&
  styled.css`
    margin-left: 0;
  `};
${props =>
  props.smOffset === "1" &&
  styled.css`
    margin-left: 8.33333333%;
  `};
${props =>
  props.smOffset === "2" &&
  styled.css`
    margin-left: 16.66666667%;
  `};
${props =>
  props.smOffset === "3" &&
  styled.css`
    margin-left: 25%;
  `};
${props =>
  props.smOffset === "4" &&
  styled.css`
    margin-left: 33.33333333%;
  `};
${props =>
  props.smOffset === "5" &&
  styled.css`
    margin-left: 41.66666667%;
  `};
${props =>
  props.smOffset === "6" &&
  styled.css`
    margin-left: 50%;
  `};
${props =>
  props.smOffset === "7" &&
  styled.css`
    margin-left: 58.33333333%;
  `};
${props =>
  props.smOffset === "8" &&
  styled.css`
    margin-left: 66.66666667%;
  `};
${props =>
  props.smOffset === "9" &&
  styled.css`
    margin-left: 75%;
  `};
${props =>
  props.smOffset === "10" &&
  styled.css`
    margin-left: 83.33333333%;
  `};
${props =>
  props.smOffset === "11" &&
  styled.css`
    margin-left: 91.66666667%;
  `};
${props =>
  props.smHorizontalAlign === "start" &&
  styled.css`
    -webkit-box-pack: start;
    -ms-flex-pack: start;
    justify-content: flex-start;
    text-align: start;
  `};
${props =>
  props.smHorizontalAlign === "center" &&
  styled.css`
    -webkit-box-pack: center;
    -ms-flex-pack: center;
    justify-content: center;
    text-align: center;
  `};
${props =>
  props.smHorizontalAlign === "end" &&
  styled.css`
    -webkit-box-pack: end;
    -ms-flex-pack: end;
    justify-content: flex-end;
    text-align: end;
  `};
}
@media only screen and (min-width: 64em){
${props =>
  ([
    "auto",
    "1",
    "10",
    "11",
    "12",
    "2",
    "3",
    "4",
    "5",
    "6",
    "7",
    "8",
    "9"
  ].indexOf(props.md) !== -1 ||
    props.lg === "auto" ||
    [
      "0",
      "1",
      "10",
      "11",
      "12",
      "2",
      "3",
      "4",
      "5",
      "6",
      "7",
      "8",
      "9"
    ].indexOf(props.mdOffset) !== -1) &&
  styled.css`
    box-sizing: border-box;
    -ms-flex: 0 0 auto;
    flex: 0 0 auto;
    padding-right: 0.5rem;
    padding-left: 0.5rem;
  `};
${props =>
  props.md === "hidden" &&
  styled.css`
    display: none;
  `};
${props =>
  (props.md === "auto" || props.lg === "auto") &&
  styled.css`
    -ms-flex-positive: 1;
    flex-grow: 1;
    -ms-flex-preferred-size: 0;
    flex-basis: 0;
    max-width: 100%;
  `};
${props =>
  props.md === "1" &&
  styled.css`
    -ms-flex-preferred-size: 8.33333333%;
    flex-basis: 8.33333333%;
    max-width: 8.33333333%;
  `};
${props =>
  props.md === "2" &&
  styled.css`
    -ms-flex-preferred-size: 16.66666667%;
    flex-basis: 16.66666667%;
    max-width: 16.66666667%;
  `};
${props =>
  props.md === "3" &&
  styled.css`
    -ms-flex-preferred-size: 25%;
    flex-basis: 25%;
    max-width: 25%;
  `};
${props =>
  props.md === "4" &&
  styled.css`
    -ms-flex-preferred-size: 33.33333333%;
    flex-basis: 33.33333333%;
    max-width: 33.33333333%;
  `};
${props =>
  props.md === "5" &&
  styled.css`
    -ms-flex-preferred-size: 41.66666667%;
    flex-basis: 41.66666667%;
    max-width: 41.66666667%;
  `};
${props =>
  props.md === "6" &&
  styled.css`
    -ms-flex-preferred-size: 50%;
    flex-basis: 50%;
    max-width: 50%;
  `};
${props =>
  props.md === "7" &&
  styled.css`
    -ms-flex-preferred-size: 58.33333333%;
    flex-basis: 58.33333333%;
    max-width: 58.33333333%;
  `};
${props =>
  props.md === "8" &&
  styled.css`
    -ms-flex-preferred-size: 66.66666667%;
    flex-basis: 66.66666667%;
    max-width: 66.66666667%;
  `};
${props =>
  props.md === "9" &&
  styled.css`
    -ms-flex-preferred-size: 75%;
    flex-basis: 75%;
    max-width: 75%;
  `};
${props =>
  props.md === "10" &&
  styled.css`
    -ms-flex-preferred-size: 83.33333333%;
    flex-basis: 83.33333333%;
    max-width: 83.33333333%;
  `};
${props =>
  props.md === "11" &&
  styled.css`
    -ms-flex-preferred-size: 91.66666667%;
    flex-basis: 91.66666667%;
    max-width: 91.66666667%;
  `};
${props =>
  props.md === "12" &&
  styled.css`
    -ms-flex-preferred-size: 100%;
    flex-basis: 100%;
    max-width: 100%;
  `};
${props =>
  props.mdOffset === "0" &&
  styled.css`
    margin-left: 0;
  `};
${props =>
  props.mdOffset === "1" &&
  styled.css`
    margin-left: 8.33333333%;
  `};
${props =>
  props.mdOffset === "2" &&
  styled.css`
    margin-left: 16.66666667%;
  `};
${props =>
  props.mdOffset === "3" &&
  styled.css`
    margin-left: 25%;
  `};
${props =>
  props.mdOffset === "4" &&
  styled.css`
    margin-left: 33.33333333%;
  `};
${props =>
  props.mdOffset === "5" &&
  styled.css`
    margin-left: 41.66666667%;
  `};
${props =>
  props.mdOffset === "6" &&
  styled.css`
    margin-left: 50%;
  `};
${props =>
  props.mdOffset === "7" &&
  styled.css`
    margin-left: 58.33333333%;
  `};
${props =>
  props.mdOffset === "8" &&
  styled.css`
    margin-left: 66.66666667%;
  `};
${props =>
  props.mdOffset === "9" &&
  styled.css`
    margin-left: 75%;
  `};
${props =>
  props.mdOffset === "10" &&
  styled.css`
    margin-left: 83.33333333%;
  `};
${props =>
  props.mdOffset === "11" &&
  styled.css`
    margin-left: 91.66666667%;
  `};
${props =>
  props.mdHorizontalAlign === "start" &&
  styled.css`
    -webkit-box-pack: start;
    -ms-flex-pack: start;
    justify-content: flex-start;
    text-align: start;
  `};
${props =>
  props.mdHorizontalAlign === "center" &&
  styled.css`
    -webkit-box-pack: center;
    -ms-flex-pack: center;
    justify-content: center;
    text-align: center;
  `};
${props =>
  props.mdHorizontalAlign === "end" &&
  styled.css`
    -webkit-box-pack: end;
    -ms-flex-pack: end;
    justify-content: flex-end;
    text-align: end;
  `};
}
@media only screen and (min-width: 75em){
${props =>
  (["1", "10", "11", "12", "2", "3", "4", "5", "6", "7", "8", "9"].indexOf(
    props.lg
  ) !== -1 ||
    [
      "0",
      "1",
      "10",
      "11",
      "12",
      "2",
      "3",
      "4",
      "5",
      "6",
      "7",
      "8",
      "9"
    ].indexOf(props.lgOffset) !== -1) &&
  styled.css`
    box-sizing: border-box;
    -ms-flex: 0 0 auto;
    flex: 0 0 auto;
    padding-right: 0.5rem;
    padding-left: 0.5rem;
  `};
${props =>
  props.lg === "hidden" &&
  styled.css`
    display: none;
  `};
${props =>
  props.lg === "1" &&
  styled.css`
    -ms-flex-preferred-size: 8.33333333%;
    flex-basis: 8.33333333%;
    max-width: 8.33333333%;
  `};
${props =>
  props.lg === "2" &&
  styled.css`
    -ms-flex-preferred-size: 16.66666667%;
    flex-basis: 16.66666667%;
    max-width: 16.66666667%;
  `};
${props =>
  props.lg === "3" &&
  styled.css`
    -ms-flex-preferred-size: 25%;
    flex-basis: 25%;
    max-width: 25%;
  `};
${props =>
  props.lg === "4" &&
  styled.css`
    -ms-flex-preferred-size: 33.33333333%;
    flex-basis: 33.33333333%;
    max-width: 33.33333333%;
  `};
${props =>
  props.lg === "5" &&
  styled.css`
    -ms-flex-preferred-size: 41.66666667%;
    flex-basis: 41.66666667%;
    max-width: 41.66666667%;
  `};
${props =>
  props.lg === "6" &&
  styled.css`
    -ms-flex-preferred-size: 50%;
    flex-basis: 50%;
    max-width: 50%;
  `};
${props =>
  props.lg === "7" &&
  styled.css`
    -ms-flex-preferred-size: 58.33333333%;
    flex-basis: 58.33333333%;
    max-width: 58.33333333%;
  `};
${props =>
  props.lg === "8" &&
  styled.css`
    -ms-flex-preferred-size: 66.66666667%;
    flex-basis: 66.66666667%;
    max-width: 66.66666667%;
  `};
${props =>
  props.lg === "9" &&
  styled.css`
    -ms-flex-preferred-size: 75%;
    flex-basis: 75%;
    max-width: 75%;
  `};
${props =>
  props.lg === "10" &&
  styled.css`
    -ms-flex-preferred-size: 83.33333333%;
    flex-basis: 83.33333333%;
    max-width: 83.33333333%;
  `};
${props =>
  props.lg === "11" &&
  styled.css`
    -ms-flex-preferred-size: 91.66666667%;
    flex-basis: 91.66666667%;
    max-width: 91.66666667%;
  `};
${props =>
  props.lg === "12" &&
  styled.css`
    -ms-flex-preferred-size: 100%;
    flex-basis: 100%;
    max-width: 100%;
  `};
${props =>
  props.lgOffset === "0" &&
  styled.css`
    margin-left: 0;
  `};
${props =>
  props.lgOffset === "1" &&
  styled.css`
    margin-left: 8.33333333%;
  `};
${props =>
  props.lgOffset === "2" &&
  styled.css`
    margin-left: 16.66666667%;
  `};
${props =>
  props.lgOffset === "3" &&
  styled.css`
    margin-left: 25%;
  `};
${props =>
  props.lgOffset === "4" &&
  styled.css`
    margin-left: 33.33333333%;
  `};
${props =>
  props.lgOffset === "5" &&
  styled.css`
    margin-left: 41.66666667%;
  `};
${props =>
  props.lgOffset === "6" &&
  styled.css`
    margin-left: 50%;
  `};
${props =>
  props.lgOffset === "7" &&
  styled.css`
    margin-left: 58.33333333%;
  `};
${props =>
  props.lgOffset === "8" &&
  styled.css`
    margin-left: 66.66666667%;
  `};
${props =>
  props.lgOffset === "9" &&
  styled.css`
    margin-left: 75%;
  `};
${props =>
  props.lgOffset === "10" &&
  styled.css`
    margin-left: 83.33333333%;
  `};
${props =>
  props.lgHorizontalAlign === "start" &&
  styled.css`
    -webkit-box-pack: start;
    -ms-flex-pack: start;
    justify-content: flex-start;
    text-align: start;
  `};
${props =>
  props.lgHorizontalAlign === "center" &&
  styled.css`
    -webkit-box-pack: center;
    -ms-flex-pack: center;
    justify-content: center;
    text-align: center;
  `};
${props =>
  props.lgHorizontalAlign === "end" &&
  styled.css`
    -webkit-box-pack: end;
    -ms-flex-pack: end;
    justify-content: flex-end;
    text-align: end;
  `};
}`;

const FlexColumn = ({
  xs,
  sm,
  md,
  lg,
  xsOffset,
  smOffset,
  mdOffset,
  lgOffset,
  xsHorizontalAlign,
  smHorizontalAlign,
  mdHorizontalAlign,
  lgHorizontalAlign,
  isReversed,
  className,
  children
}: Props) => (
  <StyledDiv
    xs={xs}
    sm={sm}
    md={md}
    lg={lg}
    xsOffset={xsOffset}
    smOffset={smOffset}
    mdOffset={mdOffset}
    lgOffset={lgOffset}
    xsHorizontalAlign={xsHorizontalAlign}
    smHorizontalAlign={smHorizontalAlign}
    mdHorizontalAlign={mdHorizontalAlign}
    lgHorizontalAlign={lgHorizontalAlign}
    isReversed={isReversed}
    className={className}
  >
    {children !== undefined ? children : <React.Fragment></React.Fragment>}
  </StyledDiv>
);

export default FlexColumn;
