// packages/govtnz-ds/build_src/vue-js/FooterWrapper.vue
<template>
  <footer class="g-footer-wrapper">
    <slot></slot>
  </footer> </template
><script>
import Vue from "vue";

export default Vue.extend({
  props: { children: { required: false, default: "Content..." } },
  computed: {}
});</script
><style scoped>
.g-footer-wrapper {
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}
</style>

// packages/govtnz-ds/build_src/react-ts-styled-components/FooterWrapper.tsx
import React from "react";
import styled from "styled-components";

type Props = {
  children?: React.ReactNode;
};

const StyledFooter = styled.footer`
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
`;

const FooterWrapper = ({ children }: Props) => (
  <StyledFooter>
    {" "}
    {children !== undefined ? (
      children
    ) : (
      <React.Fragment>Content...</React.Fragment>
    )}{" "}
  </StyledFooter>
);

export default FooterWrapper;
