// packages/govtnz-ds/build_src/vue-ts/Radios.vue
<template>
  <div v-bind:class="computed__class">
    <slot></slot>
  </div>
</template>
<script lang="ts">
import Vue from "vue";

export default Vue.extend({
  props: {
    inline: { type: Boolean, default: false, required: false },
    big: { type: Boolean, default: false, required: false },
    children: { required: false, default: "Radio components" }
  },
  computed: {
    computed__class() {
      return (
        "g-radios" +
        (this.inline ? " g-radios--inline" : "") +
        (this.big ? " g-radios--big" : "")
      );
    }
  }
});
</script>
<style scoped>
@media (min-width: 40.0625em) {
  .g-radios--inline:after {
    content: "";
    display: block;
    clear: both;
  }
}
.g-radios-hint > * {
  margin-top: 0px;
}
</style>

// packages/govtnz-ds/build_src/react-ts-styled-components/Radios.tsx
import React from "react";
import styled from "styled-components";

type Props = {
  inline?: boolean;
  big?: boolean;
  children?: React.ReactNode;
};

const StyledDiv = styled.div`
  @media (min-width: 40.0625em) {
    :after {
      content: "";
      display: block;
      clear: both;
    }
  }
  margin-top: 0px;
`;

const Radios = ({ inline, big, children }: Props) => (
  <StyledDiv inline={inline} big={big}>
    {" "}
    {children !== undefined ? (
      children
    ) : (
      <React.Fragment>Radio components</React.Fragment>
    )}{" "}
  </StyledDiv>
);

export default Radios;
