// packages/govtnz-ds/build_src/vue-js/Tag.vue
<template>
  <strong class="g-tag">
    alpha
  </strong> </template
><script>
import Vue from "vue";

export default Vue.extend({
  props: {},
  computed: {}
});</script
><style scoped>
.g-tag {
  font-family: Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  font-weight: 700;
  font-size: 0.875rem;
  line-height: 1.25;
  display: inline-block;
  padding: 4px 8px;
  padding-bottom: 1px;
  outline: 2px solid transparent;
  outline-offset: -2px;
  color: #ffffff;
  background-color: #005ea5;
  letter-spacing: 1px;
  text-decoration: none;
  text-transform: uppercase;
}
@media print {
  .g-tag {
    font-family: sans-serif;
  }
}
@media (min-width: 40.0625em) {
  .g-tag {
    font-size: 1rem;
    line-height: 1.25;
  }
}
@media print {
  .g-tag {
    font-size: 14pt;
    line-height: 1.25;
  }
}
.g-tag-hint > * {
  margin-top: 0px;
}
</style>

// packages/govtnz-ds/build_src/react-ts-styled-components/Tag.tsx
import * as React from "react";
import * as styled from "styled-components";

type Props = {};

const StyledStrong = styled.strong`
  font-family: Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  font-weight: 700;
  font-size: 0.875rem;
  line-height: 1.25;
  display: inline-block;
  padding: 4px 8px;
  padding-bottom: 1px;
  outline: 2px solid transparent;
  outline-offset: -2px;
  color: #ffffff;
  background-color: #005ea5;
  letter-spacing: 1px;
  text-decoration: none;
  text-transform: uppercase;
  @media print {
    font-family: sans-serif;
  }
  @media (min-width: 40.0625em) {
    font-size: 1rem;
    line-height: 1.25;
  }
  @media print {
    font-size: 14pt;
    line-height: 1.25;
  }
`;

const Tag = ({  }: Props) => <StyledStrong>alpha</StyledStrong>;
Tag.props = [];
export default Tag;
