// packages/govtnz-ds/build_src/vue-js/Ul.vue
<template>
  <ul v-bind:class="computed__class">
    <slot></slot>
  </ul>
</template>
<script>
import Vue from "vue";

export default Vue.extend({
  props: {
    spacing: { type: Boolean, default: false, required: false },
    children: { required: false, default: "Example text" }
  },
  computed: {
    computed__class() {
      return "g-ul " + (this.spacing ? " g-ul--spacing" : "");
    }
  }
});
</script>
<style scoped>
.g-ul {
  font-family: g-theme-font-family;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  font-weight: 400;
  font-size: 1.25rem;
  line-height: 1.625;
  color: g-theme-color;
  margin-top: 0;
  margin-bottom: 1rem;
  padding-left: 20px;
  list-style-type: disc;
}
@media print {
  .g-ul {
    font-family: sans-serif;
  }
}
@media (min-width: 40.0625em) {
  .g-ul {
    font-size: 1.1875rem;
    line-height: 1.31579;
    margin-bottom: 1rem;
  }
}
@media print {
  .g-ul {
    font-size: 14pt;
    line-height: 1.15;
    color: g-theme-print-color;
  }
}
.g-ul .g-ul {
  margin-top: 10px;
}
.g-hint > * {
  margin-top: 0px;
}
.g-ul li .g-ul {
  margin-top: 0.5rem;
}
</style>

// packages/govtnz-ds/build_src/react-ts-styled-components/Ul.tsx
import React from "react";
import styled from "styled-components";

type Props = {
  spacing?: boolean;
  children?: React.ReactNode;
};

const StyledUl = styled.ul`
  font-family: g-theme-font-family;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  font-weight: 400;
  font-size: 1.25rem;
  line-height: 1.625;
  color: g-theme-color;
  margin-top: 0;
  margin-bottom: 1rem;
  padding-left: 20px;
  list-style-type: disc;
  @media print {
    font-family: sans-serif;
  }
  @media (min-width: 40.0625em) {
    font-size: 1.1875rem;
    line-height: 1.31579;
    margin-bottom: 1rem;
  }
  @media print {
    font-size: 14pt;
    line-height: 1.15;
    color: g-theme-print-color;
  }
  margin-top: 10px;
  margin-top: 0px;
  margin-top: 0.5rem;
`;

const Ul = ({ spacing, children }: Props) => (
  <StyledUl spacing={spacing}>
    {children !== undefined ? (
      children
    ) : (
      <React.Fragment>Example text</React.Fragment>
    )}
  </StyledUl>
);

export default Ul;
