// packages/metatemplate/examples/container/vue-js/container.vue
<template>
  <div v-bind:class="computed__class">
    <slot></slot>
  </div> </template
><script>
import Vue from "vue";

const constants = {
  width: { fixed: "g-flex-container", fluid: "g-flex-container-fluid" }
};

export default Vue.extend({
  functional: true, // no internal state
  props: {
    width: {
      type: String,
      validator: value => {
        return ["fixed", "fluid"].indexOf(value) !== -1;
      },
      required: true
    },
    children: { required: false, default: "Rows..." }
  },
  computed: {
    computed__class() {
      return constants[this.width] !== undefined ? constants[this.width] : "";
    }
  }
});</script
><style scoped>
.g-flex-container,
.g-flex-container-fluid {
  margin-right: auto;
  margin-left: auto;
  padding-right: 1rem;
  padding-left: 1rem;
}
.g-flex-container {
  max-width: 85.375rem;
  box-sizing: border-box;
}
@media only screen and (min-width: 48em) {
  .g-flex-container,
  .g-flex-container-fluid {
    padding-right: 2rem;
    padding-left: 2rem;
  }
}
@media only screen and (min-width: 75em) {
  .g-flex-container,
  .g-flex-container-fluid {
    padding-right: 2.5rem;
    padding-left: 2.5rem;
  }
}
</style>

// packages/metatemplate/examples/container/react-ts-styled-components/container.tsx
import React from "react";
import styled from "styled-components";

type Props = {
  width: "fixed" | "fluid";
  children?: React.ReactNode;
};

const StyledDiv = styled.div<Pick<Props, "width">>`
  ${props =>
    ["fixed", "fluid"].indexOf(props.width) !== -1 &&
    styled.css`
      margin-right: auto;
      margin-left: auto;
      padding-right: 1rem;
      padding-left: 1rem;
    `}
  ${props =>
    props.width === "fixed" &&
    styled.css`
      max-width: 85.375rem;
      box-sizing: border-box;
    `}
@media only screen and (min-width: 48em) {
    ${props =>
      ["fixed", "fluid"].indexOf(props.width) !== -1 &&
      styled.css`
        padding-right: 2rem;
        padding-left: 2rem;
      `};
  }
  @media only screen and (min-width: 75em) {
    ${props =>
      ["fixed", "fluid"].indexOf(props.width) !== -1 &&
      styled.css`
        padding-right: 2.5rem;
        padding-left: 2.5rem;
      `};
  }
`;

const Container = ({ width, children }: Props) => (
  <StyledDiv width={width}>
    {children !== undefined ? (
      children
    ) : (
      <React.Fragment>Rows...</React.Fragment>
    )}
  </StyledDiv>
);

export default Container;
