// packages/govtnz-ds/build_src/angular/CheckboxBlock.ts
import { Component, Input } from "@angular/core";
@Component({
  selector: "g-CheckboxBlock",
  template: `
<div class="g-checkboxes__item{{errorId ? " g-form-group--error" : ""}}">

  
<input aria-describedby="{{hintId}}" class="g-checkboxes__input" id="{{id}}" type="checkbox" required="{{required}}" disabled="{{disabled}}" readonly="{{readOnly}}" autofocus="{{autoFocus}}" name="{{name}}" value="{{value}}" checked="{{checked}}"/>

  
<label class="g-checkboxes__label" for="{{id}}">
<slot name="label"></slot>

</label>


  
    
<div class="g-checkboxes__hint" id="{{hintId}}">

      <slot name="hint"></slot>
    

</div>


  
  
    
<div class="g-error-message" id="{{errorId}}">

      
<span class="g-visually-hidden">

        Error:
      

</span>


      <slot name="error"></slot>
    

</div>


  


</div>


`
})
export class AppComponent {
  @Input() errorId: string | undefined;
  @Input() id: string | undefined;
  @Input() hintId: string | undefined;
  @Input() required: boolean | undefined;
  @Input() disabled: boolean | undefined;
  @Input() readOnly: boolean | undefined;
  @Input() autoFocus: boolean | undefined;
  @Input() name: string;
  @Input() value: string | undefined;
  @Input() checked: boolean | undefined;
  @Input() label: React.ReactNode;
  @Input() hint: React.ReactNode;
  @Input() error: React.ReactNode;
  title = "CheckboxBlock";
}

// packages/govtnz-ds/build_src/react-js/CheckboxBlock.js
import React from "react";

const CheckboxBlock = ({
  errorId,
  id,
  hintId,
  required,
  disabled,
  readOnly,
  autoFocus,
  name,
  value,
  checked,
  onChange,
  ref,
  label,
  hint,
  error
}) => (
  <div className={`g-checkboxes__item${errorId ? " g-form-group--error" : ""}`}>
    <input
      aria-describedby={hintId}
      className="g-checkboxes__input"
      id={id}
      type="checkbox"
      required={required}
      disabled={
        disabled !== undefined ? disabled.toString() === "true" : undefined
      }
      readOnly={readOnly}
      autoFocus={autoFocus}
      name={name}
      value={value}
      checked={checked}
      onChange={onChange}
      ref={ref}
    />
    <label className="g-checkboxes__label" htmlFor={id}>
      {label !== undefined ? (
        label
      ) : (
        <React.Fragment>Label text</React.Fragment>
      )}
    </label>
    {hintId !== undefined ? (
      <React.Fragment>
        <div className="g-checkboxes__hint" id={hintId}>
          {hint !== undefined ? (
            hint
          ) : (
            <React.Fragment>Hint text</React.Fragment>
          )}
        </div>
      </React.Fragment>
    ) : (
      ""
    )}
    {errorId !== undefined ? (
      <React.Fragment>
        <div className="g-error-message" id={errorId}>
          <span className="g-visually-hidden">Error:</span>
          {error !== undefined ? (
            error
          ) : (
            <React.Fragment>Error text</React.Fragment>
          )}
        </div>
      </React.Fragment>
    ) : (
      ""
    )}
  </div>
);

export default CheckboxBlock;
