// packages/govtnz-ds/build_src/angular/Fieldset.ts
import { Component, Input } from "@angular/core";
@Component({
  selector: "g-Fieldset",
  template: `
    <div class="g-form-group">
      <fieldset aria-describedby="{{ hintId }}" class="g-fieldset">
        <slot></slot>
      </fieldset>
    </div>
  `
})
export class AppComponent {
  @Input() hintId: string | undefined;
  @Input() children: React.ReactNode;
  title = "Fieldset";
}

// packages/govtnz-ds/build_src/react-js/Fieldset.js
import React from "react";

const Fieldset = ({ hintId, children }) => (
  <div className="g-form-group">
    <fieldset aria-describedby={hintId} className="g-fieldset">
      {children !== undefined ? (
        children
      ) : (
        <React.Fragment>Legend and other fieldset contents...</React.Fragment>
      )}
    </fieldset>
  </div>
);

export default Fieldset;
