// packages/govtnz-ds/build_src/angular/H6.ts
import { Component, Input } from "@angular/core";
@Component({
  selector: "g-H6",
  template: `
<h6 class="g-heading{{constants.styleSize[styleSize] !== undefined ? " " +  constants.styleSize[styleSize] : ""}}{{marginBottom8 ? " g-heading-mb-8" : ""}}{{marginBottom0 ? " g-heading-mb-0" : ""}}" id="{{id}}">
   <slot></slot> 

</h6>

 `
})
export class AppComponent {
  @Input() styleSize:
    | "xlarge"
    | "large"
    | "medium"
    | "small"
    | "xsmall"
    | "xxsmall";
  @Input() marginBottom8: boolean | undefined;
  @Input() marginBottom0: boolean | undefined;
  @Input() id: string | undefined;
  @Input() children: React.ReactNode;
  title = "H6";
}

// packages/govtnz-ds/build_src/react-js/H6.js
import React from "react";

const constants = {
  styleSize: {
    xlarge: "g-h6-heading-xl",
    large: "g-h6-heading-l",
    medium: "g-h6-heading-m",
    small: "g-h6-heading-s",
    xsmall: "g-h6-heading-xs",
    xxsmall: "g-h6-heading-xxs"
  }
};

const H6 = ({ styleSize, marginBottom8, marginBottom0, id, children }) => (
  <h6
    className={`${
      constants.styleSize[styleSize] !== undefined
        ? constants.styleSize[styleSize]
        : ""
    }${marginBottom8 ? " g-h6-heading-mb-8" : ""}${
      marginBottom0 ? " g-h6-heading-mb-0" : ""
    }`}
    id={id}
  >
    {children !== undefined ? (
      children
    ) : (
      <React.Fragment>Example text</React.Fragment>
    )}
  </h6>
);

export default H6;
