// packages/govtnz-ds/build_src/angular/InputBlock.ts
import { Component, Input } from "@angular/core";
@Component({
  selector: "g-InputBlock",
  template: `
<div class="g-inputBlock-form-group{{errorId ? " g-inputBlock-form-group--error" : ""}}">

  
<label class="g-inputBlock-label" for="{{id}}">

    <slot name="label"></slot>
  

</label>


  
    
<div class="g-inputBlock-hint" id="{{hintId}}">

      <slot name="hint"></slot>
    

</div>


  
  
    
<div class="g-inputBlock-error-message" id="{{errorId}}">

      
<span class="g-inputBlock-visually-hidden">
Error: 

</span>


      <slot name="error"></slot>
    

</div>


  
  
<input aria-describedby="{{hintId ?  hintId : ""}}{{errorId ? " " +  errorId : ""}}" class="g-inputBlock-input{{constants.width[width] !== undefined ? " " +  constants.width[width] : ""}}{{error ? " g-inputBlock-input--error" : ""}}" id="{{id}}" name="{{name}}" required="{{required}}" disabled="{{disabled}}" readonly="{{readOnly}}" autofocus="{{autoFocus}}" value="{{value}}" min="{{min}}" max="{{max}}" type="{{type}}" spellcheck="{{spellCheck}}" maxlength="{{maxLength}}" autocomplete="{{autoComplete}}"/>



</div>


`
})
export class AppComponent {
  @Input() errorId: string | undefined;
  @Input() id: string | undefined;
  @Input() label: React.ReactNode;
  @Input() hint: React.ReactNode;
  @Input() hintId: string | undefined;
  @Input() error: boolean | undefined;
  @Input() width: "30" | "20" | "10" | "5" | "4" | "3" | "2" | undefined;
  @Input() required: boolean | undefined;
  @Input() disabled: boolean | undefined;
  @Input() readOnly: boolean | undefined;
  @Input() autoFocus: boolean | undefined;
  @Input() name: string;
  @Input() value: string | undefined;
  @Input() min: number | undefined;
  @Input() max: number | undefined;
  @Input() type: any;
  @Input() spellCheck: boolean | undefined;
  @Input() maxLength: number | undefined;
  @Input() autoComplete: any;
  title = "InputBlock";
}

// packages/govtnz-ds/build_src/react-js/InputBlock.js
import React from "react";

const constants = {
  width: {
    "2": "g-inputBlock-input--width-2",
    "3": "g-inputBlock-input--width-3",
    "4": "g-inputBlock-input--width-4",
    "5": "g-inputBlock-input--width-5",
    "10": "g-inputBlock-input--width-10",
    "20": "g-inputBlock-input--width-20",
    "30": "g-inputBlock-input--width-30"
  }
};

const InputBlock = ({
  errorId,
  id,
  label,
  hint,
  hintId,
  error,
  width,
  required,
  disabled,
  readOnly,
  autoFocus,
  name,
  value,
  min,
  max,
  type,
  spellCheck,
  maxLength,
  autoComplete,
  onChange,
  ref
}) => (
  <div
    className={`g-inputBlock-form-group${
      errorId ? " g-inputBlock-form-group--error" : ""
    }`}
  >
    <label className="g-inputBlock-label" htmlFor={id}>
      {label !== undefined ? (
        label
      ) : (
        <React.Fragment>Example text</React.Fragment>
      )}
    </label>
    {hint ? (
      <React.Fragment>
        <div className="g-inputBlock-hint" id={hintId}>
          {hint !== undefined ? (
            hint
          ) : (
            <React.Fragment>Example text</React.Fragment>
          )}
        </div>
      </React.Fragment>
    ) : (
      ""
    )}
    {errorId ? (
      <React.Fragment>
        <div className="g-inputBlock-error-message" id={errorId}>
          <span className="g-inputBlock-visually-hidden">Error: </span>
          {error !== undefined ? (
            error
          ) : (
            <React.Fragment>Example text</React.Fragment>
          )}
        </div>
      </React.Fragment>
    ) : (
      ""
    )}
    <input
      aria-describedby={
        errorId !== undefined || hintId !== undefined
          ? `${errorId ? errorId : ""}${hintId ? " " + hintId : ""}`
          : undefined
      }
      className={`g-inputBlock-input${
        constants.width[width] !== undefined ? " " + constants.width[width] : ""
      }${error ? " g-inputBlock-input--error" : ""}`}
      id={id}
      name={name}
      required={required}
      disabled={
        disabled !== undefined ? disabled.toString() === "true" : undefined
      }
      readOnly={readOnly}
      autoFocus={autoFocus}
      value={value}
      min={min}
      max={max}
      type={type}
      spellCheck={spellCheck}
      maxLength={maxLength}
      autoComplete={autoComplete}
      onChange={onChange}
      ref={ref}
    />
  </div>
);

export default InputBlock;
