// packages/govtnz-ds/build_src/angular/Input.ts
import { Component, Input } from "@angular/core";
@Component({
  selector: "g-Input",
  template: `
    <input aria-describedby="{{ describedBy }}" class="g-input{{
      constants.width[width] !== undefined ? " " + constants.width[width] : ""
    }}{{ error ? " g-input--error" : "" }}" id="{{ id }}" name="{{ name }}"
    type="text" required="{{ required }}" disabled="{{ disabled }}" readonly="{{
      readOnly
    }}" autofocus="{{ autoFocus }}" value="{{ value }}" spellcheck="{{
      spellCheck
    }}" maxlength="{{ maxLength }}" autocomplete="{{ autoComplete }}"/>
  `
})
export class AppComponent {
  @Input() width: "30" | "20" | "10" | "5" | "4" | "3" | "2" | undefined;
  @Input() error: boolean | undefined;
  @Input() id: string | undefined;
  @Input() describedBy: string | undefined;
  @Input() required: boolean | undefined;
  @Input() disabled: boolean | undefined;
  @Input() readOnly: boolean | undefined;
  @Input() autoFocus: boolean | undefined;
  @Input() name: string;
  @Input() value: string | undefined;
  @Input() spellCheck: boolean | undefined;
  @Input() maxLength: number | undefined;
  @Input() autoComplete: any;
  title = "Input";
}

// packages/govtnz-ds/build_src/react-js/Input.js
import React from "react";

const constants = {
  width: {
    "2": "g-input--width-2",
    "3": "g-input--width-3",
    "4": "g-input--width-4",
    "5": "g-input--width-5",
    "10": "g-input--width-10",
    "20": "g-input--width-20",
    "30": "g-input--width-30"
  }
};

const Input = ({
  width,
  error,
  id,
  describedBy,
  required,
  disabled,
  readOnly,
  autoFocus,
  name,
  value,
  spellCheck,
  maxLength,
  autoComplete,
  onChange,
  ref
}) => (
  <input
    aria-describedby={describedBy}
    className={`g-input${
      constants.width[width] !== undefined ? " " + constants.width[width] : ""
    }${error ? " g-input--error" : ""}`}
    id={id}
    name={name}
    type="text"
    required={required}
    disabled={
      disabled !== undefined ? disabled.toString() === "true" : undefined
    }
    readOnly={readOnly}
    autoFocus={autoFocus}
    value={value}
    spellCheck={spellCheck}
    maxLength={maxLength}
    autoComplete={autoComplete}
    onChange={onChange}
    ref={ref}
  />
);

export default Input;
