// packages/govtnz-ds/build_src/angular/Radio.ts
import { Component, Input } from "@angular/core";
@Component({
  selector: "g-Radio",
  template: `
    <input
      aria-describedby="{{ hintId }}"
      class="g-radios__input"
      id="{{ id }}"
      name="{{ name }}"
      type="radio"
      disabled="{{ disabled }}"
      readonly="{{ readOnly }}"
      autofocus="{{ autoFocus }}"
      value="{{ value }}"
      checked="{{ checked }}"
    />
  `
})
export class AppComponent {
  @Input() id: string | undefined;
  @Input() hintId: string | undefined;
  @Input() disabled: boolean | undefined;
  @Input() readOnly: boolean | undefined;
  @Input() autoFocus: boolean | undefined;
  @Input() name: string;
  @Input() value: string | undefined;
  @Input() checked: boolean | undefined;
  title = "Radio";
}

// packages/govtnz-ds/build_src/react-js/Radio.js
import React from "react";

const Radio = ({
  id,
  hintId,
  name,
  disabled,
  readOnly,
  autoFocus,
  value,
  checked,
  onChange
}) => (
  <input
    aria-describedby={hintId}
    className="g-radios__input"
    id={id}
    name={name}
    type="radio"
    disabled={disabled}
    readOnly={readOnly}
    autoFocus={autoFocus}
    value={value}
    checked={checked}
    onChange={onChange}
  />
);

export default Radio;
