// packages/govtnz-ds/build_src/angular/Select.ts
import { Component, Input } from "@angular/core";
@Component({
  selector: "g-Select",
  template: `
    <select
      class="g-select"
      id="{{ selectId }}"
      name="{{ name }}"
      required="{{ required }}"
      multiple="{{ multiple }}"
    >
      <slot></slot>
    </select>
  `
})
export class AppComponent {
  @Input() selectId: string | undefined;
  @Input() name: string;
  @Input() required: boolean | undefined;
  @Input() multiple: boolean | undefined;
  @Input() children: React.ReactNode;
  title = "Select";
}

// packages/govtnz-ds/build_src/react-js/Select.js
import React from "react";

const Select = ({
  selectId,
  name,
  required,
  multiple,
  onChange,
  ref,
  children
}) => (
  <select
    className="g-select"
    id={selectId}
    name={name}
    required={required}
    multiple={multiple}
    onChange={onChange}
    ref={ref}
  >
    {children !== undefined ? (
      children
    ) : (
      <React.Fragment>
        <option>Options</option>
      </React.Fragment>
    )}
  </select>
);

export default Select;
