// packages/govtnz-ds/build_src/react-ts/FooterLinks.tsx
import React from "react";

type Props = {
  children?: React.ReactNode;
};

const FooterLinks = ({ children }: Props) => (
  <ul className="g-footer-links">
    {children !== undefined ? (
      children
    ) : (
      <React.Fragment>example link list content</React.Fragment>
    )}
  </ul>
);

export default FooterLinks;

// packages/govtnz-ds/build_src/vue-ts/FooterLinks.vue
<template>
  <ul class="g-footer-links">
    <slot></slot>
  </ul>
</template>
<script lang="ts">
import Vue from "vue";

export default Vue.extend({
  props: {
    children: { required: false, default: "example link list content" }
  },
  computed: {}
});
</script>
<style scoped>
.g-footer-links {
  list-style: none;
  margin: 0px;
  padding: 0px;
}
</style>
