// packages/govtnz-ds/build_src/react-js-styled-components/MainNav.js
import React from "react";
import styled from "styled-components";

const StyledNav = styled.nav`
  display: block;
  padding: 0px;
  margin: 0px;
  background-color: #2a2a2a;
  margin: 0px -1rem;
  @media only screen and (min-width: 48em) {
    margin: 0px;
    background-color: transparent;
    margin: 0px -2rem;
  }
`;

const StyledButton = styled.button`
  position: absolute;
  top: 3px;
  right: 3px;
  background: transparent;
  color: #ffffff;
  font-size: 16px;
  display: none;
  padding: 1em;
  border: none;
  display: inline-block;
  @media only screen and (min-width: 48em) {
    display: none;
  }
  :focus {
    outline: 3px solid #b53cde;
  }
`;

const StyledSvg = styled.svg`
  display: inline-block;
  color: #24a882;
  transition: transform 0.15s;
  vertical-align: middle;
  margin-left: 0.2em;
  width: 12px;
  height: 12px;
  transform: rotate(180deg);
  transform: rotate(0deg);
`;

const StyledUl = styled.ul`
  list-style: none;
  padding: 0px;
  margin: 0px 0px 0px 1rem;
  display: block;
  display: none;
  @media only screen and (min-width: 48em) {
    margin: -4px 2rem 0px 2rem;
    display: block;
  }
`;

const MainNav = ({ isOpen, id, name, type, onClick, button, children }) => (
  <StyledNav aria-label="Main" role="navigation">
    <StyledButton
      isOpen={isOpen}
      aria-controls={id}
      aria-expanded={
        isOpen !== undefined ? isOpen.toString() === "true" : undefined
      }
      name={name}
      type={type}
      onClick={onClick}
    >
      {button !== undefined ? button : <React.Fragment> Menu </React.Fragment>}
      <StyledSvg viewBox="0 0 16 16" xmlns="http://www.w3.org/2000/svg">
        <path
          d="M7.992 9.55l5.6-5.6a1 1 0 0 1 1.415 0l.688.689a1 1 0 0 1 0 1.414L8.7 13.049a1 1 0 0 1-1.414 0L.29 6.053a1 1 0 0 1 0-1.414l.689-.689a1 1 0 0 1 1.414 0l5.6 5.6z"
          fill="currentColor"
          fillRule="nonzero"
        />
      </StyledSvg>
    </StyledButton>

    <div id={id}>
      <StyledUl isOpen={isOpen}>
        {children !== undefined ? (
          children
        ) : (
          <React.Fragment> MainNavLink components go here </React.Fragment>
        )}
      </StyledUl>
    </div>
  </StyledNav>
);

export default MainNav;

// packages/govtnz-ds/build_src/vue-ts/MainNav.vue
<template>
  <nav aria-label="Main" class="g-main-nav" role="navigation">
    <button
      v-bind:aria-controls="id"
      v-bind:aria-expanded="isOpen"
      v-bind:class="computed__class"
      v-bind:name="name"
      v-bind:type="type"
    >
      <slot name="button"></slot>

      <svg
        class="g-main-nav__button__icon"
        viewBox="0 0 16 16"
        xmlns="http://www.w3.org/2000/svg"
      >
        <path
          d="M7.992 9.55l5.6-5.6a1 1 0 0 1 1.415 0l.688.689a1 1 0 0 1 0 1.414L8.7 13.049a1 1 0 0 1-1.414 0L.29 6.053a1 1 0 0 1 0-1.414l.689-.689a1 1 0 0 1 1.414 0l5.6 5.6z"
          fill="currentColor"
          fill-rule="nonzero"
        />
      </svg>
    </button>

    <div v-bind:id="id">
      <ul v-bind:class="computed__class2">
        <slot></slot>
      </ul>
    </div>
  </nav>
</template>
<script lang="ts">
import Vue from "vue";

const constants = {
  isOpen: { true: "g-main-nav--open", false: "g-main-nav--closed" }
};

export default Vue.extend({
  props: {
    isOpen: {
      type: String,
      validator: value => {
        return ["true", "false"].indexOf(value) !== -1;
      },
      required: false
    },
    id: { type: String, required: false },
    name: { type: String, required: false },
    type: { type: String, required: false },
    button: { required: false, default: " Menu " },
    children: { required: false, default: " MainNavLink components go here " }
  },
  computed: {
    computed__class() {
      return (
        "g-main-nav__button " +
        (constants.isOpen[this.isOpen] !== undefined
          ? ` ${constants.isOpen[this.isOpen]}`
          : "")
      );
    },
    computed__class2() {
      return (
        "g-main-nav__ul " +
        (constants.isOpen[this.isOpen] !== undefined
          ? ` ${constants.isOpen[this.isOpen]}`
          : "")
      );
    }
  }
});
</script>
<style scoped>
.g-main-nav {
  display: block;
  padding: 0px;
  margin: 0px;
  background-color: #2a2a2a;
}
.g-flex-container .g-main-nav,
.g-flex-container-fluid .g-main-nav {
  margin: 0px -1rem;
}
@media only screen and (min-width: 48em) {
  .g-main-nav {
    margin: 0px;
    background-color: transparent;
  }
  .g-flex-container .g-main-nav,
  .g-flex-container-fluid .g-main-nav {
    margin: 0px -2rem;
  }
}
.g-main-nav__button {
  position: absolute;
  top: 3px;
  right: 3px;
  background: transparent;
  color: #ffffff;
  font-size: 16px;
  display: none;
  padding: 1em;
  border: none;
}
.g-main-nav__button.g-main-nav--open,
.g-main-nav__button.g-main-nav--closed {
  display: inline-block;
}
@media only screen and (min-width: 48em) {
  .g-main-nav__button.g-main-nav--open,
  .g-main-nav__button.g-main-nav--closed {
    display: none;
  }
}
.g-main-nav__button:focus {
  outline: 3px solid #b53cde;
}
.g-main-nav__button__icon {
  display: inline-block;
  color: #24a882;
  transition: transform 0.15s;
  vertical-align: middle;
  margin-left: 0.2em;
  width: 12px;
  height: 12px;
  transform: rotate(180deg);
}
.g-main-nav__button.g-main-nav--closed > .g-main-nav__button__icon {
  transform: rotate(0deg);
}
.g-main-nav__ul {
  list-style: none;
  padding: 0px;
  margin: 0px 0px 0px 1rem;
}
.g-main-nav__ul.g-main-nav--open {
  display: block;
}
.g-main-nav__ul.g-main-nav--closed {
  display: none;
}
@media only screen and (min-width: 48em) {
  .g-main-nav__ul {
    margin: -4px 2rem 0px 2rem;
  }
  .g-main-nav__ul.g-main-nav--closed {
    display: block;
  }
}
</style>
